### PR TITLE
Feature/tropics satellite ioda converter

### LINKED ISSUE #809: convert TROPICS satellite data to IODA
## Description
Create a python based converter for TROPICS satellite data to IODA format

## Requirements

python h5py

## Acceptance Criteria (Definition of Done)
a successful IODA formatted output file is created

### PR DESCRIPTION
**Pull request by BenjaminRuston**
## Description

This converter takes the TROPICS netCDF input file and creates the IODA output 

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #809 

## Acceptance Criteria (Definition of Done)

successfully create a IODA file for TROPICS data to be tested in UFO

## Dependencies

requires python and h5py library

### CODE REVIEW

**Comment by fcvdb** [comment]
I built the ioda-bundle with the feature/tropics_satellite_ioda_converter](https://github.com/JCSDA-internal/ioda-converters/tree/feature/tropics_satellite_ioda_converter) ioda-converters branch. I ran the converter on file:
`/work/noaa/da/bruston/data_repos/tropics/20220328/TROPICS01.BRTT.L1B.Orbit04113.V02-03.ST20220328-025250.ET20220328-042800.CT20220329-180423.nc `
The converter ran file with one and four thread and produced an output file.

**Review by fcvdb — APPROVED** [review]
The converter works great!

**Review by huishao-r — APPROVED** [review]
Looks good to me.

**Review by haydenlj — APPROVED** [review]
looks good, I don't notice any problems

**Comment by rhoneyager** [comment]
Once merged, this could use another PR making changes to the ioda-converters sprint branch to match conventions.

**Pull request merged**
