### PR TITLE
Change the predictor emissivityK to emissivityJacobian following the naming convention

### LINKED ISSUE #1517: Update emissivityK to emissivityJacobian
## Description
`emissivityK` has not been updated to `emissivityJacobian` in satbias_converter*.yaml (test/testinput/) and in the corresponding satbias_*.nc4 files (test/testoutput/varbc/)

## Requirements
Update the predictor's name `emissivityK` -> `emissivityJacobian`

### PR DESCRIPTION
**Pull request by huishao-r**
run-ci-on-draft=true

## Description

emissivityK is no longer supported. Instead, emissivityJacobian should be used. This PR is to fix this.

## Issue(s) addressed

Resolves #1517 

## Dependencies

None 
## Impact

CI should pass with test yaml and test reference

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by BenjaminRuston** [comment]
@huishao-r is this ready for review?

**Review by gthompsnJCSDA — APPROVED** [review]
Thanks @huishao-r   I admit that I am a little confused that this did not become part of the previous PRs for VarBC work.  I realize it was not 100% dependent on that work, but it was logical to include this change into that effort.

**Comment by huishao-r** [comment]
> Thanks @huishao-r I admit that I am a little confused that this did not become part of the previous PRs for VarBC work. I realize it was not 100% dependent on that work, but it was logical to include this change into that effort.

@gthompsnJCSDA I know. This converter was updated using an intermediate name only in the VarBC branch, which didn't show up in develop. We focused on updating the develop files. I assume that was what happened. Of course, ctest reference used the same name so didn't catch this issue either.

**Comment by huishao-r** [comment]
Sorry, I converted it back to draft. I realized there are more variables to be updated. @junmeiban I found some other predictor names might not be right either. Please be cautious when using this converter at this point. I'll push my changes to the same branch.

**Comment by huishao-r** [comment]
@junmeiban I fixed the predictor names for all. I realized this converter was updated before the naming convention was finalized. I fixed the predictor names in the branch now. Would you like to test it from your side? Sorry about this.

**Comment by junmeiban** [comment]
> @junmeiban I fixed the predictor names for all. I realized this converter was updated before the naming convention was finalized. I fixed the predictor names in the branch now. Would you like to test it from your side? Sorry about this.

Thank you so much! I will test it in MPAS-JEDI.

**Comment by junmeiban** [comment]
I generated new `satbias_*.nc4` files by using `satbias_converter.yaml` (updated by @huishao-r ); Tested in MPAS-JEDI and ran successfully. 
Other `satbias_converter*.yaml` and `satbias` files are also corrected by @huishao-r

**Review by junmeiban — APPROVED** [review]

**Comment by junmeiban** [comment]
Many thanks @huishao-r !

**Pull request merged**
