### PR TITLE
CMake modifications for accessing ioda_engines after ioda_engines code is merged with ioda

### PR DESCRIPTION
**Pull request by srherbener**
## Description

This PR contains CMakeLists.txt modifications for accessing ioda_engines once the ioda_engines code is merged into the ioda repository. The merging of the repos is a PR in ioda (jcsda-internal/ioda/pull/44) that will be merged soon.

I've tested this on my iMac and was able to build the EMC bufr converter code successfully both when ioda-converters was a standalone clone and when idoa-converters was part of ioda-bundle.

This likely needs more testing, but I thought submitting this PR now would help get the testing underway.

### Issue(s) addressed

None

## Dependencies

Waiting on the following PRs:
- waiting on JCSDA-internal/ioda/pull/44

## Impact

None

### CODE REVIEW

**Review by rhoneyager — APPROVED** [review]

**Review by aerorahul — APPROVED** [review]

**Comment by travissluka** [comment]
soca builds are broken after this PR.  (https://travis-ci.com/github/JCSDA-internal/soca/jobs/470870112#L914)

1. is CI not running for this repo anymore ??
2. It looks like the build is trying to build the bufr stuff now that the (previously missing in soca) ioda-engines is not longer required, but it is trying to use `bufr.interface.h` headers from `bufr`, even though it seems `bufrlib` not `bufr` is in the container. @mmiesch would rebuilding the containers fix the issue? (seems they haven't been rebuilt since https://github.com/JCSDA-internal/jedi-stack/pull/35)

**Comment by srherbener** [comment]
Recently, we switched to using NCEPLIBS-bufr fork of the EMC repo as the means for providing both the Fortran bufr reader/writer library and the ncepbufr python API. This Fortran library is the "bufr" module. The "bufrlib" module is deprecated now.

The container should have only the bufr module loaded. It might be that the containers have both bufrlib and bufr modules loaded, and that is leading to the confusion.

Also, there was a PR merged yesterday into ioda-converters that enables finding the ioda-engines code from the ioda repository (instead of the now deprecated ioda-engines repository). I suspect that you picked this up, but just wanted to let you know.

**Comment by travissluka** [comment]
> Recently, we switched to using NCEPLIBS-bufr fork of the EMC repo as the means for providing both the Fortran bufr reader/writer library and the ncepbufr python API. This Fortran library is the "bufr" module. The "bufrlib" module is deprecated now.
> 
> The container should have only the bufr module loaded. It might be that the containers have both bufrlib and bufr modules loaded, and that is leading to the confusion.
> 
> Also, there was a PR merged yesterday into ioda-converters that enables finding the ioda-engines code from the ioda repository (instead of the now deprecated ioda-engines repository). I suspect that you picked this up, but just wanted to let you know.

It seems the bufr module was merged into jedi-stack on Dec 17, but the latest docker images are Dec 15, so I'm guessing it didn't make it in?

You can ignore me for now, i'm removing ioda-converters from our travisCI tests for now, I"m sure this will all get sorted out when https://github.com/JCSDA-internal/ioda-converters/issues/370 is addressed

**Comment by mmiesch** [comment]
Yep, looks like the containers still have bufrlib instead of bufr.  I'll create a ZenHub issue for new containers

**Pull request merged**
