### PR TITLE
Update 9 km SMAP soil moisture converter 

### LINKED ISSUE #808: SMAP 9km IODA converter should not depend on directory structure
## Description
The SMAP 9km IODA converter handling of date and time currently depend on the directory structure. More specifically, it depends on the number of '\_' symbols in the path where SMAP data is stored. Lines 107-109 in smap9km_ssm2ioda.py  read the file name and split by '_' to find the part of the file name where the information about date and time are stored.

107         str_split = self.filename.split("_")
108         str_datetime = str_split[7]
109         my_datetime = datetime.strptime(str_datetime, "%Y%m%dT%H%M%S")

This does not work for the following path because the path has '_' symbols in it:
filename:
/scratch2/BMC/gsienkf/Zofia.Stanley/projects/smap_qc/my_Data/SMAP_L2_SM_2016/SMAP_L2_SM_P_E_04892_A_20160101T005308_R17000_001.h5

filename split by '_':
['/scratch2/BMC/gsienkf/Zofia.Stanley/projects/smap', 'qc/my', 'Data/SMAP', 'L2', 'SM', '2016/SMAP', 'L2', 'SM', 'P', 'E', '04892', 'A', '20160101T005308', 'R17000', '001.h5']

## Requirements

Converter should not depend on the path. Ideally the date and time would be read in from SMAP metadata, but I have looked briefly and did not find this in the SMAP data files. 

## Acceptance Criteria (Definition of Done)
SMAP 9km IODA converter should not depend on the path. 

## Dependencies
No dependencies.

@YoulongXia-NOAA @srherbener @ClaraDraper-NOAA

### PR DESCRIPTION
**Pull request by YoulongXia-NOAA**
## Description

Based on the request from the users from Land DA, I added two variables: easeRowIndex and easeColumnIndex. At the same time, the converter dependency on input filename issue is fixed.
 
### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #808 

## Acceptance Criteria (Definition of Done)

ctest passed, testoutput was updated, and the PR is reviewed and merged into develop

## Dependencies

No
## Impact

Please list the other repositories (if any) that this PR will require changes in (example below)
No

### CODE REVIEW

**Comment by YoulongXia-NOAA** [comment]
@zcstanley, based on your request and raised issue, I modified the converter and corresponding testoutput. Please review the python code and look at the output nc file and see if this what you wanted.

**Review by zcstanley — APPROVED** [review]
Thanks Youlong! This looks good to me. I checked a few cases and the datetimes calculated here match the datetimes in tb_time_utc. I have one minor comment which you may choose to incorporate or not. I believe that lines 113 & 114 could be simplified to just one line: 
base_date = datetime(2000,1,1,12,0)

**Comment by YoulongXia-NOAA** [comment]
> Thanks Youlong! This looks good to me. I checked a few cases and the datetimes calculated here match the datetimes in tb_time_utc. I have one minor comment which you may choose to incorporate or not. I believe that lines 113 & 114 could be simplified to just one line: base_date = datetime(2000,1,1,12,0)

Yes, modified you suggested and tested it. Push to github. Thank you for reviewing this PR @zcstanley

**Review by srherbener — APPROVED** [review]
Looks good. Thanks!

**Comment by YoulongXia-NOAA** [comment]
Thank you, @srherbener.

**Pull request merged**
