### PR TITLE
[3D]RTMA Mesonet BUFR tables

### PR DESCRIPTION
**Pull request by PraveenKumar-NOAA**
## Description

This PR provides BUFR tables for each Mesonet data subset, which are described below:

- NC255001 --> MTYP 255-001  Mesonet from MADIS: Denver Urban Drainage  
- NC255002 --> MTYP 255-002  Mesonet from MADIS: RAWS (NIFC)            
- NC255003 --> MTYP 255-003  Mesonet from MADIS: MesoWest (many subpr)  
- NC255004 --> MTYP 255-004  Mesonet from MADIS: APRS WeatherNet        
- NC255005 --> MTYP 255-005  Mesonet from MADIS: Kansas DOT             
- NC255006 --> MTYP 255-006  Mesonet from MADIS: Florida                
- NC255007 --> MTYP 255-007  Mesonet from MADIS: Iowa DOT               
- NC255008 --> MTYP 255-008  Mesonet from MADIS: Minnesota DOT          
- NC255009 --> MTYP 255-009  Mesonet from MADIS: Anything Weather       
- NC255010 --> MTYP 255-010  Mesonet from MADIS: NOS PORTS              
- NC255011 --> MTYP 255-011  Mesonet from MADIS: Aberdeen Proving Grds  
- NC255012 --> MTYP 255-012  Mesonet from MADIS: Weather for You        
- NC255013 --> MTYP 255-013  Mesonet from MADIS: NWS Cooperative Obs    
- NC255014 --> MTYP 255-014  Mesonet from MADIS: NWS HADS               
- NC255015 --> MTYP 255-015  Mesonet from MADIS: AWS                    
- NC255016 --> MTYP 255-016  Mesonet from MADIS: Iowa Environmental     
- NC255017 --> MTYP 255-017  Mesonet from MADIS: Oklahoma               
- NC255018 --> MTYP 255-018  Mesonet from MADIS: Colorado DOT           
- NC255019 --> MTYP 255-019  Mesonet from MADIS: West Texas             
- NC255020 --> MTYP 255-020  Mesonet from MADIS: Wisconsin DOT          
- NC255021 --> MTYP 255-021  Mesonet from MADIS: LSU-JSU                
- NC255022 --> MTYP 255-022  Mesonet from MADIS: Colorado E-470         
- NC255023 --> MTYP 255-023  Mesonet from MADIS: DC Net                 
- NC255024 --> MTYP 255-024  Mesonet from MADIS: Indiana DOT            
- NC255025 --> MTYP 255-025  Mesonet from MADIS: Florida DOT            
- NC255026 --> MTYP 255-026  Mesonet from MADIS: Alaska DOT             
- NC255027 --> MTYP 255-027  Mesonet from MADIS: Georgia DOT            
- NC255028 --> MTYP 255-028  Mesonet from MADIS: Virginia DOT           
- NC255029 --> MTYP 255-029  Mesonet from MADIS: MO Comm Agric. Wx Net  
- NC255030 --> MTYP 255-030  Mesonet from MADIS: other than above       
- NC255031 --> MTYP 255-031  Urbanet from MADIS: UrbaNet                
- NC255032 --> MTYP 255-032  Urbanet from MADIS: USouthAL               
- NC255101 --> MTYP 255-101  Coop from MADIS: NEPP &  HCN-Modrnzd- NOA  
- NC255102 --> MTYP 255-102  Coop from SHEF fmt: All NWS Coop Obs       
- NC255111 --> MTYP 255-111  Mesonet from MADIS: Climate Refrnce Netwk  
- NC255131 --> MTYP 255-131  Hydro from MADIS: Denver Urban Drainage    
- NC255160 --> MTYP 255-160  Hydro from MADIS: other than above         
- NC255161 --> MTYP 255-161  Snow data from MADIS: many different prov  

**New BUFR tables:** 
There are a total of thirty-eight mesonet subsets. A total of six BUFR tables are created to cover all of these subsets.  The following six files are added to the following directory: /doc/bufr_table_samples

- mesonet.nc255001.bufr.table.txt (for first 32 subsets nc255001 - nc255032)
- mesonet.nc255101.bufr.table.txt
- mesonet.nc255102.bufr.table.txt
- mesonet.nc255111.bufr.table.txt
- mesonet.nc255131.bufr.table.txt (for subsets nc255131 and nc255160)
- mesonet.nc255161.bufr.table.txt

Information for the mnemonics, units, and their descriptions, etc. is provided. 

### Issue(s) addressed
The following issue is addressed partially #1132, which belongs to the OBS Team pipeline. 

## Acceptance Criteria (Definition of Done)
It will be done once all-important mnemonics are determined and documented.

## Dependencies
None

## Impact
None

### CODE REVIEW

**Review by nicholasesposito — APPROVED** [review]
Looks good to me

**Review by BenjaminRuston — APPROVED** [review]
@PraveenKumar-NOAA see these are just samples these are to help guide decoding and other tasks?

**Comment by MatthewMorris-NOAA** [comment]
@PraveenKumar-NOAA I noticed that some of the mnemonics included were not in our initial files. Why were these added? Also, some of the mnemonics aren't included in all of the subsets. Is there a reason for this?

**Comment by PraveenKumar-NOAA** [comment]
> @PraveenKumar-NOAA I noticed that some of the mnemonics included were not in our initial files. Why were these added? Also, some of the mnemonics aren't included in all of the subsets. Is there a reason for this?

@MatthewMorris-NOAA These subset BUFR tables are created/separated from the mesonet table, tab_3DRTMA_msonet_t0000z, that I shared with you and there are no extra added mnemonics. Each subset has a different set of mnemonics, for example, see below for subset NC255161:

| NC255161 | YEAR  MNTH  DAYS  HOUR  MINU  {RCPTIM}  RPID  {SPRVID}  CLATH     |
| NC255161 | CLONH  SELV  SRMK  {FILENAME}  <MNTOSDSQ>  {SNSWEMSQ}  {MNDOFSSQ} |.

The reason is to have a BUFR table for subset-type-specific mnemonics like mesonet.nc255161.bufr.table.txt for NC255161, which is required for the development/test purpose and easy to handle compared to the full table.

**Review by MatthewMorris-NOAA — APPROVED** [review]
Looks good!

**Pull request merged**
