### PR TITLE
Update the sprint branch with as much of ```develop``` branch as possible for November code sprint

### PR DESCRIPTION
**Pull request by gthompsnJCSDA**
## Description

This feature branch is a ```merge -X theirs``` (develop) into ```feature/sprint-ioda-converters``` followed by deciding each and every 174 files that needed to be ejudicated.  In their entirety, all code additions/changes made by Ron McLaren for BUFR query_cxx (and its related PRs) that were merged to develop are incorporated into this branch.  As such, many ```testinput``` YAML and testing files were changed/added as well as many ```testoutput``` files.  Some of these changes are not compatible with JEDI Data Conventions and need to be fixed again within this new branch.  Most of the Python converters and ```ioda-data``` and ```ioda-converters/testoutput``` were already updated for data conventions within the sprint branch.  A few specific files may not have met requirements once develop is merged here and will require intervention again.  That list should be short.

### Issue(s) addressed

Will find a pre-existing issue or create a new one for documentation purposes.

## Acceptance Criteria (Definition of Done)

This PR will **NOT** produce passing ctests at this time.  However, this PR is absolutely necessary to simplify the code sprint staring 14 Nov in which we plan to update UFO to the Data Conventions and will also fix the files that produce errors in ioda-converters.  Merging this pull request ahead of the code sprint will provide common starting point in all repos for the sprint.  Hopefully at the end of the code sprint, all ctests will pass again in which case both UFO and IODA can use new naming conventions properly in the develop branch.

## Dependencies

This repo depends on ```feature/sprint-ioda-converters``` in the ioda repo.  A number of updates therein provide tools to update testinput files to do variable re-naming.

## Impact

Hopefully none.

### CODE REVIEW

**Comment by gthompsnJCSDA** [comment]
@mikecooke77   Just FYI.  I am optimistic this starting update to ```ioda-converters/feature/sprint-ioda-converters``` will enable us to update the sprint branch very near to ```develop``` branch such that if we succeed at UFO side, then both can be merged almost simultaneously.  Not asking for your review, we just need others to merge to facilitate our sprint.

**Review by CoryMartin-NOAA — APPROVED** [review]
Builds on Hera, thanks @gthompsnJCSDA

**Review by huishao-r — APPROVED** [review]

**Review by srherbener — APPROVED** [review]
Thanks for doing all of this hard work to get this prepared!

**Comment by huishao-r** [comment]
@srherbener Can you merge this? Ben and Pat are not available at this point

**Comment by srherbener** [comment]
@gthompsnJCSDA are you ready for this to be merged? Just want to double check before doing the merge. Thanks

**Comment by gthompsnJCSDA** [comment]
> @gthompsnJCSDA are you ready for this to be merged? Just want to double check before doing the merge. Thanks


Yes please Steve!  This will be helpful and thanks a bunch!

**Pull request merged**
