### PR TITLE
Feature/query new result

### PR DESCRIPTION
**Pull request by rmclaren**
## Description

Major refactor of the ResultSet. The major benefits are

1) Improves code readability and maintainability (should be much easier to understand).
2) Major performance improvement (eliminates some large performance bottlenecks).
3) Should improve reliability of group_by operation.
4) Fixes some bugs.

## Issue(s) addressed

#993 
#1345

## Dependencies

List the other PRs that this PR is dependent on:
- https://github.com/NOAA-EMC/NCEPLIBS-bufr/pull/519
- https://github.com/JCSDA-internal/ioda-converters/pull/1325

## Impact

Improved performance.

### CODE REVIEW

**Comment by rmclaren** [comment]
@nicholasesposito Please validate ACID issue.

**Comment by PatNichols** [comment]
@rmclaren does this PR supersede the other one? Do we need to merge both in order ?? Does the ncep-buffer PR need to be merged before/after/same time as this ? Sorry I am a little confused.

**Comment by rmclaren** [comment]
@PatNichols The PR's build on top of each other; they do not supersede each other... They should be merged in the order indicated.

**Comment by rmclaren** [comment]
@PatNichols The one NCEPLIB-bufr PR that is outstanding needs to be merged for long string support (feature/query_long_str_4) I believe that PR already indicates this (as a dependency).

**Comment by rmclaren** [comment]
@PatNichols Just to be clear the order of merges is as follows:

1. #1221 
2. #1325   (Depends on https://github.com/NOAA-EMC/NCEPLIBS-bufr/pull/519 and #1221)
3. #1344   (Depends on https://github.com/NOAA-EMC/NCEPLIBS-bufr/pull/519 and #1325)

**Comment by PatNichols** [comment]
> @PatNichols Just to be clear the order of merges is as follows:
> 
> 1. [Refactored QueryRunner::collectData #1221](https://github.com/JCSDA-internal/ioda-converters/pull/1221)
> 2. [BUFR query: Handle long strings from BUFR files #1325](https://github.com/JCSDA-internal/ioda-converters/pull/1325)   (Depends on [Feature/expose readlc c NOAA-EMC/NCEPLIBS-bufr#519](https://github.com/NOAA-EMC/NCEPLIBS-bufr/pull/519) and [Refactored QueryRunner::collectData #1221](https://github.com/JCSDA-internal/ioda-converters/pull/1221))
> 3. [Feature/query new result #1344](https://github.com/JCSDA-internal/ioda-converters/pull/1344)   (Depends on [Feature/expose readlc c NOAA-EMC/NCEPLIBS-bufr#519](https://github.com/NOAA-EMC/NCEPLIBS-bufr/pull/519) and [BUFR query: Handle long strings from BUFR files #1325](https://github.com/JCSDA-internal/ioda-converters/pull/1325))

@rmclaren Thank you for explaining this to me.  It is now clear to me now how to handle these merges.

**Comment by nicholasesposito** [comment]
@rmclaren  To test the ACID issue, should I be building feature/query_long_str_4 or feature/query_new_result ?

**Comment by rmclaren** [comment]
@nicholasesposito query_new_result

**Comment by nicholasesposito** [comment]
@rmclaren Ok I was able to set everything up. I ran a yaml with a full aircraft_profiles prepbufr file (the one with the two different ACID sequences). I can see results of the query for both the AIRCFT and AIRCAR sequences, and can therefore confirm that this indeed works! Thank you for all your hard work!

**Comment by rmclaren** [comment]
Cool! Thanks for taking the time to look at this for me.

**Review by nicholasesposito — APPROVED** [review]
I think it looks good

**Review by srherbener — COMMENTED** [review]
Does this PR depend on bufr@12.0.0? Is that why the build fails? spack-stack@1.5.0, which contains bufr@12.0.0 is getting tested this week with the target of releasing it by the end of this week. I'm not sure when the CI testing is getting updated, but it should be soon after the release.

I think in general the code looks good.

**Comment by rmclaren** [comment]
This project depends on the next release of NCEPLIB-bufr which has not been tagged yet (same as feature/query_long_str_4). It may end up being v12.0.1.

**Review by PraveenKumar-NOAA — APPROVED** [review]
Built and tested using a new long string wigos variable. 
Looks good to me.

**Comment by PatNichols** [comment]
@rmclaren Same here as the previous PR. Could you resolve the conflcts. Thank you!

**Comment by rmclaren** [comment]
@srherbener Both branches should be good.

**Review by srherbener — APPROVED** [review]

**Pull request merged**
