### PR TITLE
Feature/query cxx adpsfc hblcs

### PR DESCRIPTION
**Pull request by nicholasesposito**
## Description
The mnemonic HBLCS which is known as the variable "heightAboveSurfaceOfBaseOfLowestCloud" should not have any units (previously "m" or meter) as it is a "CODE TABLE" in the bufrTable. This gets rid of the "units" line in the yamls and updates the output data.

It should be paired with the ioda branch "feature/query_cxx_adpsfc_hblcs", which contains 1 update to the ObsSpace.yaml file.

Additionally the Wind Quality Marker mnemonic (QMWN) was not initially in due to decisions previously made. It was newly decided that it should be in the bufr. That change is now in this PR as well.

It updates:
/test/testinput/bufr_ncep_prepbufr_adpsfc.yaml
/test/testinput/bufr_ncep_adpsfc.yaml
test/testrun/gdas.t12z.adpsfc.tm00.nc
test/testrun/gdas.t12z.adpsfc.prepbufr.nc

## Acceptance Criteria (Definition of Done)
It will be finished once the tests pass.

### Issue(s) addressed)
#990 #994 

## Impact

Please list the other repositories (if any) that this PR will require changes in (example below)

- [ ] ioda

### CODE REVIEW

**Comment by nicholasesposito** [comment]
@emilyhcliu @rmclaren @YoulongXia-NOAA @PraveenKumar-NOAA 

I found a small error in the adpsfc yamls. The mnemonic "HBLCS" should not have had units of "m", since it was a CODE TABLE. This PR/issue fixes that.

**Comment by nicholasesposito** [comment]
@emilyhcliu @rmclaren @YoulongXia-NOAA @PraveenKumar-NOAA I have added the QMWN mnemonic as well.

**Comment by BenjaminRuston** [comment]
whew,,, @nicholasesposito  looks like this is  a blocker now for PR #1034 which is a blocker for PR #1044 

is this correct?

**Comment by nicholasesposito** [comment]
@BenjaminRuston Yes. @emilyhcliu @rmclaren @YoulongXia-NOAA @PraveenKumar-NOAA  please review and accept.

**Comment by emilyhcliu** [comment]
@nicholasesposito looking into it now.

**Comment by PraveenKumar-NOAA** [comment]
> @BenjaminRuston Yes. @emilyhcliu @rmclaren @YoulongXia-NOAA @PraveenKumar-NOAA please review and accept.

@nicholasesposito I think I approved this already.

**Comment by nicholasesposito** [comment]
@PraveenKumar-NOAA It does not say you have approved it yet.

**Comment by emilyhcliu** [comment]
@nicholasesposito 
Your branch will need to merge with the develop and do a git push.

**Comment by PraveenKumar-NOAA** [comment]
> @PraveenKumar-NOAA It does not say you have approved it yet.

@nicholasesposito sorry I approved #742, both look similar.

**Comment by nicholasesposito** [comment]
@BenjaminRuston @emilyhcliu @PraveenKumar-NOAA @rmclaren  Because this branch is basically moot with the update of types, I think we ignore this. The newest adpsfc files in the types branch have the updated HBLCS unit/type. What do you think?

HOWEVER, we need to update ObsSpace.yaml with HBLCS. Please see https://github.com/JCSDA-internal/ioda/pull/742 as soon as possible and approve it.

**Comment by emilyhcliu** [comment]
> @BenjaminRuston @emilyhcliu @PraveenKumar-NOAA @rmclaren Because this branch is basically moot with the update of types, I think we ignore this. The newest adpsfc files in the types branch have the updated HBLCS unit/type. What do you think?
> 
> HOWEVER, we need to update ObsSpace.yaml with HBLCS. Please see [JCSDA-internal/ioda#742](https://github.com/JCSDA-internal/ioda/pull/742) as soon as possible and approve it.

@nicholasesposito The ObsSpace.yaml under feature/query_cxx has been merged into IODA repository.  
I agree, we can ditch this one.  
Ron had merged your [feature/query_cxx_types_NE_adpsfc branch](https://github.com/JCSDA-internal/ioda-converters/pull/1034).

**Pull request closed without merging**
