### PR TITLE
Ioda-converters YAML for [3D]-RTMA ADPUPA BUFR

### LINKED ISSUE #1450: Example YAMLs for the [3D]-RTMA ADPUPA prepBUFR/ BUFR Data
## Description
**The purpose of this issue is to**:
Write example YAMLs that can convert the [3D- RTMA ADPUPA prepBUFR/BUFR files into the IODA format for the following subsets:

**_**prepBUFR**:_** ADPUPA 

**_BUFR:_** 
NC002001 | A63218 | MSG TYPE 002-001  RAWINSONDE - FIXED LAND          
NC002002 | A63219 | MSG TYPE 002-002  RAWINSONDE - MOBIL LAND                
NC002003 | A63220 | MSG TYPE 002-003  RAWINSONDE - SHIP                      
NC002004 | A63221 | MSG TYPE 002-004  DROPWINSONDE                           
NC002005 | A63222 | MSG TYPE 002-005  PIBAL                                  
NC002006 | A62207 | MSG TYPE 002-006  OZONESONDE (LOW-RES) (FROM METO BUFR)  
NC002007 | A63223 | MSG TYPE 002-007  NOAA PROFILER NETWORK (NPN) WINDS      
NC002008 | A63224 | MSG TYPE 002-008  NeXRaD VAD WINDS FROM RADAR CODED MSG  
NC002009 | A61200 | MSG TYPE 002-009  PROFILER WINDS IN PILOT(PIBAL) FORMAT  
NC002010 | A61204 | MSG TYPE 002-010  NPN AND MAP PROFILER SPECTRAL MOMENTS  
NC002011 | A52201 | MSG TYPE 002-011  MULTI-AGENCY PROFILER (MAP) WINDS      
NC002012 | A52202 | MSG TYPE 002-012  NPN AND MAP RASS TEMPERATURES          
NC002013 | A52203 | MSG TYPE 002-013  JAPANESE MET AGENCY PROFILER WINDS     
NC002014 | A52205 | MSG TYPE 002-014  OTHER PROFILER WINDS (BUFR)            
NC002015 | A62208 | MSG TYPE 002-015  OZONESONDE (HIGH-RES) (FROM ASCII)     
NC002016 | A52206 | MSG TYPE 002-016  EUROPEAN PROFILER WINDS                
NC002017 | A63191 | MSG TYPE 002-017  NeXRaD VAD WINDS FROM LEVEL 2 DECODER  
NC002018 | A51060 | MSG TYPE 002-018  OTHER RADAR VAD WINDS (BUFR)           
NC002020 | A56251 | MSG TYPE 002-020  WIND ENERGY TOWER, RESTRICTED          
NC002021 | A56252 | MSG TYPE 002-021  WIND ENERGY TOWER                      
NC002101 | A51101 | MSG TYPE 002-101  RAWINSONDE - FIXED LAND (BUFR)         
NC002102 | A51102 | MSG TYPE 002-102  RAWINSONDE - MOBIL LAND (BUFR)         
NC002103 | A51103 | MSG TYPE 002-103  RAWINSONDE - SHIP (BUFR)               
NC002104 | A51104 | MSG TYPE 002-104  DROPWINSONDE (BUFR)                    
NC002105 | A51105 | MSG TYPE 002-105  PIBAL (BUFR)                           

- Global ADPUPA YAMLs will be used as a reference 
- Use these YAMLs to convert into an IODA-formatted netCDF file
- Add outputs to the ioda-converter testoutput directory
- Add tests to the CMakeLists.txt files
- Have the tests pass

## Requirements

- All important mnemonics need to be known.

## Acceptance Criteria (Definition of Done)

- It will be finished when all files have been checked and tests have passed.

## Dependencies

- _The bufr2ioda.x_

### PR DESCRIPTION
**Pull request by PraveenKumar-NOAA**
## Description

This PR adds an ioda-converters YAML for the [3D]-RTMA ADPUPA BUFR data.

The following files are new/ modified:

testinput/bufr_ncep_rtma_adpupa.yaml
testinput/rtma.t00z.adpupa.tm00.bufr_d
testoutput/rtma.t00z.adpupa.tm00.nc
CMakeLists.txt

The ioda-validation test is performed and following results were obtained:

**Final results:**
_errors: 0
warnings: 0_

The validation of the output ioda obs is also performed in: https://github.com/JCSDA-internal/ioda-converters/issues/1451

## Issue(s) addressed

Resolves #1450 

## Dependencies

None

## Impact

None

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by MatthewMorris-NOAA — APPROVED** [review]
Looks good!

**Review by nicholasesposito — APPROVED** [review]

**Comment by nicholasesposito** [comment]
Looks great

**Comment by fcvdb** [comment]
@PraveenKumar-NOAA The Netcdf output file size is a little bit large (2.48Mb), is there a way you could subsample the input BUFR file to reduce the size of the output? Thanks.

**Comment by PraveenKumar-NOAA** [comment]
> @PraveenKumar-NOAA The Netcdf output file size is a little bit large (2.48Mb), is there a way you could subsample the input BUFR file to reduce the size of the output? Thanks.

@fcvdb I used only one subset for the BUFR file and which is less than 1 Mb. I am not sure if it can be reduced further. Similar is true for for prepBUFR PR.

**Comment by PraveenKumar-NOAA** [comment]
@fcvdb @PatNichols I fixed the file sizes, thanks to @ADCollard.

**Review by PatNichols — APPROVED** [review]
Thanks for reducing the file sizes.

**Review by BenjaminRuston — APPROVED** [review]
thank you @PraveenKumar-NOAA for this very critical decoder

**Comment by BenjaminRuston** [comment]
thank you @PraveenKumar-NOAA I've run this on a file like this which would be obtained from either the NCAR RDA archive or the NOMADS server and it completed fine and produced a reasonable looking file:

`gdas.adpupa.t00z.20220216.bufr`

```
file: 20220215T21_PT6H_adpupa_nesdis_bufr.nc4
range(/MetaData/dataReceiptTime): [--, --]
range(/MetaData/dateTime): [2022-02-15 21:00:00, 2022-02-16 02:00:00]
range(/MetaData/latitude): [-90.0, 82.5]
range(/MetaData/longitude): [-170.7100067138672, 179.22000122070312]
range(/MetaData/stationElevation): [-22, 4508]
range(/MetaData/stationIdentification): [02527, ZVQEQCM]
range(/MetaData/stationWIGOSId): [, ]
range(/ObsValue/airTemperature): [185.85000610351562, 307.1499938964844]
range(/ObsValue/dewPointTemperature): [163.25, 300.1499938964844]
range(/ObsValue/pressure): [300, 109900]
range(/ObsValue/windDirection): [0, 360]
range(/ObsValue/windSpeed): [0.0, 156.0]
range(/QualityMarker/airTemperature): [14, 14]
range(/QualityMarker/dewPointTemperature): [14, 14]
range(/QualityMarker/pressure): [14, 14]
range(/QualityMarker/stationElevation): [1, 1]
range(/QualityMarker/windSpeed): [14, 14]
```

one thing I notice is the `pressure` variable is not in `MetaData` which has been standard practice with `radiosonde` .  It is instead under the `ObsValue` 

@gthompsnJCSDA and @CoryMartin-NOAA  and @emilyhcliu we should discuss think we can move forward for now, but believe our current practice is to have `pressure` under `MetaData` as it is essentially the location information

**Comment by BenjaminRuston** [comment]
getting this plot for the above file for observation only:
image

**Comment by gthompsnJCSDA** [comment]
FYI. This is already merged but the ObsTeam needs to do a better job with validating the incoming data against the IODA-validate program.  The dimension name `RadiosondeReportLevelData` is ad hoc and never before seen.  I realize we have been lax with ioda-validate set to ignore warnings and errors, but it's up to our own team and reviewers to know that we cannot allow new entires to go against the conventions or else we have no point in the conventions.

Let's be sure to correct the dimension name and `MetaData/pressure` in place of `ObsValue/pressure` in a subsequent PR please.

**Pull request merged**
