### PR TITLE
add airnow converter for ioda-v2

### PR DESCRIPTION
**Pull request by ytangnoaa**
## Description

*(Instructions: replace text in this and all sections with your own text)*

Provide a detailed description of what this PR does.

What problem does it fix? What new capability does it add?

It added a new capability to converted AIRNow data (https://airnow.gov) to JEDI IODA V2 format.
With this capability, we can assimilate AIRNow data in JEDI
 
[See the JEDI Documentation](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/pullrequest.html) for further information.

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #<issue_number>
N/A
If this does not close an existing issue, then [be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## Acceptance Criteria (Definition of Done)

What does it mean for this PR to be finished?

## Dependencies
No dependency. It is a standalone process that only needs JEDI python package.

If there are PRs that need to be merged before or along with this one, please add "waiting for another PR" label and list the dependencies in the other repositories (example below). Note that the branches in the other repositories should have matching names for the automated tests to pass.
Waiting on the following PRs:
- [ ] waiting on JCSDA/eckit/pull/<pr_number>
- [ ] waiting on JCSDA/atlas/pull/<pr_number>

## Impact

Please list the other repositories (if any) that this PR will require changes in (example below)

No other change this time

- [ ] saber
- [ ] ufo
- [ ] ...

## Test Data

Please list the test data (if any) that needs to be updated on AWS to the best of your knowledge (example below).

No other change this time

- [ ] saber
- [ ] ioda
- [ ] ...

### CODE REVIEW

**Comment by liuxiao37k** [comment]
Hello @ytangnoaa! I am happy to contribute but wanted to confirm that you meant to ask ME (Xiao Liu @ EMC) to review. Air Quality is beyond my expertise (I work on ocean biogeochemistry and Ocean Color), but, again, I am happy to contribute if I can be of any help. Thanks.

**Comment by ytangnoaa** [comment]
Hello, Xiao

Thank you for your prompt response. This pull request is about an
engineering issue, not related to any scientific background.
So, as long as you are familiar with IODA converter, you are the good
expert  for reviewing this request.

Thanks again

Youhua Tang


NOAA Air Resources Laboratory
5830 University Research Court #4253
College Park, Maryland  20740
Phone: 301-683-1388

**Comment by ytangnoaa** [comment]
Cory

Thank you for your suggestion. You are right that I write out the netCDF
file directly instead of through the IODA routine.
We can change it when the IODA library supports the IODA-2 format.

Thanks

Youhua

**Review by srherbener — APPROVED** [review]
I think this looks good now. The ioda converter library is being used (which outputs idoa-v1 format) putting you in a good position to easily transfer over to the new ioda converter library based on ioda-v2 (when it is ready). And for now the ioda-upgrade.x application can be used to convert the ioda-v1 file this converter outputs to ioda-v2.

**Comment by srherbener** [comment]
@CoryMartin-NOAA have all your comments been addressed? Thanks

**Comment by ytangnoaa** [comment]
Stephen

Thank you for your action. So next time, when the ioda-v2 modules are in
place, this PR will be automatically converted to
new format, which is convenient. All my comments are addressed.

Thank you again
Youhua



NOAA Air Resources Laboratory
5830 University Research Court #4253
College Park, Maryland  20740
Phone: 301-683-1388

**Comment by srherbener** [comment]
> Stephen Thank you for your action. So next time, when the ioda-v2 modules are in place, this PR will be automatically converted to new format, which is convenient. All my comments are addressed. Thank you again Youhua NOAA Air Resources Laboratory 5830 University Research Court #4253 College Park, Maryland 20740 Phone: 301-683-1388

I wish it could be automatic, but the conversion to ioda-v2 may require some modification to the code outside the library. The primary thing is to change the organization of radiance data from a set of 1D variables (one per channel, dimensioned by locations) to a single 2D variable (dimensioned locations X channels). I don't think this converter (airnow2ioda.py) has this particular issue, but there still might be a couple minor things to address.

We are organizing a code sprint to take place this summer (mid-July perhaps) to migrate the converters to the new ioda-v2 library after the library is ready. You may want to consider attending. We will give more updates to everyone as we get the code sprint schedule worked out.

**Comment by srherbener** [comment]
@ytangnoaa thank you for your patience as we work through the transition from ioda-v1 to ioda-v2!

**Review by CoryMartin-NOAA — APPROVED** [review]
I think my comments have been addressed, will revisit when we convert to IODAv2

**Comment by srherbener** [comment]
@CoryMartin-NOAA thanks for your review.

The tests are failing due to coding norms errors:
```
test 1
--
813 | Start 1: iodaconv_chem_coding_norms
814 |  
815 | 1: Test command: /build_container/bin/iodaconv_lint.sh "/jcsda/ioda-bundle/iodaconv/src/chem" "/jcsda/ioda-bundle/iodaconv"
816 | 1: Environment variables:
817 | 1:  OMP_NUM_THREADS=1
818 | 1: Test timeout computed to be: 10000000
819 | 1: + SRC_DIR=/jcsda/ioda-bundle/iodaconv/src/chem
820 | 1: + PYCODESTYLE_CFG_PATH=/jcsda/ioda-bundle/iodaconv
821 | 1: + cd /jcsda/ioda-bundle/iodaconv/src/chem
822 | 1: + pycodestyle -v --config=/jcsda/ioda-bundle/iodaconv/.pycodestyle --filename=*.py,*.py.in .
823 | 1: cli configuration: /jcsda/ioda-bundle/iodaconv/.pycodestyle
824 | 1: directory .
825 | 1: checking ./airnow2ioda-nc.py
826 | 1: ./airnow2ioda-nc.py:19:1: E302 expected 2 blank lines, found 1
827 | 1: ./airnow2ioda-nc.py:21:9: E117 over-indented
828 | 1: ./airnow2ioda-nc.py:42:1: E302 expected 2 blank lines, found 1
829 | 1: ./airnow2ioda-nc.py:54:1: W293 blank line contains whitespace
830 | 1: ./airnow2ioda-nc.py:55:1: E302 expected 2 blank lines, found 1
831 | 1: ./airnow2ioda-nc.py:67:1: E302 expected 2 blank lines, found 1
832 | 1: ./airnow2ioda-nc.py:67:20: E231 missing whitespace after ','
833 | 1: ./airnow2ioda-nc.py:68:4: E111 indentation is not a multiple of four
834 | 1: ./airnow2ioda-nc.py:68:6: E225 missing whitespace around operator
835 | 1: ./airnow2ioda-nc.py:68:25: E231 missing whitespace after ','
836 | 1: ./airnow2ioda-nc.py:69:27: E127 continuation line over-indented for visual indent
837 | 1: ./airnow2ioda-nc.py:70:27: E127 continuation line over-indented for visual indent
838 | 1: ./airnow2ioda-nc.py:71:27: E127 continuation line over-indented for visual indent
839 | 1: ./airnow2ioda-nc.py:72:4: E111 indentation is not a multiple of four
840 | 1: ./airnow2ioda-nc.py:73:13: E127 continuation line over-indented for visual indent
841 | 1: ./airnow2ioda-nc.py:74:4: E111 indentation is not a multiple of four
842 | 1: ./airnow2ioda-nc.py:75:4: E111 indentation is not a multiple of four
843 | 1: ./airnow2ioda-nc.py:76:4: E111 indentation is not a multiple of four
844 | 1: ./airnow2ioda-nc.py:77:4: E111 indentation is not a multiple of four
845 | 1: ./airnow2ioda-nc.py:78:4: E111 indentation is not a multiple of four
846 | 1: ./airnow2ioda-nc.py:79:33: E127 continuation line over-indented for visual indent
847 | 1: ./airnow2ioda-nc.py:80:33: E127 continuation line over-indented for visual indent
848 | 1: ./airnow2ioda-nc.py:81:4: E111 indentation is not a multiple of four
849 | 1: ./airnow2ioda-nc.py:82:4: E111 indentation is not a multiple of four
850 | 1: ./airnow2ioda-nc.py:83:1: W293 blank line contains whitespace
851 | 1: ./airnow2ioda-nc.py:84:4: E111 indentation is not a multiple of four
852 | 1: ./airnow2ioda-nc.py:85:4: E111 indentation is not a multiple of four
853 | 1: ./airnow2ioda-nc.py:86:4: E111 indentation is not a multiple of four
854 | 1: ./airnow2ioda-nc.py:87:4: E111 indentation is not a multiple of four
855 | 1: ./airnow2ioda-nc.py:88:4: E111 indentation is not a multiple of four
856 | 1: ./airnow2ioda-nc.py:89:1: W293 blank line contains whitespace
857 | 1: ./airnow2ioda-nc.py:90:1: E305 expected 2 blank lines after class or function definition, found 1
858 | 1: ./airnow2ioda-nc.py:93:2: E111 indentation is not a multiple of four
859 | 1: ./airnow2ioda-nc.py:94:9: E126 continuation line over-indented for hanging indent
860 | 1: ./airnow2ioda-nc.py:97:5: E121 continuation line under-indented for hanging indent
861 | 1: ./airnow2ioda-nc.py:99:2: E111 indentation is not a multiple of four
862 | 1: ./airnow2ioda-nc.py:100:2: E111 indentation is not a multiple of four
863 | 1: ./airnow2ioda-nc.py:101:9: E126 continuation line over-indented for hanging indent
864 | 1: ./airnow2ioda-nc.py:104:2: E111 indentation is not a multiple of four
865 | 1: ./airnow2ioda-nc.py:105:9: E126 continuation line over-indented for hanging indent
866 | 1: ./airnow2ioda-nc.py:108:2: E111 indentation is not a multiple of four
867 | 1: ./airnow2ioda-nc.py:109:9: E126 continuation line over-indented for hanging indent
868 | 1: ./airnow2ioda-nc.py:113:2: E111 indentation is not a multiple of four
869 | 1: ./airnow2ioda-nc.py:114:2: E111 indentation is not a multiple of four
870 | 1: ./airnow2ioda-nc.py:114:17: E231 missing whitespace after ','
871 | 1: ./airnow2ioda-nc.py:114:28: E231 missing whitespace after ','
872 | 1: ./airnow2ioda-nc.py:115:2: E111 indentation is not a multiple of four
873 | 1: ./airnow2ioda-nc.py:115:3: E225 missing whitespace around operator
874 | 1: ./airnow2ioda-nc.py:115:23: E231 missing whitespace after ','
875 | 1: ./airnow2ioda-nc.py:117:2: E111 indentation is not a multiple of four
876 | 1: ./airnow2ioda-nc.py:117:4: E225 missing whitespace around operator
877 | 1: ./airnow2ioda-nc.py:117:29: E231 missing whitespace after ','
878 | 1: ./airnow2ioda-nc.py:117:38: E231 missing whitespace after ','
879 | 1: ./airnow2ioda-nc.py:118:2: E111 indentation is not a multiple of four
880 | 1: ./airnow2ioda-nc.py:118:7: E231 missing whitespace after ','
881 | 1: ./airnow2ioda-nc.py:118:15: E225 missing whitespace around operator
882 | 1: ./airnow2ioda-nc.py:119:1: W293 blank line contains whitespace
883 | 1: ./airnow2ioda-nc.py:120:2: E111 indentation is not a multiple of four
884 | 1: ./airnow2ioda-nc.py:120:13: E201 whitespace after '{'
885 | 1: ./airnow2ioda-nc.py:121:5: E128 continuation line under-indented for visual indent
886 | 1: ./airnow2ioda-nc.py:121:15: E231 missing whitespace after ','
887 | 1: ./airnow2ioda-nc.py:122:2: E111 indentation is not a multiple of four
888 | 1: ./airnow2ioda-nc.py:122:14: E201 whitespace after '{'
889 | 1: ./airnow2ioda-nc.py:123:1: W293 blank line contains whitespace
890 | 1: ./airnow2ioda-nc.py:124:2: E111 indentation is not a multiple of four
891 | 1: ./airnow2ioda-nc.py:124:21: E201 whitespace after '['
892 | 1: ./airnow2ioda-nc.py:125:4: E128 continuation line under-indented for visual indent
893 | 1: ./airnow2ioda-nc.py:125:24: E231 missing whitespace after ','
894 | 1: ./airnow2ioda-nc.py:125:44: E231 missing whitespace after ','
895 | 1: ./airnow2ioda-nc.py:125:68: E231 missing whitespace after ','
896 | 1: ./airnow2ioda-nc.py:128:2: E111 indentation is not a multiple of four
897 | 1: ./airnow2ioda-nc.py:129:1: W293 blank line contains whitespace
898 | 1: ./airnow2ioda-nc.py:130:2: E111 indentation is not a multiple of four
899 | 1: ./airnow2ioda-nc.py:131:2: E111 indentation is not a multiple of four
900 | 1: ./airnow2ioda-nc.py:132:2: E111 indentation is not a multiple of four
901 | 1: ./airnow2ioda-nc.py:133:2: E111 indentation is not a multiple of four
902 | 1: ./airnow2ioda-nc.py:134:2: E111 indentation is not a multiple of four
903 | 1: ./airnow2ioda-nc.py:135:2: E111 indentation is not a multiple of four
904 | 1: ./airnow2ioda-nc.py:135:19: E225 missing whitespace around operator
905 | 1: ./airnow2ioda-nc.py:136:2: E111 indentation is not a multiple of four
906 | 1: ./airnow2ioda-nc.py:136:13: E225 missing whitespace around operator
907 | 1: ./airnow2ioda-nc.py:137:1: W293 blank line contains whitespace
908 | 1: ./airnow2ioda-nc.py:138:2: E111 indentation is not a multiple of four
909 | 1: ./airnow2ioda-nc.py:138:22: E231 missing whitespace after ','
910 | 1: ./airnow2ioda-nc.py:139:3: E111 indentation is not a multiple of four
911 | 1: ./airnow2ioda-nc.py:139:23: E225 missing whitespace around operator
912 | 1: ./airnow2ioda-nc.py:139:25: E231 missing whitespace after ','
913 | 1: ./airnow2ioda-nc.py:140:3: E111 indentation is not a multiple of four
914 | 1: ./airnow2ioda-nc.py:140:23: E225 missing whitespace around operator
915 | 1: ./airnow2ioda-nc.py:140:25: E231 missing whitespace after ','
916 | 1: ./airnow2ioda-nc.py:141:3: E111 indentation is not a multiple of four
917 | 1: ./airnow2ioda-nc.py:141:22: E225 missing whitespace around operator
918 | 1: ./airnow2ioda-nc.py:141:24: E231 missing whitespace after ','
919 | 1: ./airnow2ioda-nc.py:142:1: W293 blank line contains whitespace
920 | 1: ./airnow2ioda-nc.py:143:2: E111 indentation is not a multiple of four
921 | 1: ./airnow2ioda-nc.py:143:3: E225 missing whitespace around operator
922 | 1: ./airnow2ioda-nc.py:143:20: E231 missing whitespace after ','
923 | 1: ./airnow2ioda-nc.py:144:2: E111 indentation is not a multiple of four
924 | 1: ./airnow2ioda-nc.py:144:6: E225 missing whitespace around operator
925 | 1: ./airnow2ioda-nc.py:145:2: E111 indentation is not a multiple of four
926 | 1: ./airnow2ioda-nc.py:145:23: E225 missing whitespace around operator
927 | 1: ./airnow2ioda-nc.py:145:45: E231 missing whitespace after ','
928 | 1: ./airnow2ioda-nc.py:146:2: E111 indentation is not a multiple of four
929 | 1: ./airnow2ioda-nc.py:146:23: E225 missing whitespace around operator
930 | 1: ./airnow2ioda-nc.py:147:2: E111 indentation is not a multiple of four
931 | 1: ./airnow2ioda-nc.py:147:24: E225 missing whitespace around operator
932 | 1: ./airnow2ioda-nc.py:148:2: E111 indentation is not a multiple of four
933 | 1: ./airnow2ioda-nc.py:148:21: E225 missing whitespace around operator
934 | 1: ./airnow2ioda-nc.py:148:37: E231 missing whitespace after ','
935 | 1: ./airnow2ioda-nc.py:149:2: E111 indentation is not a multiple of four
936 | 1: ./airnow2ioda-nc.py:149:32: E225 missing whitespace around operator
937 | 1: ./airnow2ioda-nc.py:149:48: E231 missing whitespace after ','
938 | 1: ./airnow2ioda-nc.py:150:1: W293 blank line contains whitespace
939 | 1: ./airnow2ioda-nc.py:151:2: E111 indentation is not a multiple of four
940 | 1: ./airnow2ioda-nc.py:151:3: E225 missing whitespace around operator
941 | 1: ./airnow2ioda-nc.py:151:20: E231 missing whitespace after ','
942 | 1: ./airnow2ioda-nc.py:152:2: E111 indentation is not a multiple of four
943 | 1: ./airnow2ioda-nc.py:152:6: E225 missing whitespace around operator
944 | 1: ./airnow2ioda-nc.py:153:2: E111 indentation is not a multiple of four
945 | 1: ./airnow2ioda-nc.py:153:25: E225 missing whitespace around operator
946 | 1: ./airnow2ioda-nc.py:153:47: E231 missing whitespace after ','
947 | 1: ./airnow2ioda-nc.py:154:1: W293 blank line contains whitespace
948 | 1: ./airnow2ioda-nc.py:155:2: E111 indentation is not a multiple of four
949 | 1: ./airnow2ioda-nc.py:155:40: E225 missing whitespace around operator
950 | 1: ./airnow2ioda-nc.py:156:2: E111 indentation is not a multiple of four
951 | 1: ./airnow2ioda-nc.py:156:34: E225 missing whitespace around operator
952 | 1: ./airnow2ioda-nc.py:157:2: E111 indentation is not a multiple of four
953 | 1: ./airnow2ioda-nc.py:157:22: E231 missing whitespace after ','
954 | 1: ./airnow2ioda-nc.py:158:3: E111 indentation is not a multiple of four
955 | 1: ./airnow2ioda-nc.py:158:32: E225 missing whitespace around operator
956 | 1: ./airnow2ioda-nc.py:158:48: E231 missing whitespace after ','
957 | 1: ./airnow2ioda-nc.py:159:3: E111 indentation is not a multiple of four
958 | 1: ./airnow2ioda-nc.py:159:31: E225 missing whitespace around operator
959 | 1: ./airnow2ioda-nc.py:159:47: E231 missing whitespace after ','
960 | 1: ./airnow2ioda-nc.py:160:1: W293 blank line contains whitespace
961 | 1: ./airnow2ioda-nc.py:161:2: E111 indentation is not a multiple of four
962 | 1: ./airnow2ioda-nc.py:161:15: E225 missing whitespace around operator
963 | 1: ./airnow2ioda-nc.py:162:2: E111 indentation is not a multiple of four
964 | 1: ./airnow2ioda-nc.py:162:15: E225 missing whitespace around operator
965 | 1: ./airnow2ioda-nc.py:162:21: W291 trailing whitespace
966 | 1: ./airnow2ioda-nc.py:163:2: E111 indentation is not a multiple of four
967 | 1: checking ./tropomi_no2_nc2ioda.py
968 | 1: checking ./viirs_aod2ioda.py
969 | 1: 57      E111 indentation is not a multiple of four
970 | 1: 1       E117 over-indented
971 | 1: 1       E121 continuation line under-indented for hanging indent
972 | 1: 4       E126 continuation line over-indented for hanging indent
973 | 1: 6       E127 continuation line over-indented for visual indent
974 | 1: 2       E128 continuation line under-indented for visual indent
975 | 1: 3       E201 whitespace after '{'
976 | 1: 25      E225 missing whitespace around operator
977 | 1: 25      E231 missing whitespace after ','
978 | 1: 4       E302 expected 2 blank lines, found 1
979 | 1: 1       E305 expected 2 blank lines after class or function definition, found 1
980 | 1: 1       W291 trailing whitespace
981 | 1: 11      W293 blank line contains whitespace
982 | 1/1 Test #1: iodaconv_chem_coding_norms .......***Failed    0.11 sec
983 |  
984 | 0% tests passed, 1 tests failed out of 1
985 |  
986 | Label Time Summary:
987 | iodaconv    =   0.11 sec*proc (1 test)
988 | script      =   0.11 sec*proc (1 test)
989 |  
990 | Total Test time (real) =   0.11 sec
991 |  
992 | The following tests FAILED:
993 | 1 - iodaconv_chem_coding_norms (Failed)
994 | Errors while running CTest
```

Once these are fixed, the PR can be merged.

Thanks!

**Comment by ytangnoaa** [comment]
Stephen
Thank you for this information. I did not notice the style requirement.
I just updated my branch for that fix. Please try and let me know if there
is any issue.

Youhua

**Comment by srherbener** [comment]
@ytangnoaa thanks for fixing the coding norms errors.

**Pull request merged**
