### PR TITLE
Bugfix/omi ompsnm converter get files correctly at beginning of window

### PR DESCRIPTION
**Pull request by karpob**
## Description

This fixes a problem with not grabbing raw files at the start of the window. 

What problem does it fix? What new capability does it add?
When I wrote the script to grab files within the window, I mistakenly used the last date/time in the filename as the end date/time of the data, when in fact it is just the processing time.  This now just uses the start time of each file to get files within the window.

## Dependencies
None

## Impact
None

### CODE REVIEW

**Review by CoryMartin-NOAA — APPROVED** [review]

**Review by jeromebarre — APPROVED** [review]
looks ok to me

**Comment by karpob** [comment]
Hmm. Not sure why the build checks fail. The CodeBuilds look clean, unless I'm missing something. Any ideas?

**Comment by CoryMartin-NOAA** [comment]
http://cdash.jcsda.org:8080/test/2786095

```
Test output

+ SRC_DIR=/jcsda/ioda-bundle/iodaconv/src/compo
+ PYCODESTYLE_CFG_PATH=/jcsda/ioda-bundle/iodaconv
+ cd /jcsda/ioda-bundle/iodaconv/src/compo
+ pycodestyle -v --config=/jcsda/ioda-bundle/iodaconv/.pycodestyle --filename=*.py,*.py.in .
cli configuration: /jcsda/ioda-bundle/iodaconv/.pycodestyle
directory .
checking ./aeronet_aaod2ioda.py
checking ./aeronet_aod2ioda.py
checking ./airnow2ioda-nc.py
checking ./mls_o3_nc2ioda.py
checking ./modis_aod2ioda.py
checking ./mopitt_co_nc2ioda.py
checking ./omi_o3_nc2ioda.py
./omi_o3_nc2ioda.py:331:15: E231 missing whitespace after ','
checking ./ompsnm_o3_nc2ioda.py
./ompsnm_o3_nc2ioda.py:251:15: E231 missing whitespace after ','
checking ./tropomi_no2_nc2ioda.py
checking ./viirs_aod2ioda.py
checking ./viirs_biaswriter.py
2       E231 missing whitespace after ','
```

**Comment by karpob** [comment]
Whoops, thanks!

**Pull request merged**
