### PR TITLE
update name of radiosonde output from sonde

### LINKED ISSUE #1416: ncar bufr2ioda converter radiosonde name update
## Description
when breaking out the observation types in the prepBUFR file the name `sonde` is a bit ambiguous and `radiosonde` is more descriptive of the instrument

### PR DESCRIPTION
**Pull request by BenjaminRuston**
## Description

the output of the NCAR to IODA converter for prepBUFR uses the name `sonde` update to `radiosonde`

enables:
https://github.com/JCSDA-internal/skylab/pull/214
https://github.com/JCSDA-internal/ewok/pull/854

## Issue(s) addressed

Resolves #1416 

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by ashley314 — APPROVED** [review]
Thanks Ben, I tested it on the RND cluster with no issues. I have PRs in to update the observation ingest suite based on these new names.

**Review by fcvdb — APPROVED** [review]
Thanks Ben!

**Comment by BenjaminRuston** [comment]
ok @PatNichols and @fcvdb that fixed it so this is ready now after we decide what to do regarding the NCEP BUFRlib fix....

**Review by smaticka — APPROVED** [review]
This worked for me in conjunction with the `ewok` and `skylab` ingest PRs. 

Thanks @BenjaminRuston !

**Pull request merged**
