### PR TITLE
Add capability for CO in TROPOMI NO2 converter

### LINKED ISSUE #987: Create converter for TROPOMI CO
Create converter for TROPOMI CO
Using template from TROPOMI NO2:
https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/compo/tropomi_no2_nc2ioda.py
getting data at:
https://s5phub.copernicus.eu/dhus/#/home or eumetsat

### PR DESCRIPTION
**Pull request by weiwilliam**
## Description
This PR introduces the code for CO into the existing NO2 converter for TROPOMI.

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #987 

## Dependencies
Waiting on the following PRs:
- [ ] waiting on JCSDA/ufo/pull/2508

### CODE REVIEW

**Comment by jeromebarre** [comment]
`iodaconv_compo_coding_norms` is failing. You might have few spaces or commas that are no fitting in the coding norms. Just run that test and see what the output says then correct accordingly.

**Comment by jeromebarre** [comment]
Other than that the code looks good to me. Good job. Ready ton approve whenever you have fixed the coding norms!

**Review by jeromebarre — COMMENTED** [review]
see my comments above.

**Comment by weiwilliam** [comment]
@jeromebarre Thank you, I've made the modification. It passed the coding norms test.

**Comment by weiwilliam** [comment]
Let me see what happened. It should not have any changes.

**Comment by jeromebarre** [comment]
> DIFFER : VALUES OF GLOBAL ATTRIBUTE : converter : "tropomi_no2_co_nc2ioda.py" <> "tropomi_no2_nc2ioda.py" Does it mean I should update testoutput for no2 with using tropomi_no2_co_nc2ioda.py?

yes the output files probably have the info from the converter name. just update that and you'll be fine

**Review by srherbener — APPROVED** [review]
Changes look good. Thanks for doing this update!

**Review by jeromebarre — APPROVED** [review]
looks good now. this can be merged

**Comment by jeromebarre** [comment]
I am adding those additional PR that needs to be merged jointly with this one:
https://github.com/JCSDA-internal/ufo-data/pull/265
https://github.com/JCSDA-internal/ufo/pull/2508

**Comment by BenjaminRuston** [comment]
@srherbener updated the branch will watch for the tests to complete.  The adherence to new ioda conventions by 17Jan2023 will be undertaken by your team correct @jeromebarre

**Pull request merged**
