### PR TITLE
update README file for the land converters

### LINKED ISSUE #1520: land converter README markdown update
## Description

the current README in the land converter directory should be removed (and it is out of date anyway)

should be removed:
https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/land/README.md

rather the updated converters instructions should be updated here:
https://github.com/JCSDA-internal/ioda-converters/blob/develop/README.md

## Requirements

a selection of working converters for land

## Acceptance Criteria (Definition of Done)
a clear README explaining converters in the directory and how to call them

### PR DESCRIPTION
**Pull request by BenjaminRuston**
## Description

Make some updates to the README for the land converters

## Issue(s) addressed

Resolves #1520 

## Impact

An up to date README markdown

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by BenjaminRuston** [comment]
@YoulongXia-NOAA please feel free to go ahead and push to my branch and we'll clean these up

remove any that you don't recommend or support anymore if you think that's best (I think it wouldn't be a terrible idea)

**Comment by YoulongXia-NOAA** [comment]
@BenjaminRuston, now smap NRT and smap 9km ioda converters have been combined into a single converter, the README.md also need to make the corresponding modifications. Additionally, imsfv3 snow depth ioda converter is not included in this README.md file, it also needs to be included.  This is what I suggested. Furthermore, as you removed owp snow depth ioda converter from land sub-directory, it also needs to be added into this README.md file.

**Comment by BenjaminRuston** [comment]
@YoulongXia-NOAA please make whatever changes you see fit, and push to this branch

i could take a swing at it, would be comfortable with you taking the lead

**Comment by BenjaminRuston** [comment]
excellent, thanks @YoulongXia-NOAA, please either ask me for additional input .

or once you believe it's ready, just select *Ready for review* and take this out of draft mode and we'll get this reviewed and into the repository

**Comment by YoulongXia-NOAA** [comment]
@BenjaminRuston, please take a look and see if you need to modify it/put the additional input. After that, we can ask @ClaraDraper-NOAA  to take a look and work together with you and I to finish it. Thank you.

**Comment by BenjaminRuston** [comment]
@YoulongXia-NOAA and @ClaraDraper-NOAA this looks fine to me

and note @YoulongXia-NOAA you can approve this as it is my PR, so please do so if you feel it is ready and we'll update this file

**Review by YoulongXia-NOAA — APPROVED** [review]
Look good to me.

**Review by fcvdb — APPROVED** [review]
Thanks Ben!

**Pull request merged**
