### PR TITLE
update containers

### PR DESCRIPTION
**Pull request by mer-a-o**
## Description

This PR removes building fckit and atlas from CI. They are now available in the containers. CI/CMakeLists.txt is updated in this PR to be compatible with ecbuild 3.5 requirements.

### Issue(s) addressed

- partly https://github.com/JCSDA-internal/ufo/issues/1209

## Acceptance Criteria (Definition of Done)
All test pass in the new containers

## Dependencies
None

## Impact
None

## Test Data
None

### CODE REVIEW

**Review by mmiesch — APPROVED** [review]
Thanks @mer-a-o!

**Review by srherbener — COMMENTED** [review]
Are the python bindings being enabled for the ioda repo? I don't see the `-DBUILD_PYTHON_BINDINGS=ON ` control anywhere. Or is the addition of the python bindings being done in a subsequent PR? Thanks!

**Comment by srherbener** [comment]
Only for ioda.

This enables the ioda-engines Python API which the converters will eventually use.

Thanks!

**Comment by mer-a-o** [comment]
@srherbener Yes, I will turn it on for ioda. I'm working on a PR now.

**Review by srherbener — APPROVED** [review]
I'm good with the python bindings being enabled in a subsequent PR.

**Comment by srherbener** [comment]
@mer-a-o should I merge this now? Did you mean that a new PR is coming for ioda-converters to enable the python bindings? thanks!

**Comment by mer-a-o** [comment]
Sorry @srherbener, I think I misunderstood you. So we want to have `ecbuild -DBUILD_PYTHON_BINDINGS=ON` in both ioda and ioda-converters CI? or just ioda CI?

**Comment by mmiesch** [comment]
> I'm good with the python bindings being enabled in a subsequent PR.

It should be in this PR, shouldn't it - or the CI is not going to work.  I believe that option is only needed when building ioda.

**Comment by srherbener** [comment]
@mer-a-o, @mmiesch, sorry my initial response was confusing (trying to do too many things at once).

Eventually the python bindings need to be enabled for both ioda and ioda-converters CI testing. 

For ioda-converters: Cory M has a feature branch in ioda-converters that uses the ioda python bindings so we technically are okay now without that, but we need it soon to be checking Cory's work when he creates a PR. 

For ioda: The ioda-engines Python API is gaining traction and it should always be tested now, both for coverage and for making sure we don't break it. 

I think the best way forward is to:
* Merge this PR now
* Issue two new PRs, one for ioda-converters the other for ioda, to enable the ioda python bindings

Does that sound okay with you?

Thanks

**Comment by mer-a-o** [comment]
@srherbener I added python binding to this PR. I have a similar PR in ioda repo as well: https://github.com/JCSDA-internal/ioda/pull/285

**Comment by srherbener** [comment]
> @srherbener I added python binding to this PR. I have a similar PR in ioda repo as well: [JCSDA-internal/ioda#285](https://github.com/JCSDA-internal/ioda/pull/285)

Yes, I see it now (sorry I missed it before). I'll merge now. Thanks for you help @mer-a-o in getting this enabled!

**Pull request merged**
