### PR TITLE
Feature/avk vertcoord

### LINKED ISSUE #709: TROPOMI NO2 converter vertical coordinate
## Description
This issue is linked to the UFO issue https://github.com/JCSDA-internal/ufo/issues/1687

The tm5 like hybrid sigma coordinate using surface pressure to recalculate the pressure levels is TropOMI/OMI NO2 specific.
Most of the other trace gas L2 products provide a pressure/altitude grid per pixel or a fixed grid.
Ideally, we would want the ioda-converters to provide a coordinate grid that has the same dimensions as the averaging kernel array: (nloc,nlev).

We might feed redundant information to ufo but this would keep the ufo operator clean.
Alternatively, we would have to add cases in ufo for each L2 product vertical coordinate flavor ... this might become problematic as different instruments will be integrated.

Other types of vertical coordinate conventions for trace gas could be envisioned. Suggestions welcome

## Requirements
agree on a vertical coordinate convention for the averaging kernel operator

## Acceptance Criteria (Definition of Done)
Modify
https://github.com/JCSDA-internal/ioda-converters/blob/develop/src/chem/tropomi_no2_nc2ioda.py 
to provide a calculated vertical pressure grid to feed UFO

## Dependencies
https://github.com/JCSDA-internal/ufo/issues/1687

### PR DESCRIPTION
**Pull request by jeromebarre**
## Description

This an update of the ioda-converter for tropomi no2 and for future ioda converter using the averaging kernel formulation.
This is the PR form the issue 
https://github.com/JCSDA-internal/ioda-converters/issues/709
"The tm5 like hybrid sigma coordinate using surface pressure to recalculate the pressure levels is TropOMI/OMI NO2 specific.
Most of the other trace gas L2 products provide a pressure/altitude grid per pixel or a fixed grid."
This PR is solving this.

### Issue(s) addressed
https://github.com/JCSDA-internal/ioda-converters/issues/709

Link the issues to be closed with this PR
- fixes #709

## Dependencies

This PR needs to be merged jointly with:

https://github.com/JCSDA-internal/ufo/pull/1753
https://github.com/JCSDA-internal/ufo-data/pull/110

## Impact

ufo
ufo-data
fv3-jedi
fv3-jedi-data

### CODE REVIEW

**Comment by srherbener** [comment]
CI test failures are the following coding norms errors:

```
+ SRC_DIR=/jcsda/ioda-bundle/iodaconv/src/chem
+ PYCODESTYLE_CFG_PATH=/jcsda/ioda-bundle/iodaconv
+ cd /jcsda/ioda-bundle/iodaconv/src/chem
+ pycodestyle -v --config=/jcsda/ioda-bundle/iodaconv/.pycodestyle --filename=*.py,*.py.in .
cli configuration: /jcsda/ioda-bundle/iodaconv/.pycodestyle
directory .
checking ./aeronet_aaod2ioda.py
checking ./aeronet_aod2ioda.py
checking ./airnow2ioda-nc.py
checking ./modis_aod2ioda.py
checking ./tropomi_no2_nc2ioda.py
./tropomi_no2_nc2ioda.py:18:59: W291 trailing whitespace
./tropomi_no2_nc2ioda.py:103:61: W291 trailing whitespace
./tropomi_no2_nc2ioda.py:106:13: E265 block comment should start with '# '
./tropomi_no2_nc2ioda.py:107:69: E231 missing whitespace after ','
./tropomi_no2_nc2ioda.py:108:69: E231 missing whitespace after ','
./tropomi_no2_nc2ioda.py:109:40: W291 trailing whitespace
./tropomi_no2_nc2ioda.py:151:63: E128 continuation line under-indented for visual indent
./tropomi_no2_nc2ioda.py:154:48: E128 continuation line under-indented for visual indent
checking ./viirs_aod2ioda.py
2       E128 continuation line under-indented for visual indent
2       E231 missing whitespace after ','
1       E265 block comment should start with '# '
3       W291 trailing whitespace
```

**Review by srherbener — APPROVED** [review]
Looks good. Thanks for the updates.

**Review by CoryMartin-NOAA — APPROVED** [review]
Approved contingent on minor updates to pass coding norms tests

**Comment by jeromebarre** [comment]
I'll fix the coding norms later today.

**Comment by jeromebarre** [comment]
@mer-a-o

**Comment by jeromebarre** [comment]
@srherbener I think I fixed the coding norms now.

**Pull request merged**
