### PR TITLE
New BUFR tables for each subset of the ADPUPA data 

### PR DESCRIPTION
**Pull request by PraveenKumar-NOAA**
## Description

New six BUFR tables for each subset of the ADPUPA data for bufr2ioda conversion.

## Acceptance Criteria (Definition of Done)

People can have access of these tables and find important Mnemonics informations. 

## Dependencies

There is no dependencies. 

## Impact

No impact

## Test Data

No test data

### CODE REVIEW

**Review by srherbener — APPROVED** [review]
Thanks for adding these tables.

**Comment by jamiebresch** [comment]
Just curious - how are these tables generated?
There are existing NC002 tables as in https://www.nco.ncep.noaa.gov/pmb/codes/nwprod/decoders/decod_shared/fix_v5.7.0/bufrtab.002, why is it necessary to have separate subset tables?

**Comment by gthompsnJCSDA** [comment]
Praveen and Jamie, would you like to have a joint telecon together to discuss all this?  In my bufr2ioda work, I have now compiled quite a large total list of individual tables to document a lot of data forms, starting from WMO BUFR and I think we should just come up with a unified convention for where to find all this stuff.  I am also planning to work all week on this topic for the data types that do not have "delayed sequences" that are not yet supported by Ron McLaren's code since ncep-bufr-libs is problematic for these types of BUFR messages.

**Comment by PraveenKumar-NOAA** [comment]
Jamie: these tables contain very specific mnemonics used for only one obs-type, like rawinsonde, rather than grouping all ADPUPA into a single table. When we run bufr2ioda.x, at some point, we are likely to have one stream of incoming data type (rawinsonde for example, separated from adpupa obs) and using a yaml meant only for rawinsonde data.

**Review by emilyhcliu — APPROVED** [review]

**Pull request merged**
