### PR TITLE
Feature/modis aod from h4

### PR DESCRIPTION
**Pull request by jeromebarre**
Update the MODIS IODA converter to take the native h4 files as input!

No need to pre-convert the files to a netcdf format beforehand anymore...

It seems that packages have now been installed see: https://github.com/NOAA-EMC/spack-stack/issues/129 and https://github.com/NOAA-EMC/spack-stack/pull/131

people tagged:
@mer-a-o, @christophkeller, @vbuchard, @srherbener, @rhoneyager

### CODE REVIEW

**Comment by jeromebarre** [comment]
I believe the test is failing because the containers have not been updated. Do we know when we expect to have this updated? @climbfuji

**Comment by jeromebarre** [comment]
@CoryMartin-NOAA and @andytangborn this now ready for review.

**Review by CoryMartin-NOAA — APPROVED** [review]
Looks good to me, thanks!

**Review by srherbener — APPROVED** [review]
Looks good. Thanks for this upgrade.

**Pull request merged**
