### PR TITLE
gmao converter update

### PR DESCRIPTION
**Pull request by Dooruk**
## Description

- Updated gmao_obs2ioda.py file to work with the iODA v2 convention.

- Created two tests (salinity and temperature) to process & validate the conversions.

- Input/output files added:

1. testinput/gmao_tao.nc
2. testoutput/gmao_sal.nc
3. testoutput/gmao_temp.nc

### CODE REVIEW

**Review by danholdaway — APPROVED** [review]
Thank for adding this @Dooruk

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Comment by BenjaminRuston** [comment]
@Dooruk this looks like a case of `take ours` for all the conflicts, but can you advise?

**Review by travissluka — CHANGES_REQUESTED** [review]
The latest develop after today's PRs needs to be merged in and resolved. Double check that the variable names follow the new conventions (e.g. should be `waterTemperature` not `sea_water_tenperature`)

**Comment by Dooruk** [comment]
I wasn't aware that someone else was updating the gmao converter code, so this PR is not necessary anymore.

**Pull request closed without merging**
