### PR TITLE
Ctest for the existing bufr_ncep_adpupa.yaml

### LINKED ISSUE #1183: Add ctest for the adpupa bufr and prepbufr
## Description

- The adpupa bufr and prepbufr YAMLs are in the develop branch of the ioda-converters. The purpose of this issue is to add the ctest for both of these YAMLs. A ctest, _test_iodaconv_bufr_adpupa_ is already in _CMakeLists.txt_ for the prepbufr that also needs to be updated/fixed for these latest YAMLs. 

## Requirements

- None

## Acceptance Criteria (Definition of Done)

- Ctests for both bufr and prepbufr need to be passed.

## Dependencies

- None

### PR DESCRIPTION
**Pull request by PraveenKumar-NOAA**
## Description
There was no ctest in ioda-converets for the existing ADPUPA BUFR YAML, bufr_ncep_adpupa.yaml. This PR adds a new ctest, test_iodaconv_bufr_ncep_adpupa2ioda, for this YAML. 

### Issue(s) addressed
- fixes #1183 

## Acceptance Criteria (Definition of Done)
The ctest should pass.

## Dependencies
merge #1174  first

## Impact
None

### CODE REVIEW

**Review by nicholasesposito — APPROVED** [review]

**Comment by PatNichols** [comment]
@PraveenKumar-NOAA Does this reference files from your previous PR?

**Comment by BenjaminRuston** [comment]
@PraveenKumar-NOAA merged in the PR1174 and now conflict here. will let you resolve if that's OK

**Review by PatNichols — APPROVED** [review]
thanks for this!

**Comment by PraveenKumar-NOAA** [comment]
@BenjaminRuston please also look at this one and merge.

**Comment by PatNichols** [comment]
@PraveenKumar-NOAA sorry this merge is taking so long. We are putting out fires in other repos

**Review by fcvdb — APPROVED** [review]
The `test_iodaconv_bufr_ncep_adpupa2ioda `passes. Thanks.

**Pull request merged**
