### PR TITLE
feature/gliderAOML

### PR DESCRIPTION
**Pull request by lliu1220**
### Description

Hurricane gliders by AOML provides valuable high vertical resolution information to weather forecast which benefit numerical modeling of vertical mixing, stratification as well as water transport  during extreme weather events. In order for Hurricane gliders to be assimilated and benefit the system, a converter for the system to ingest is required at first place.

### Issue(s) addressed
Merged T/S converter into one: https://github.com/JCSDA-internal/ioda-converters/pull/341
Fixed coding norm and merging conflicts: https://github.com/JCSDA-internal/ioda-converters/pull/360

### Dependencies
Addressed how to assimilate glider: https://github.com/JCSDA-internal/soca-science/issues/83

### Impact
Assimilating hurricane glider benefits hurricane research including hurricane track and intensity study

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
> this is to address an old branch feature/marineglider , old draft PR #360
> since that branch was a month behind, it'd be wise to create a new one, any other ways?

That's fine, but adding a proper short description of what your work does would be nice ...

**Review by guillaumevernieres — COMMENTED** [review]
- Output looks OK
- You still have a few debug print statement to get rid off
- It's not finding `ioda_conv_ncio` when testing in singularity.
Could you replace 
```python
sys.path.append("@SCRIPT_LIB_PATH@")
```
by 
```python
from pathlib import Path
+
+IODA_CONV_PATH = Path(__file__).parent/"@SCRIPT_LIB_PATH@"
+if not IODA_CONV_PATH.is_dir():
+    IODA_CONV_PATH = Path(__file__).parent/'..'/'lib-python'
+sys.path.append(str(IODA_CONV_PATH.resolve()))
```
(copy/pasted from an other converter ...)

**Comment by lliu1220** [comment]
Done.

**Review by guillaumevernieres — APPROVED** [review]
:+1: Thanks for that work.

**Review by jkbk2004 — APPROVED** [review]

**Comment by lliu1220** [comment]
@srherbener 
Hi, Stephen,
Now I have two approval for this PR, would you please take a look at it when you get a chance? Thank you! appreciate it.
Ling

**Review by travissluka — APPROVED** [review]
:+1:
@lliu1220  FYI the JEDI team is doing a JEDI academy this week, so I wouldn't expect many PRs to get merged until after that

**Review by srherbener — APPROVED** [review]
Looks great! Thank you for merging the scripts into one script.

**Comment by lliu1220** [comment]
@srherbener 
Steven, I think you might have deleted the wrong branch, feature/gliderAOML is the one that's approved and ought to be merged , feature/marineglider is supposed to be deleted.
Thank you,
Ling

**Comment by lliu1220** [comment]
@srherbener sorry my bad just realized branch ought to be deleted after merging into develop

**Comment by srherbener** [comment]
@lliu1220 no problem. Can the feature/marineglider branch be deleted? If so, please delete. Thanks!

**Pull request merged**
