### PR TITLE
changes for L2 trace gas varnames to follow conventions

### PR DESCRIPTION
**Pull request by jeromebarre**
changes for L2 trace gas varnames to follow conventions

### CODE REVIEW

**Review by mer-a-o — APPROVED** [review]

**Review by srherbener — COMMENTED** [review]
Changes look good. The tropomi tests are still commented out, ie not running. Is that what we want, or should we uncomment and enable the tests? Thanks!

**Comment by jeromebarre** [comment]
@srherbener I just uncommented the tests now. They are working fine.

**Comment by srherbener** [comment]
@jeromebarre I created feature/sprint-ioda-converters-jerome2 branches (based on feature/sprint-ioda-converters) for both ioda and ioda-data repos. The ctests were failing because these branches did not exist and develop was selected for both ioda and ioda-data. ctest results this time should look much better.

**Review by srherbener — APPROVED** [review]
Thanks for uncommenting the tropomi tests.

**Pull request merged**
