### PR TITLE
Ioda-converters YAML for the [3D]-RTMA aircar data

### LINKED ISSUE #1391: Example YAMLs for the [3D]-RTMA AIRCAR data
## Description
The purpose of this issue is to:
Write an example YAML that can convert the [3D]-RTMA AIRCAR BUFR file into the IODA format for the following subsets:

NC004004 --- MTYP 004-004 Automated MDCRS (ARINC to NCEP) (BUFR)
NC004007 --- MTYP 004-007 Auto MDCRS (ARINC to AFWA to NCEP) (AIREP

- Global AIRCAR YAML will be used as a reference
- Use this YAML to convert into an IODA-formatted netCDF file
- Add output to the ioda-converter testoutput directory
- Add tests to the CMakeLists.txt files
- Have the tests pass

## Requirements
All important mnemonics need to be known.

## Acceptance Criteria (Definition of Done)
It will be finished when all files have been checked and tests have passed.

## Dependencies
The bufr2ioda.x

### PR DESCRIPTION
**Pull request by PraveenKumar-NOAA**
## Description
This PR adds an ioda-converters YAML for the [3D]-RTMA AIRCAR data. 

The following files are new/ modified: 

- testinput/bufr_ncep_rtma_aircar.yaml
- testinput/rtma_ru.t0000z.aircar_NC004004.tm00.bufr_d
- testoutput/rtma_ru.t0000z.aircar_NC004004.tm00.nc
- CMakeLists.txt

The ioda-validation test is performed and following results were obtained: 

**Final results:**
_errors:      0
warnings:    0_

The validation of the output ioda obs is also performed in: #1373 

## Issue(s) addressed
Resolves #1391 

## Dependencies
None

## Impact
None

## Checklist
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by nicholasesposito — APPROVED** [review]
Looks good

**Comment by MatthewMorris-NOAA** [comment]
@PraveenKumar-NOAA This looks good to me, but I'm curious about the 3 failed checks. Is this a cause for concern?

**Comment by PraveenKumar-NOAA** [comment]
> @PraveenKumar-NOAA This looks good to me, but I'm curious about the 3 failed checks. Is this a cause for concern?

@MatthewMorris-NOAA I don't think, let us see what @PatNichols says about it.

**Comment by PatNichols** [comment]
@PraveenKumar-NOAA The one failed test is directly related to this PR.
The error message is:
ERROR /tmp/root/spack-stage/spack-stage-nccmp-1.9.0.1-br2cpqht43dbgly2cax2zzc3ee2z7tow/spack-src/src/nccmp_state.c:163 File not found: testoutput/rtma_ru.t0000z.aircar_NC004004.tm00.nc

**Comment by PatNichols** [comment]
@PraveenKumar-NOAA It looks like you never added your output file to the CMakeLists.txt file.

**Review by PatNichols — APPROVED** [review]

**Review by MatthewMorris-NOAA — APPROVED** [review]

**Pull request merged**
