### PR TITLE
Feature/query dim naming bug

### PR DESCRIPTION
**Pull request by rmclaren**
## Description

Current iteration of query feature doesn't check whether named dimensions have generic path strings (start with *). This bug fix makes sure to throw an exception when this criteria is not met.

### Issue(s) addressed

#1020 
#1031 

## Acceptance Criteria (Definition of Done)

named dimensions with non-generic paths (don't start with *) will throw an exception.

## Prerequisite

#1006

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
Is this the right base branch? 155 commits seems like a lot...

**Comment by rmclaren** [comment]
So this branch is based on feature/query_cxx which has not been merged into develop (that PR as listed as a prerequisite). @srherbener was concerned that query_cxx kept drifting with these incremental bug fixes, so I thought it would be better to have this as a seperate PR which can be applied after query_cxx is merged. Please let me know if there is a better way to do this.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by srherbener** [comment]
Basing this PR on `feature/query_cxx` is what I was intending. The request I made was to not merge this PR into `feature/query_cxx` and instead wait until after `feature/query_cxx` has been merged into develop. When that happens, github will automatically change the base branch to `develop`.

**Review by srherbener — APPROVED** [review]

**Review by emilyhcliu — APPROVED** [review]
Looks good to me.

**Pull request merged**
