### PR TITLE
Add converter for SatWinds WMO-formatted BUFR for INSAT and Aqua/Terra

### PR DESCRIPTION
**Pull request by gthompsnJCSDA**
## Description

This PR adds in the capability to run bufr2ioda.x on the WMO-formatted BUFR files that contain either INSAT (India) or the MODIS Aqua/Terra satellite atmospheric motion vectors (AMVs).  The sample input BUFR file contains only INSAT data, but the same yaml was used for a MODIS-only file and works equivalently.  There are only minor differences in the variable list between the 2 different data sets.  This PR includes doc/bufr_table_samples (and obs_samples) with the mnemonics used for the variables.

### Issue(s) addressed

A separate issue was not created for this.

## Acceptance Criteria (Definition of Done)

Working ctest and reviews.

## Dependencies

There are no dependencies.

## Impact

No impacts to other repos expected.

### CODE REVIEW

**Review by nicholasesposito — COMMENTED** [review]
Should it be "Metadata" (no capital D) in the yamls? Does it matter?
Looks good otherwise.

**Comment by PraveenKumar-NOAA** [comment]
Looks good to me.

**Comment by nicholasesposito** [comment]
> > Should it be "Metadata" (no capital D) in the yamls? Does it matter? Looks good otherwise.
> 
> It does actually matter coming up soon with Ryan's validator program. We did have a mixture of the two in our earlier document but decided for sure that we want `MetaData` because that is already in our files and path of least resistance is to keep it that way.

OK, sounds good to me. Thanks

**Review by nicholasesposito — APPROVED** [review]

**Review by srherbener — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
