### PR TITLE
Feature/ompslp

### PR DESCRIPTION
**Pull request by LouisKouvaris-NOAA**
## Description

Added mixing_ratio_ozone_in_air in gsi_ncdiag.py  to accommodate OMPS LP instrument

## Dependencies

None
Waiting on the following PRs:
None
## Impact
Add OMPS LP funcyionality

Requires changes in the following repositories:
- [ ] saber
- [ ] ioda
- [ ] ufo
- [ ] ...

### CODE REVIEW

**Comment by karpob** [comment]
I need to review this more carefully but one thing right off the bat is 'absorber 03' needs to be mole fraction of ozone in air, not mass fraction.

**Comment by karpob** [comment]
There are a few things that I think are going to be problem. The first is I don't understand why it's necessary to create a new name for something that already exists, and I think it's generally a bad idea to add a new name for the same quantity. 
```python 
        if(self.sensor == "ompslp"):
            vname = "mixing_ratio_ozone_in_air"
```
As far as I can tell this is the same as mole_fraction_of_ozone_in_air.

Second, I've never used these converters and don't have a handy way to test, but this line shouldn't be necessary as the only thing we're outputting for geovals would be mole fraction. 
```python
        if(self.sensor != 'ompslp'):
            ncout.createDimension("nlevs", self.df.dimensions["mass_concentration_of_ozone_in_air_arr_dim"].size)
        else:
            ncout.createDimension("nlevs", self.df.dimensions["mole_fraction_of_ozone_in_air_arr_dim"].size)
```

**Comment by srherbener** [comment]
@LouisKouvaris-NOAA please resolve the conflict `src/gsi-ncdiag/gsi_ncdiag.py`, then the others can review this PR. Thanks!

**Review by srherbener — APPROVED** [review]
@LouisKouvaris-NOAA, thank you for this update! I apologize for taking so long to get to this.

**Comment by srherbener** [comment]
@karpob, @emilyhcliu, @HaixiaLiu-NOAA, could at least one of you review this soon. It's been here for a long time. If you can't get to this soon, please recommend another reviewer. Thanks!

**Comment by HaixiaLiu-NOAA** [comment]
@srherbener in the process of discussing how to do this with @LouisKouvaris-NOAA. Will have an update soon.

**Comment by srherbener** [comment]
@HaixiaLiu-NOAA sounds good. Thanks for the update.

**Comment by HaixiaLiu-NOAA** [comment]
we have discussed it and @LouisKouvaris-NOAA will update this one and I will review after he makes modifications. Thanks for your patience, @srherbener

**Review by srherbener — APPROVED** [review]
Thought I should reset my review since there were a bunch of recent commits. The code changes look good to me still.

**Comment by srherbener** [comment]
I merged develop to get this up to date. Please review so we can get this merged in. If the current reviewers are not available, please request new reviewers. Thanks!

**Review by HaixiaLiu-NOAA — APPROVED** [review]
@srherbener thank you for the reminder. The changes look good to me. Approved.

**Comment by srherbener** [comment]
@HaixiaLiu-NOAA thanks for the review!

**Pull request merged**
