### PR TITLE
setting standards for c, c++ and fortran

### LINKED ISSUE #1288: Update to cxx-17 and set standard for C and fortran
## Description

All repos are updating the C++ to C++-17. This PR will update the standard and also set the C and fortran standards.

## Acceptance Criteria (Definition of Done)

Buidling and ctests pass.

## Dependencies

None

### PR DESCRIPTION
**Pull request by PatNichols**
## Description

This sets the standards for C, C++ and FORTRAN.
C++ is set to C++-17
C is set to C-17
FORTRAN is set to fortran-08

## Issue(s) addressed

Resolves #1288 

## Dependencies

None

## Impact

None

## Checklist

- [ x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ x] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by srherbener** [comment]
The intel build failure is reporting this error:
```
CMake Error in /build_container/CMakeFiles/CMakeTmp/CMakeLists.txt:
--
480 | Target "cmTC_2220c" requires the language dialect "C17" .  But the current
481 | compiler "Intel" does not support this, or CMake does not know the flags to
482 | enable it.
```

Which doesn't make sense because the Intel C compiler (icc --help) reports, on S4, that it does support `-std=c17`. Perhaps there is a bug in CMake?

**Comment by srherbener** [comment]
And I see the same failure on S4 as reported in the Intel CI test when I try to build jedi-bundle.

**Comment by PatNichols** [comment]
> The intel build failure is reporting this error:
> 
> ```
> CMake Error in /build_container/CMakeFiles/CMakeTmp/CMakeLists.txt:
> --
> 480 | Target "cmTC_2220c" requires the language dialect "C17" .  But the current
> 481 | compiler "Intel" does not support this, or CMake does not know the flags to
> 482 | enable it.
> ```
> 
> Which doesn't make sense because the Intel C compiler (icc --help) reports, on S4, that it does support `-std=c17`. Perhaps there is a bug in CMake?

@srherbener Yep... I checked the documentation and intel only supports up to C-11 which is crazy since they have support for c++-17.  I downgraded the version requested and I am hoping for the best. This is mainly an experiment  to see how this might play out in other repos which depend on each other.

**Comment by PatNichols** [comment]
This now sets the following standards
C-11
CXX-17
fortran-08

**Comment by rmclaren** [comment]
Having issues with the python API on my machine (GNU compiler). Will look at it more tomorrow.

**Comment by rmclaren** [comment]
Never mind, I think my issue is that all my libaries were compiled with c++ 11 still... So I'm using incompatible binaries.

**Review by srherbener — APPROVED** [review]
Looks great! Thanks for providing this model of how to specify the language standards. Hopefully, this pattern will work with the other repos.

**Review by fmahebert — APPROVED** [review]
Did not test, but looks good to me!

**Pull request merged**
