### PR TITLE
SPRINT:  update 3 marine converters to follow JEDI Data Conventions

### LINKED ISSUE #829: gmao_obs2ioda.py is never tested in ioda-converters
See title. This was noticed in our code sprint. The script should be tested somewhere, but it isn't. If it is dead code, then it should be removed.

### LINKED ISSUE #898: Upgrade marine converters for hgodas_adt2ioda and rads_adt2ioda to follow the JEDI Data Conventions
## Description

Upgrade the two marine converters (python) called ```hgodas_adt2ioda.py``` and ```rads_adt2ioda.py``` to follow the JEDI Data Conventions.

These codes were updated and partially rewritten to unify the code better with numerous other marine converters.  In the long run these codes should now be easier to maintain going forward.

### PR DESCRIPTION
**Pull request by gthompsnJCSDA**
## Description

This PR updates 3 marine converters to follow JEDI Data Conventions.  The list is

-   hgodas_adt2ioda.py
-   rads_adt2ioda.py
-   gmao_obs2ioda.py

In addition to changing some variable names, the structures of these scripts were unified in ways very similar to some of the other converters (godae* in particular).  The GMAO converter also included a new input file for a new ctest that was lacking previously (see one of the issue numbers below that this PR closes).

### Issue(s) addressed

- Closes #898 
- Closes #829 

## Acceptance Criteria (Definition of Done)

Working tests and reviews

## Dependencies

Waiting on the following PRs:
- [x] waiting on #895 
- [ ] waiting on JCSDA-internal/ioda/pull/685

## Impact

None if kept within ```feature/sprint-ioda-converters```

### CODE REVIEW

**Review by travissluka — APPROVED** [review]

**Comment by HamidehGMAO** [comment]
It seems the coding_norms tests are failing

**Comment by gthompsnJCSDA** [comment]
> It seems the coding_norms tests are failing

Thank you.  I believe I fixed these now.

**Comment by HamidehGMAO** [comment]
marine_code_norm looks fine now but it seems something is wrong with the other tests in AWS runs,
image

**Comment by gthompsnJCSDA** [comment]
@rhoneyager   I am struggling to understand how my test/testoutput files for this PR do not seem to be the correct one even though I have tried so many times to use the ones I copy from my testrun directory after exercising the codes.  Can you please help?  I have re-attempted git push of the files over and over again.

**Comment by gthompsnJCSDA** [comment]
There is a problem with the absoluteDynamicTopography variable coming in as all NaNF type in the netCDF file and I need to align that (I do not know how) to the netCDF missing float value.  So the GMAO data is failing the automated testing right now.

**Review by srherbener — APPROVED** [review]
Looks good. Thank you for all your hard work and diligence to get these converters completed!

**Comment by gthompsnJCSDA** [comment]
> Looks good. Thank you for all your hard work and diligence to get these converters completed!

Thanks Steve.  Looks like the tests all pass.  Is the "warning" caused by the print statement in the code upon completion?

**Comment by srherbener** [comment]
> > Looks good. Thank you for all your hard work and diligence to get these converters completed!
> 
> Thanks Steve. Looks like the tests all pass. Is the "warning" caused by the print statement in the code upon completion?

That warning looks more like an informational message indicating how many obs were pulled from the input file. I think it's okay to have that. I'll merge now.

**Pull request merged**
