### PR TITLE
Fixes testoutput files that have missing fields.

### PR DESCRIPTION
**Pull request by rmclaren**
## Description

I recent fix to the ioda library adds additional fields to the netcdf files that were previously missing (should have been there but were not). Unfortunately this broke our unit tests. This PR updates those testoutput files.

## Issues

#1269

### CODE REVIEW

**Comment by srherbener** [comment]
@rmclaren I noticed that some of the test failures are related to string types so the question I have is whether to merge the IODA PR with the str type fix: https://github.com/JCSDA-internal/ioda/pull/1019. Ie, do you need this merged to get this PR working, or do you instead need for me to hold off merging? Thanks!

**Comment by rmclaren** [comment]
@srherbener Unfortunately the "string fix" PR in IODA will need to be merged before all the unit tests will pass.

**Comment by srherbener** [comment]
> @srherbener Unfortunately the #1019 PR in IODA will need to be merged before all the unit tests will pass.

No problem. I'll do the merge now.

**Comment by srherbener** [comment]
https://github.com/JCSDA-internal/ioda-converters/issues/1019 is merged.

**Comment by rmclaren** [comment]
@srherbener Thanks Steve! Not all the tests will pass yet. There are some I've been having trouble running locally because of software configuration issues on my end...

**Comment by srherbener** [comment]
I think this is almost there! It looks like the ctest errors are all like this:
```
DIFFER : NUMBER OF GLOBAL ATTRIBUTES : 7 <> 6
DIFFER : NAME OF GLOBAL ATTRIBUTE : ioda_version : GLOBAL ATTRIBUTE DOESN'T EXIST IN "testoutput/amdar_wmo_multi2.nc"
```
where the only difference is the global attribute is missing from the test reference files.

**Comment by srherbener** [comment]
This PR will get develop back to passing so it's important to process this now. Thanks everyone!

**Review by srherbener — APPROVED** [review]
@rmclaren thanks for your effort to quickly get these fixes in!

**Comment by rmclaren** [comment]
@srherbener Thanks for fixing the remaining unit tests!

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
