### PR TITLE
BUGFIX: incoming SSEC AMV data has wrong convention for east/western hemispheres

### PR DESCRIPTION
**Pull request by gthompsnJCSDA**
## Description

The text data downloaded from SSEC uses positive longitudes for western hemisphere and negative longitudes for eastern hemisphere.  This PR fixes to world convention using a -1.0 multiplier for their longitudes.

### Issue(s) addressed

Rapid bug fix, a separate issue was not created.

## Acceptance Criteria (Definition of Done)

It will be nice to see the change on experiments.jcsda.org but this was discovered by looking at experiment id=`369c00` that clearly shows the error.

## Dependencies

None

## Impact

None

### CODE REVIEW

**Comment by PatNichols** [comment]
@BenjaminRuston  @gthompsnJCSDA does the lattitude needs to be flipped?

**Comment by gthompsnJCSDA** [comment]
> @BenjaminRuston @gthompsnJCSDA does the lattitude needs to be flipped?


It doesn't appear to be, no.  But I will know after another test file is run through a full experiment test - which we will know quickly.

**Comment by PatNichols** [comment]
@gthompsnJCSDA let me know when you think it is good to go

**Comment by gthompsnJCSDA** [comment]
> @gthompsnJCSDA let me know when you think it is good to go


Waiting on Ben to give approval

**Comment by BenjaminRuston** [comment]
image

**Review by BenjaminRuston — APPROVED** [review]
this worked for me for a 6-hour window

**Comment by gthompsnJCSDA** [comment]
> this worked for me for a 6-hour window

Ta-da!  Much better.  Why the heck is SSEC sending out data with reversed standard of longitude?

**Review by fabiolrdiniz — APPROVED** [review]
Thanks, @gthompsnJCSDA.

**Review by haydenlj — APPROVED** [review]

**Pull request merged**
