### PR TITLE
Fix reference to oz_sensors in proc_gsi_ncdiag

### LINKED ISSUE #1052: GSI ncdiag processing script no longer works
## Current behavior (describe the bug)
After #1043 , `proc_gsi_ncdiag.py` no longer works because it is looking for `oz_sensors`.
This needs to be added in `proc_gsi_ncdiag.py` the way it is added in `gsi_ncdiag.py`:
```
 oz_sensors = oz_lay_sensors + oz_lev_sensors
```

## To Reproduce

Run `proc_gsi_ncdiag.py` which I do not think is tested.

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
## Description
This PR fixes a reference to oz_sensors now that this has been replaced with two lists for layer and level sensors.

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #1052 

## Acceptance Criteria (Definition of Done)

What does it mean for this PR to be finished?
Reviewed

## Dependencies

None

## Impact

None

### CODE REVIEW

**Review by karpob — APPROVED** [review]
Sorry, should have caught this when I split it out!

**Review by srherbener — APPROVED** [review]

**Comment by BenjaminRuston** [comment]
@CoryMartin-NOAA ,, put the `ready for merge` label on this one. did you need to have another look at this?

**Comment by BenjaminRuston** [comment]
but note the message on the empty commit was incorrect -- doh!

**Comment by PatNichols** [comment]
Cory: This branch seems to be failing these tests with the intel compiler (only the intel compiler)
566 - test_iodaconv_tropomi_no2_tropo (Failed)
954 | 569 - test_iodaconv_aeronet_aod (Failed)

**Comment by srherbener** [comment]
> Cory: This branch seems to be failing these tests with the intel compiler (only the intel compiler) 566 - test_iodaconv_tropomi_no2_tropo (Failed) 954 | 569 - test_iodaconv_aeronet_aod (Failed)

I believe that these tests are also failing on develop. It's a tolerance issue with floating point number comparisons. Someone needs to create PRs to fix these. In the `test/CMakeLists.txt` file, there is a cmake variable that specifies a non-zero tolerance which can be used in the add_test command.

https://github.com/JCSDA-internal/ioda-converters/blob/eb59448e210db29e14ee8ea7cf79172440ff4922/test/CMakeLists.txt#L341

**Comment by PatNichols** [comment]
That seems weird. Why only failures on intel ?

**Comment by PatNichols** [comment]
PR 1066 should fix this issue. The tolerance_zero is set to 1.e-7 in the ctests though that was just a guess on my part. If y'all have a more precise number, I would welcome it.

**Pull request merged**
