### PR TITLE
Pass TotalBias argument to Ozone.toGeovals

### PR DESCRIPTION
**Pull request by danholdaway**
## Description

Our nightly picked up a bug in the Ozone converter code. TotalBias is an undefined variable.

### CODE REVIEW

**Review by BenjaminRuston — APPROVED** [review]
yes thought something like this may happen,,, thanks @danholdaway looks good

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by BenjaminRuston** [comment]
Wait,, think the correct approach is none of the `toGeovals` should have `TotalBias`

so we should remove this section:

```
                if (TotalBias):
                    # compute final bias correction
                    key1 = 'Obs_Minus_Forecast_adjusted'
                    key2 = 'Obs_Minus_Forecast_unadjusted'
                    if key1 in self.df.variables.keys() and key2 in self.df.variables.keys():
                        tmp = self.var(key1) - self.var(key2)
                        iodavar = 'GsiBc'
                        gvname = vname, iodavar
                        outdata[gvname] = np.reshape(tmp, dim)
                        VarDims[gvname] = dim_names
                    else:
                        print(f' ... can not add total bias missing {key1} or {key2} from input file')
```

**Comment by BenjaminRuston** [comment]
@danholdaway please put `ready to merge` if this fix works for you and we'll get it in

**Comment by danholdaway** [comment]
Thanks @BenjaminRuston. Removing it makes sense to me.

**Pull request merged**
