### PR TITLE
ioda converter for synthetic SWOT observations

### LINKED ISSUE #1014: Create converter for SWOT
find the existing synthetic SWOT observations, and create a ioda-converter for it.

### PR DESCRIPTION
**Pull request by kbhargava**
## Description

This converter reads in the synthetic SWOT observations, estimates the ADT and write them out in ioda format. 

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #1014 

## Acceptance Criteria (Definition of Done)
- output dataset looks reasonable
- passes all ctests

### CODE REVIEW

**Comment by ShastriPaturi** [comment]
ctest passes on orion.

**Review by ShastriPaturi — APPROVED** [review]
Looks Good.
Thanks

**Review by travissluka — CHANGES_REQUESTED** [review]
1. thin out the obs file with nco tools. 700,486 nlocs is a bit too much for a ioda converter ctest
2. I *think* what we want to do is `adt = ssha_karin + mean_sea_surface_cnescls - geoid`. The problem with `ssh_karin` is that it does not have tides removed, `ssha_karin` does. Someone (@guillaumevernieres ?) can check my logic on that one. I've included the descriptions of the relevant variables of input file.

```
ssh_karin:comment = "Fully corrected sea surface height measured by KaRIn. The height is relative to the reference ellipsoid defined in the global attributes. This value is computed using radiometer measurements for wet troposphere effects on the KaRIn measurement (e.g., rad_wet_tropo_cor and sea_state_bias_cor)." ;

ssha_karin:comment = "Sea surface height anomaly from the KaRIn measurement = ssh_karin - mean_sea_surface_cnescls - solid_earth_tide - ocean_tide_fes – internal_tide_hret - pole_tide - dac." ;

geoid:source = "EGM2008 (Pavlis et al., 2012)" ;
geoid:comment = "Geoid height above the reference ellipsoid with a correction to refer the value to the mean tide system, i.e. includes qthe permanent tide (zero frequency)." ;

mean_sea_surface_cnescls:comment = "Mean sea surface height above the reference ellipsoid. The value is referenced to the mean tide system, i.e. includes the permanent tide (zero frequency)." ;
```

**Comment by guillaumevernieres** [comment]
Yes, that's right @travissluka . You could also do adt = ssh_karin + MDT, which is what we currently use, but you would need to figure out how to reconcile the climatology used for ssha and mdt ...  Probably a good time to start picking at an expert's brain.

**Review by travissluka — APPROVED** [review]
seems right... I guess we'll find out when we try assimilating!

**Review by guillaumevernieres — APPROVED** [review]
:+1:

**Pull request merged**
