### PR TITLE
renaming test input and output files AMSR2 iodaconv ctest

### PR DESCRIPTION
**Pull request by smaticka**
## Description
renaming the input and output files for the ioda-converter ctest. 
The data is downsampling and this label includes the instrument, the date, and the `sample` label to indicate downsampling.

### CODE REVIEW

**Review by fcvdb — APPROVED** [review]
Thanks Sam!

**Comment by PatNichols** [comment]
@smaticka @fcvdb I changed the cmake for the test so the proper files are used for the ctest. Hopefully that fixes that.

**Review by BenjaminRuston — APPROVED** [review]
thanks @smaticka think it is nice to separate the naming of the input from the output just to make the difference that much more obvious!

**Comment by PatNichols** [comment]
@smaticka You added a cooridinate merge label. Which other PR is dependent on this one? I am a little confused here.

**Pull request merged**
