### PR TITLE
Bugfix/sensor scan position integer

### PR DESCRIPTION
**Pull request by gthompsnJCSDA**
## Description

Change all converters and various in/out files to force `sensorScanPosition` to be integer, which it really is, and not floating point.

## Issue(s) addressed

Discussed in [IODA issue 1037](https://github.com/JCSDA-internal/ioda/issues/1037) but this is actually not a problem in `ObsSpace.yaml` which already has the correct type as integer

## Dependencies

- [ioda-data PR 161](https://github.com/JCSDA-internal/ioda-data/pull/161)

Besides the direct dependency with `ioda-data` there are two corresponding PRs, one in `ufo-data` and one in `ufo`.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by CoryMartin-NOAA — APPROVED** [review]
Approved pending the BUFR tests that are failing get their references updated properly. Thanks for enforcing/fixing this!

**Comment by gthompsnJCSDA** [comment]
> Approved pending the BUFR tests that are failing get their references updated properly. Thanks for enforcing/fixing this!

@CoryMartin-NOAA 
Thanks, yup, trying to fix those last set of tests related to bufr2ioda.  Did you for sure see how I fixed/changed the gsi ncdiag files for radiance?  If you notice the radar section and the compo sections also cannot support non-floating point variables in the MetaData.  So this is suboptimal.  And, I didn't explicitly add support for either `long` or `double` type either.

**Comment by CoryMartin-NOAA** [comment]
@gthompsnJCSDA I think it's fine. GSI nc-diag's days are numbered and really are only for GMAO/EMC NWP-centric JEDI validation efforts. If we need the if/else in the other observation types we can implement that when we need to.

**Review by PatNichols — APPROVED** [review]
Looks good.

**Comment by BenjaminRuston** [comment]
seeing failures for `test_iodaconv_bufr_ncep_1bamua2ioda` and `test_iodaconv_bufr_ncep_1bamua2ioda_n15`

these should have been updated with PR https://github.com/JCSDA-internal/ioda-converters/pull/1304/files

**Comment by BenjaminRuston** [comment]
I see what happened these two files need to be updated in this PR with the new `valid_range`
```
test/testoutput/gdas.t12z.mtiasi_metop-c.tm00.nc
test/testoutput/gdas.t12z.amsua_n15.tm00.nc
```

**Review by BenjaminRuston — APPROVED** [review]
after update to the testoutput for ncep_amua ctests with new valid_range all tests passing

**Pull request merged**
