### PR TITLE
Feature/sprint viirs aod converters

### LINKED ISSUE #845: Upgrade converter for chem/modis_aod to follow the JEDI Data Conventions
Update the converter identified in the title (hereafter referred to as the **target converter**) to follow the JEDI Data Conventions.

- Update variable names
- Ensure variable units match the units in the conventions table
- Update the global attributes dictionary as needed
- Run the converter test to make sure it runs (but will fail because of unupdated test reference)
- Run ```ioda-validate.x``` on your output file and verify that there are no errors or warnings
- Update test reference file
- Run unit tests making use of the target converter and verify that they pass
- Make sure you verify the results by examining the file using ```ncdump -t```, ```h5dump```, ```HDFview```, or a similar application.

## ZenHub organization

Please make sure that you have properly set:
- Labels: OBS3
- Estimate: An estimate of how long this issue will take to resolve. 1 = half a day. 2 = full day. 3 = two days, 5 = three days.
- Epics: [Sprint: Implement the JEDI Data Conventions in the Converters](https://github.com/JCSDA-internal/ioda-converters/issues/813)
- Assignees: Anyone **working** on this issue. Anyone who is not working directly on the issue, but
  who should receive notifications, should be listed below.
- Reviewers

## Notifications

Fill in a list of GitHub handles here. People here are not *assigned*, but instead receive notifications
about this issue's progress.

Notifications should always go to: @rhoneyager.

Other people:

### LINKED ISSUE #846: Upgrade converter for chem/viirs_aod to follow the JEDI Data Conventions
Update the converter identified in the title (hereafter referred to as the **target converter**) to follow the JEDI Data Conventions.

- Update variable names
- Ensure variable units match the units in the conventions table
- Update the global attributes dictionary as needed
- Run the converter test to make sure it runs (but will fail because of unupdated test reference)
- Run ```ioda-validate.x``` on your output file and verify that there are no errors or warnings
- Update test reference file
- Run unit tests making use of the target converter and verify that they pass
- Make sure you verify the results by examining the file using ```ncdump -t```, ```h5dump```, ```HDFview```, or a similar application.

## ZenHub organization

Please make sure that you have properly set:
- Labels: OBS3
- Estimate: An estimate of how long this issue will take to resolve. 1 = half a day. 2 = full day. 3 = two days, 5 = three days.
- Epics: [Sprint: Implement the JEDI Data Conventions in the Converters](https://github.com/JCSDA-internal/ioda-converters/issues/813)
- Assignees: Anyone **working** on this issue. Anyone who is not working directly on the issue, but
  who should receive notifications, should be listed below.
- Reviewers

## Notifications

Fill in a list of GitHub handles here. People here are not *assigned*, but instead receive notifications
about this issue's progress.

Notifications should always go to: @rhoneyager.

Other people:

### PR DESCRIPTION
**Pull request by bhuang95**
## Description

*Update chem/viirs_aod converter to follow JEDI IODA convention*

Provide a detailed description of what this PR does.
The ioda-bundle/iodaconv/src/compo/viirs_aod2ioda.py converter and the corresponding ctest output file ioda-converters/test/testoutput/viirs_aod.nc have been updated to the latest [IODA conventions](https://docs.google.com/spreadsheets/d/1fHb2QIHOwgp4d6plyn9Dj9HZFZsDRxcPaUV6hdTb5BU/edit#gid=0) as of 2022/03/09.

I included "units" for preQC to avoid error after running ioda-validate.x. Instead, there was a warning as below
"Warning: Attribute 'units' is present but is not listed as a required or optional attribute in the spec."

[See the JEDI Documentation](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/pullrequest.html) for further information.

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #846 

If this does not close an existing issue, then [be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## Acceptance Criteria (Definition of Done)
Pass ctests test_iodaconv_viirs_aod

## Dependencies

If there are PRs that need to be merged before or along with this one, please add "waiting for another PR" label and list the dependencies in the other repositories (example below). Note that the branches in the other repositories should have matching names for the automated tests to pass.
Waiting on the following PRs:
- [ ]

### CODE REVIEW

**Comment by bhuang95** [comment]
viirs_aod2ioda.py was modified following Greg's change to MODIS AOD. It passed ctest and ioda-validator.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Review by andytangborn — APPROVED** [review]
This looks fine to me.

**Review by jeromebarre — APPROVED** [review]

**Comment by jeromebarre** [comment]
I guess the reasons why half of the tests are failing aws is because the tsagging branch is behind develop now?

**Comment by jeromebarre** [comment]
It seems this hasn't been merged to https://github.com/JCSDA-internal/ioda-converters/pull/817. The files changes in there do not reflect this.

**Comment by srherbener** [comment]
The tests related to VIIRS AOD are passing so I will merge this in now.

**Pull request merged**
