### PR TITLE
bugfix for running tests in a bundle.

### LINKED ISSUE #393: ghcn_snod test fails due to file not found.
https://github.com/JCSDA-internal/ioda-converters/blob/cfa4344fd5a0845c7b889ac50ac5ae538898efeb/test/CMakeLists.txt#L496

This test will always fail because the `doc/fix/ghcn-stations.txt` is not present in the `CMAKE_BINARY_DIR`

### PR DESCRIPTION
**Pull request by aerorahul**
## Description
This PR:
- uses `${PROJECT_BINARY_DIR}` instead of `${CMAKE_BINARY_DIR}` for the ghcn snow test.  This ensures the test runs in and out of the bundle.

What bug does it fix, or what feature does it add? fixes #393 
Is a change of answers expected from this PR? No

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #393 

## Dependencies
- None
- 
## Impact
All tests will pass when executed inside or outside of the bundles.

### CODE REVIEW

**Comment by YoulongXia-NOAA** [comment]
Originally I want to put txt file in testinput directory. As this file is a fixed file and it does not vary with time, after Steven, Cory and I discussed this file in the mail to recommended me create a doc and fix subdirectory and put it to there. Okay I will test soon.

**Comment by aerorahul** [comment]
closing for now.

**Comment by YoulongXia-NOAA** [comment]
For my ioda-converters, I just tested this change and it works. If you test it in ioda-biundle and worked. It should be fine. I incorporated it to feature/smap_ssm branch. Thank you for your finding and fix.

**Comment by YoulongXia-NOAA** [comment]
I also modified for feature/ghcn_snod branch. This change should be merged into develop in the future.

**Review by YoulongXia-NOAA — APPROVED** [review]
After I reviewed this PR, I approved it.

**Review by rhoneyager — APPROVED** [review]

**Review by srherbener — APPROVED** [review]

**Pull request merged**
