### PR TITLE
add updated SSMIS file for bufr2ioda for NCEPBufrLib

### LINKED ISSUE #1244: update ssmis ncep decode
## Description

an updated yaml for the SSMIS data in NCEP BUFR needs to be created

## Requirements

a NCEP BUFR file of SSMIS data for input

## Acceptance Criteria (Definition of Done)

a IODA file it output

### PR DESCRIPTION
**Pull request by BenjaminRuston**
## Description

add an updated yaml for the NCEP BUFRlib SSMIS file

### Issue(s) addressed

- fixes #1244 

### Acceptance Criteria (Definition of Done)

running with these file in UFO depends on https://github.com/JCSDA-internal/ufo/pull/2835
IODA output created and ctest passes

### CODE REVIEW

**Review by PatNichols — APPROVED** [review]
Looks good

**Comment by fabiolrdiniz** [comment]
There is another PR suggesting a few changes for this one here: https://github.com/JCSDA-internal/ioda-converters/pull/1252

**Review by fabiolrdiniz — APPROVED** [review]
Thanks, @BenjaminRuston!

**Comment by fabiolrdiniz** [comment]
@PatNichols, unfortunately, not yet. @BenjaminRuston tested it with a fresh build and looks like something got out of sync. We'll debug today.

**Pull request merged**
