### PR TITLE
ADT data conversion script associated with egm2008 gravity model

### LINKED ISSUE #989: update ADT data geoid from NESDIS
## Current behavior (describe the bug)
As of January 16, 2022 RADS NESDIS stopped reporting the geoid "xgm2016" for calculating the ADT in their netCDF files.
The current ioda converter (rads_adt2ioda.py) need to be updated to read "egm2008".
Lines 61-64 need to be updated.

Update lines 61-64 as follows:
        vals = ncd.variables['adt_egm2008'][:]
        val_units = ncd.variables['adt_egm2008'].units
        Fill_val = ncd.variables['adt_egm2008']._FillValue
        scale_factor = ncd.variables['adt_egm2008'].scale_factor

### PR DESCRIPTION
**Pull request by mjhossen**
## Description

This PR tests updated conversion scripts for rads adt through a ctest.

### Issue(s) addressed

- fixes #989 

## Acceptance Criteria (Definition of Done)

Pass the ctest

### CODE REVIEW

**Review by liuxiao37k — APPROVED** [review]

**Review by ShastriPaturi — APPROVED** [review]

**Comment by kbhargava** [comment]
Quick question do you care about the backward compatibility with older versions?

**Review by kbhargava — APPROVED** [review]
Ctests pass on orion.

**Comment by liuxiao37k** [comment]
> Quick question do you care about the backward compatibility with older versions?

@kbhargava good question. I was thinking the same thing while reviewing. I didn't look into the files, but given that the input file didn't have to be modified to pass the ctest, I assume both variables are reported in the older versions. hence, backward compatible?

**Comment by kbhargava** [comment]
> > Quick question do you care about the backward compatibility with older versions?
> 
> @kbhargava good question. I was thinking the same thing while reviewing. I didn't look into the files, but given that the input file didn't have to be modified to pass the ctest, I assume both variables are reported in the older versions. hence, backward compatible?

Thanks @liuxiao37k ! That makes sense. Both variables are indeed reported in the input data.

**Comment by ShastriPaturi** [comment]
> > > Quick question do you care about the backward compatibility with older versions?
> > 
> > 
> > @kbhargava good question. I was thinking the same thing while reviewing. I didn't look into the files, but given that the input file didn't have to be modified to pass the ctest, I assume both variables are reported in the older versions. hence, backward compatible?
> 
> Thanks @liuxiao37k ! That makes sense. Both variables are indeed reported in the input data.

@kbhargava and @liuxiao37k , as of 2022-01-16, only egm2008 is reported, so backward compatibility will be an issue. It is noted in the issue (#989) and hence the PR.

**Review by srherbener — APPROVED** [review]

**Pull request merged**
