### PR TITLE
Feature/gnssro awsopendata

### PR DESCRIPTION
**Pull request by hailingz**
## Description

This PR adds a new GNSSRO converter. It reads GNSSRO data from the AWS open data registry.
The AWS open data registry contains post-processed GNSSRO data from multiple processing centers (UCAR/COSMIC, ROMSAF, JPL). This converter focuses on the conversion of "atmPrf" in NETCDF. With this, we can use the post-processed RO data while other data feed (e.g., WMO bufr, NCEP bufr) are all near real-time data. 

data available at: https://registry.opendata.aws/gnss-ro-opendata/
documents available at: https://github.com/gnss-ro/aws-opendata

What problem does it fix? What new capability does it add?

adds a new GNSSRO converter.

## Acceptance Criteria (Definition of Done)
pass ctests:
ctest -R test_iodaconv_gnssro_AWSopendataNetcdf_conv

## Dependencies
N/A
## Impact
N/A

### CODE REVIEW

**Comment by hailingz** [comment]
I use this PR for testing, but I wonder if the ioda-bundle is broken due to the fail of "python install". 
 I will work on it if this is an issue only for my codes.
@PatNichols

**Comment by PatNichols** [comment]
> I use this PR for testing, but I wonder if the ioda-bundle is broken due to the fail of "python install". I will work on it if this is an issue only for my codes. @PatNichols

@Hae-CheolKim-NOAA yes the ci testing spack is broken still. Dom wants to fix the current stack rather than roll back to the old one so there's no telling how long until it's fixed.

**Comment by BenjaminRuston** [comment]
@hailingz putting the `ignore` label makes me want to look at it even more ;0)

**Comment by BenjaminRuston** [comment]
@Hae-CheolKim-NOAA good to know the plan with fixing the repository!

also this should really be combine with the other converter the changes are minimal to `gnssro_bufr2ioda.py` so it can work with both files

**Comment by PatNichols** [comment]
@hailingz  We got ioda-converters CI testing working again :) ! am going to kick off the tests. The ignore tests label was just for when the CI tests were failing right?

**Comment by PatNichols** [comment]
@hailingz Your PR failed a coding norms ctest. Some small edits should fix this and we can merge it :)

**Pull request closed without merging**
