### PR TITLE
Better way to handle inconsistent pressure units

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
A more robust way to check if pressure units are in Pa or hPa from GSI to convert to observation value/location

### CODE REVIEW

**Comment by danholdaway** [comment]
Thanks for adding this. It's definitely better than assuming that the data are Pa. Would the logic fail when the entire observation record was measured in Pa but be higher than 1100Pa though? I can't think of anything like that in the GSI so likely nothing to worry about but figured I'd ask the question. I don't think we assimilate sounding rockets in the GSI ;)

**Comment by CoryMartin-NOAA** [comment]
@danholdaway good point. I don't think there is anything that would be like this but I'm not sure. Since we are close to not needing GSI for ioda-converters anyways, I think we will be fine with this 1100 test.

**Review by srherbener — CHANGES_REQUESTED** [review]
Thanks for this update!

I'm requesting changes because there are two test failures:
- `iodaconv_gsi-ncdiag_coding_norms`
- `test_iodaconv_gsidiag_conv`

**Review by danholdaway — APPROVED** [review]
Approved subject to changes needed to pass CI

**Comment by srherbener** [comment]
I merged in develop to trigger the CI testing. There were fixes in develop that enabled CodeBuild testing and these tests should re-run the failing tests with verbosity turned up (so you can see what is failing).

**Comment by srherbener** [comment]
The CI testing is still seeing test failures. Here is what CI testing is reporting:

```
2: Test command: /build_container/bin/iodaconv_lint.sh "/src_repo/ioda-converters/src/gsi-ncdiag" "/src_repo/ioda-converters"
--
510 | 2: Environment variables:
511 | 2:  OMP_NUM_THREADS=1
512 | 2: Test timeout computed to be: 1500
513 | 2: + SRC_DIR=/src_repo/ioda-converters/src/gsi-ncdiag
514 | 2: + PYCODESTYLE_CFG_PATH=/src_repo/ioda-converters
515 | 2: + cd /src_repo/ioda-converters/src/gsi-ncdiag
516 | 2: + pycodestyle -v --config=/src_repo/ioda-converters/.pycodestyle --filename=*.py,*.py.in .
517 | 2: cli configuration: /src_repo/ioda-converters/.pycodestyle
518 | 2: directory .
519 | 2: checking ./combine_conv.py
520 | 2: checking ./gsi_ncdiag.py
521 | 2: ./gsi_ncdiag.py:699:53: E261 at least two spaces before inline comment
522 | 2: ./gsi_ncdiag.py:758:69: E261 at least two spaces before inline comment
523 | 2: checking ./proc_gsi_ncdiag.py
524 | 2: checking ./subset_files.py
525 | 2: checking ./test_gsidiag.py
526 | 2: 2       E261 at least two spaces before inline comment
527 | 1/2 Test  #2: iodaconv_gsi-ncdiag_coding_norms ...***Failed    0.37 sec
528 | test 28
529 | Start 28: test_iodaconv_gsidiag_conv
530 |  
531 | 28: Test command: /build_container/bin/iodaconv_comp.sh "netcdf" "/build_container/bin/test_gsidiag.py
532 | -i testinput/gsidiag_conv_t_sfc_test.nc
533 | -o testrun/
534 | -t conv
535 | -p sfc" "sfc_tv_obs_2018041500.nc4" "0.0"
536 | 28: Environment variables:
537 | 28:  OMP_NUM_THREADS=1
538 | 28: Test timeout computed to be: 1500
539 | 28: Platform:sfc Var:tv #Obs:39
540 | 28: ProcessedL 39 Conventional obs processed to: testrun//sfc_tv_obs_2018041500.nc4
541 | 28: Platform:sfc Var:tsen #Obs:1
542 | 28: ProcessedL 1 Conventional obs processed to: testrun//sfc_tsen_obs_2018041500.nc4
543 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [0] : VALUES : 100250 <> 1002.5
544 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [1] : VALUES : 93700 <> 937
545 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [2] : VALUES : 101580 <> 1015.8
546 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [3] : VALUES : 99630 <> 996.3
547 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [4] : VALUES : 99850 <> 998.5
548 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [5] : VALUES : 98150 <> 981.5
549 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [6] : VALUES : 101510 <> 1015.1
550 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [7] : VALUES : 96580 <> 965.8
551 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [8] : VALUES : 95130 <> 951.3
552 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [9] : VALUES : 101550 <> 1015.5
553 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [10] : VALUES : 96900 <> 969
554 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [11] : VALUES : 100880 <> 1008.8
555 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [12] : VALUES : 89920 <> 899.2
556 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [13] : VALUES : 101820 <> 1018.2
557 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [14] : VALUES : 101570 <> 1015.7
558 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [15] : VALUES : 101160 <> 1011.6
559 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [16] : VALUES : 98300 <> 983
560 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [17] : VALUES : 100860 <> 1008.6
561 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [18] : VALUES : 99550 <> 995.5
562 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [19] : VALUES : 97040 <> 970.4
563 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [20] : VALUES : 86980 <> 869.8
564 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [21] : VALUES : 100570 <> 1005.7
565 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [22] : VALUES : 91520 <> 915.2
566 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [23] : VALUES : 101000 <> 1010
567 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [24] : VALUES : 90180 <> 901.8
568 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [25] : VALUES : 99260 <> 992.6
569 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [26] : VALUES : 98270 <> 982.7
570 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [27] : VALUES : 100940 <> 1009.4
571 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [28] : VALUES : 81640 <> 816.4
572 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [29] : VALUES : 80070 <> 800.7
573 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [30] : VALUES : 97840 <> 978.4
574 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [31] : VALUES : 98480 <> 984.8
575 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [32] : VALUES : 97800 <> 978
576 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [33] : VALUES : 100740 <> 1007.4
577 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [34] : VALUES : 99110 <> 991.1
578 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [35] : VALUES : 100500 <> 1005
579 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [36] : VALUES : 100890 <> 1008.9
580 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [37] : VALUES : 95370 <> 953.7
581 | 28: DIFFER : VARIABLE : air_pressure@MetaData : POSITION : [38] : VALUES : 101220 <> 1012.2
582 | 28: Variable              Group Count         Sum      AbsSum     Min    Max   Range    Mean  StdDev
583 | 28: air_pressure@MetaData /        39 3.76033e+06 3.76033e+06 79269.3 100802 21532.5 96418.6 5247.23
584 | 2/2 Test #28: test_iodaconv_gsidiag_conv .........***Failed    0.21 sec
585 |  
586 | 0% tests passed, 2 tests failed out of 2
587 |  
588 | Label Time Summary:
589 | iodaconv    =   0.58 sec*proc (2 tests)
590 | script      =   0.58 sec*proc (2 tests)
591 |  
592 | Total Test time (real) =   0.58 sec
593 |  
594 | The following tests FAILED:
595 | 2 - iodaconv_gsi-ncdiag_coding_norms (Failed)
596 | 28 - test_iodaconv_gsidiag_conv (Failed)
597 | Errors while running CTest
```

**Comment by CoryMartin-NOAA** [comment]
Sorry @srherbener and @danholdaway, the tests should (hopefully) pass now. Needed to fix the two coding norms and update the reference output file for the new, correct, pressure units of Pa from hPa.

**Comment by srherbener** [comment]
Sorry about the delay getting back to this. Looks good now and thanks for fixing the test failures!

**Review by srherbener — APPROVED** [review]

**Pull request merged**
