### PR TITLE
changes needed for new containers

### PR DESCRIPTION
**Pull request by mer-a-o**
## Description

*(Instructions: replace text in this and all sections with your own text)*

Provide a detailed description of what this PR does.

What problem does it fix? What new capability does it add?

[See the JEDI Documentation](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/pullrequest.html) for further information.

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #<issue_number>

If this does not close an existing issue, then [be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## Acceptance Criteria (Definition of Done)

What does it mean for this PR to be finished?

## Dependencies

If there are PRs that need to be merged before or along with this one, please add "waiting for another PR" label and list the dependencies in the other repositories (example below). Note that the branches in the other repositories should have matching names for the automated tests to pass.
Waiting on the following PRs:
- [ ] waiting on JCSDA/eckit/pull/<pr_number>
- [ ] waiting on JCSDA/atlas/pull/<pr_number>

## Impact

Please list the other repositories (if any) that this PR will require changes in (example below)

- [ ] saber
- [ ] ufo
- [ ] ...

### CODE REVIEW

**Comment by climbfuji** [comment]
This seems to be working, but I get three test failures:
```
566 - test_iodaconv_tropomi_no2_tropo (Failed)
567 - test_iodaconv_mopitt_co (Failed)
569 - test_iodaconv_aeronet_aod (Failed)
```
All three seem to be failing due to floating point deviations, although these must be small, less than what is displayed: http://cdash.jcsda.org:8080/viewTest.php?onlyfailed&buildid=28449

**Comment by climbfuji** [comment]
@mer-a-o FYI

**Comment by srherbener** [comment]
> This seems to be working, but I get three test failures:
> 
> ```
> 566 - test_iodaconv_tropomi_no2_tropo (Failed)
> 567 - test_iodaconv_mopitt_co (Failed)
> 569 - test_iodaconv_aeronet_aod (Failed)
> ```
> 
> All three seem to be failing due to floating point deviations, although these must be small, less than what is displayed: http://cdash.jcsda.org:8080/viewTest.php?onlyfailed&buildid=28449

These all have their tolerance set to zero for the floating point comparisons. Here is the tropomi_no2_tropo example:

https://github.com/JCSDA-internal/ioda-converters/blob/25d08ed8e86f75d074828bbb675c6c986f95a449/test/CMakeLists.txt#L930

There is another cmake variable (`IODA_CONV_COMP_TOL`) that can be used to tell nccmp to use a non-zero tolerance:

https://github.com/JCSDA-internal/ioda-converters/blob/25d08ed8e86f75d074828bbb675c6c986f95a449/test/CMakeLists.txt#L341

It may just be a matter of switching to the non-zero tolerance for nccmp.

**Comment by srherbener** [comment]
FYI: The reason for a zero tolerance and a non-zero tolerance is that for converters that are simply copying values from the input file should get the exact same value in the output file (zero tolerance) and for converters that do any sort of numerical operation on values from the input file the non-zero tolerance should be used. I suspect these converters may fall into the latter category.

**Comment by srherbener** [comment]
I think the 3 Intel test failures are due to issues outside the scope of this PR, so I am okay merging this in without fixing those tests.

**Review by srherbener — COMMENTED** [review]
Thank you for providing this fix!

There are a number of lines with commented code. Please delete if it's old code that doesn't work. However, if there is value to keeping some of the commented code around it's okay to do so. I'm just asking to review the commented code and clean up whatever makes sense to do so. Thanks!

**Comment by climbfuji** [comment]
> Thank you for providing this fix!
> 
> There are a number of lines with commented code. Please delete if it's old code that doesn't work. However, if there is value to keeping some of the commented code around it's okay to do so. I'm just asking to review the commented code and clean up whatever makes sense to do so. Thanks!

Thanks, @srherbener ! I removed the unnecessary comments, I would like to keep the others for now. Having looked at several of these buildspecs today and yesterday, I think it is time for a full cleanup across repos to make them all a lot more similar and easier to maintain.

**Comment by climbfuji** [comment]
I removed only a few commented lines in https://github.com/JCSDA-internal/ioda-converters/pull/1056/commits/9da2df17e7be0d0bc5763b104c43b1a23dc0abeb and then pulled in develop, and now there are 14 tests that are failing that ran just fine beforehand?

**Comment by climbfuji** [comment]
I reverted pulling in "develop", since this PR is for the feature/query_cxx branch. Now it's only CI updates, hopefully the tests will be back to before the cleanup commit.

**Review by shlyaeva — APPROVED** [review]

**Comment by climbfuji** [comment]
@mer-a-o I also fixed the cdash links here, hopefully it's all good now (will wait for the CI tests to complete and then check the links).

**Comment by climbfuji** [comment]
Ok, this is good now. Same three tests fail for Intel as before, and as said by @srherbener earlier these are not due to this PR:
```
The following tests FAILED:
566 - test_iodaconv_tropomi_no2_tropo (Failed)
567 - test_iodaconv_mopitt_co (Failed)
569 - test_iodaconv_aeronet_aod (Failed)
```
@srherbener please review again and merge if satisfied. Thanks!

**Review by srherbener — APPROVED** [review]
Thanks!

**Comment by climbfuji** [comment]
Thanks very much, @srherbener !

Now these changes need to find their way into develop ... wait for feature/query_cxx being merged down, or cherry-pick the merged commit and create PR for develop?

**Comment by srherbener** [comment]
GNU and Clang tests passed on feature/query_cxx. Intel is still running. Let's wait for feature/query_cxx to be merged, then we can get someone to fix the broken intel tests.

**Pull request merged**
