### PR TITLE
Fix failing BUFR ctests.

### PR DESCRIPTION
**Pull request by rmclaren**
## Description

Fixes failing ctests for ioda-converter BUFR code.

### CODE REVIEW

**Comment by rmclaren** [comment]
@PraveenKumar-NOAA In your script `bufr_ncep_prepbufr_adpupa.py` you create a field for specificHumidity. The latest code fixed a problem with this field, and I was wondering if you would double checkout the data in output file `testoutput/prepbufr_adpupa_api.nc`?

**Comment by rmclaren** [comment]
Are we treating warnings as errors for the purpose of CI?

**Review by srherbener — APPROVED** [review]
Thanks for fixing this!

At this point the tests are all passing on my arm64 Mac, but there are still a few CI test failures. I'm going to approve now since I will be gone the next two weeks on leave. Someone please test again on the Mac after the CI testing is passing. Thanks!

**Comment by srherbener** [comment]
> Are we treating warnings as errors for the purpose of CI?

Warnings are not treated as errors at this point, but we are attempting to resolve all the compiler warnings in JEDI. Thanks for addressing the warnings in this PR!

**Comment by BenjaminRuston** [comment]
@rmclaren that fixed 3 of the 4 for all compilers..... and 4 out of 4 for `intel`
the CDASH output (though has a green check) can show the issues `gnu` and `clang` are seeing.  Orion can also build with a `gnu` environment

but here's a few lines of what is failing in the ctest: `test_iodaconv_prepbufr_ncep_aircftprofiles2ioda`

```
DIFFER : VARIABLE : pressure : POSITION : [53,6] : VALUES : 5.395e-43 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,7] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,8] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,9] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,10] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,11] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,12] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,13] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,14] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,15] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [54,0] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [54,1] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [54,2] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [54,3] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [54,4] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [54,5] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [54,6] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
```

**Comment by BenjaminRuston** [comment]
to see that CDASH output you gotta click details 
image


then scroll to the bottom and view test summary (and click on failing test)
image

**Comment by rmclaren** [comment]
@BenjaminRuston Thanks Ben, I was aware of this. This particular test is a little annoying as haven't been able to reproduce either on my machine or hera...

**Comment by BenjaminRuston** [comment]
@rmclaren thought you likely already new those steps...
and sorry to hear this has been difficult to track down.  Do you think we should move forward with the fix you've found, and potentially disable the remaining ctest:  `test_iodaconv_prepbufr_ncep_aircftprofiles2ioda` while we continue to investigate the solution?  
Could ask others next week, but think that may be a course of action for the time being.

**Comment by rmclaren** [comment]
So I recompiled everything on HERA last using the spack-stack 1.5.1 GNU gcc/g++ (9.2.0) compiler and I'm not seeing the failure there. The only difference I can see is that your CI machines are using a different version of the GNU compiler (9.4.0).

**Comment by rmclaren** [comment]
Is there any chance the source data on the CI machines is corrupted in some way? Bad checkout?

**Comment by BenjaminRuston** [comment]
@rmclaren I did have the infrastructure team re-examine the CI containers and @climbfuji verified these

that being said we should get some other eyes on this, @PatNichols please see if you notice anything that may suggest the cause of these last errors

**Comment by PatNichols** [comment]
@rmclaren @BenjaminRuston I will take a look on the AWS instance. To see if it passes.

**Comment by PatNichols** [comment]
This is the line from the failing tests from CI. It's repeared multiple times... Maybe 0 is not begin set to missing value?
I will check if appears on AWS.
DIFFER : VARIABLE : pressure : POSITION : [508,15] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100

**Comment by rmclaren** [comment]
@PatNichols Like I said on Hera I'm using 9.2.0 because thats the version available via spack-stack 1.5.1/

**Comment by PatNichols** [comment]
@rmclaren Are you using spack stack? spack-stack-1.5.1 or 1..5.0?

**Comment by PatNichols** [comment]
@rmclaren I am seeing the same failure on my intel mac using spack-stack-1.5.1,clang version 14.0 and gfortran version 12.
If this get too much to debug we can just eliminate the test for ci and deal with it in another PR later.

**Comment by PatNichols** [comment]
@rmclaren  What seems to be doing is assigning 0 to missing values? That just a guess though. The reference file has many missing values.

**Comment by BenjaminRuston** [comment]
@rmclaren just reproduced this on Orion.  Using your branch all ctests are passing except for:
```
test_iodaconv_prepbufr_ncep_aircftprofiles2ioda
```

this reproduces the same error our CI see.  When I'm using the `gcc` compiler.  Should be able to reproduce this on Orion with gnu by cloning the `ufo-bundle` and building with the environment:

```
# Purge all modules
module purge

# Load required modules
module use /work/noaa/epic/role-epic/spack-stack/orion/modulefiles
module load python/3.9.2
module load ecflow/5.8.4
module load mysql/8.0.31

# Gnu
module use /work/noaa/epic/role-epic/spack-stack/orion/spack-stack-1.5.1/envs/unified-env/install/modulefiles/Core
module load stack-gcc/10.2.0
module load stack-openmpi/4.0.4
module load stack-python/3.10.8

module load jedi-fv3-env
module load ewok-env
module load soca-env
```

looking back looks like the gnu compiller is `10.2.0` ?
```
Orion-login-3: /iodaconv >gcc --version
gcc (GCC) 10.2.0
```

**Comment by rmclaren** [comment]
What result do you get if you do `ncdump -h test/testrun/gdas.t12z.acft_profiles.prepbufr.nc`

**Comment by PatNichols** [comment]
> What result do you get if you do `ncdump -h test/testrun/gdas.t12z.acft_profiles.prepbufr.nc`

The look similar. Both have many missing values. I am looking closer to see where things are not lining up.

**Comment by PatNichols** [comment]
@rmclaren  This is the output from you PR for the pressure in one place

  2.477496e-41, 0, 3.279038e-43, 0, 0, 0, 3.279038e-43, 0, 0, 0, 0, 0, 0, 
      0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 4.040255e-38, 3.443831e-41, 4.040255e-38, 3.443831e-41, 
      4.040256e-38, 3.443831e-41, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 4.04026e-38, 3.443831e-41, 4.04026e-38, 3.443831e-41, 4.040261e-38, 
      3.443831e-41, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 4.040322e-38, 3.443831e-41, 4.040322e-38, 3.443831e-41, 
      4.040325e-38, 3.443831e-41, 0, 0, 0, 0,
  0, 0, 0, 0, 4.04034e-38, 3.443831e-41, 4.04034e-38, 3.443831e-41, 
      4.040343e-38, 3.443831e-41, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 4.040264e-38, 3.443831e-41, 4.040264e-38, 3.443831e-41, 
      4.040265e-38, 3.443831e-41, 0, 0, 0, 0, 0, 0,
  0, 0, 0, 0, 0, 0, 0, 0, 4.040313e-38, 3.443831e-41, 4.040313e-38, 
      3.443831e-41, 4.040316e-38, 3.443831e-41, 0, 0,

**Comment by rmclaren** [comment]
@PatNichols Thanks. I was actually looking to see the header information, not the data. Don't forget the -h option.

**Review by PraveenKumar-NOAA — APPROVED** [review]
Looks good.

**Comment by rmclaren** [comment]
@PraveenKumar-NOAA Thanks!

**Comment by BenjaminRuston** [comment]
@rmclaren , @PatNichols  and @climbfuji this is still failing on Orion following
https://spack-stack.readthedocs.io/en/1.5.1/PreConfiguredSites.html#msu-orion

and loading these (always load all three though assume only the first would be needed for the ioda-bundle):
```
module load jedi-fv3-env
module load ewok-env
module load soca-env
```

it does look like the output has changed this is the Orion output for the failing test `test_iodaconv_prepbufr_ncep_aircftprofiles2ioda`:

```
105: DIFFER : VARIABLE : pressure : POSITION : [53,6] : VALUES : 2.47988e-41 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [53,7] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [53,8] : VALUES : 2.4775e-41 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [53,9] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [53,10] : VALUES : 1.43455e-37 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [53,11] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [53,12] : VALUES : 1.43455e-37 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [53,13] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [53,14] : VALUES : 1.43455e-37 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [53,15] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [54,12] : VALUES : 1.82169e-44 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [55,12] : VALUES : 1.82169e-44 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [56,12] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [57,12] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [58,12] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [59,12] : VALUES : 1.82169e-44 <> 3.40282e+38 : PERCENT : 100
105: DIFFER : VARIABLE : pressure : POSITION : [60,12] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
```

**Comment by climbfuji** [comment]
> @rmclaren , @PatNichols and @climbfuji this is still failing on Orion following https://spack-stack.readthedocs.io/en/1.5.1/PreConfiguredSites.html#msu-orion
> 
> and loading these (always load all three though assume only the first would be needed for the ioda-bundle):
> 
> ```
> module load jedi-fv3-env
> module load ewok-env
> module load soca-env
> ```
> 
> it does look like the output has changed this is the Orion output for the failing test `test_iodaconv_prepbufr_ncep_aircftprofiles2ioda`:
> 
> ```
> 105: DIFFER : VARIABLE : pressure : POSITION : [53,6] : VALUES : 2.47988e-41 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [53,7] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [53,8] : VALUES : 2.4775e-41 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [53,9] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [53,10] : VALUES : 1.43455e-37 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [53,11] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [53,12] : VALUES : 1.43455e-37 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [53,13] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [53,14] : VALUES : 1.43455e-37 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [53,15] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [54,12] : VALUES : 1.82169e-44 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [55,12] : VALUES : 1.82169e-44 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [56,12] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [57,12] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [58,12] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [59,12] : VALUES : 1.82169e-44 <> 3.40282e+38 : PERCENT : 100
> 105: DIFFER : VARIABLE : pressure : POSITION : [60,12] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
> ```

Is this "erratic" behavior in a sense that it passes on some platforms, but not on others, or that it even changes on one platform? That's often caused by uninitialized variables or out-of-bounds array access etc.

**Comment by BenjaminRuston** [comment]
@climbfuji just looked at a previous log, the order the processors report changes .   the output does look the same .... 

```
PRE-MAIN-INFO Exporting Data
PRE-MAIN-INFO Finished [0.04s]
DIFFER : VARIABLE : pressure : POSITION : [53,6] : VALUES : 2.47988e-41 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,7] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,8] : VALUES : 2.4775e-41 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,9] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,10] : VALUES : 1.85421e-37 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,11] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,12] : VALUES : 1.85421e-37 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,13] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,14] : VALUES : 1.85421e-37 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [53,15] : VALUES : 0 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [54,0] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [55,0] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [56,0] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [57,0] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [58,0] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [59,0] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [60,0] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [61,0] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [62,0] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [63,0] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
DIFFER : VARIABLE : pressure : POSITION : [64,0] : VALUES : 1.4013e-45 <> 3.40282e+38 : PERCENT : 100
```

**Comment by BenjaminRuston** [comment]
@rmclaren 

i discussed this with @ADCollard and he agreed we could remove this ctest while we track this down

so break that into it's own separate issue and PR, will create a branch off yours and do this just review and merge into your branch if you feel alright with placing `test_iodaconv_prepbufr_ncep_aircftprofiles2ioda` in the ongoing investigation bin

do think this is a canary telling us about a small initialization type step yet to be found

**Comment by rmclaren** [comment]
@BenjaminRuston I think the std namespace is being polutteds with inconsistent versions of the std library...

**Comment by BenjaminRuston** [comment]
@rmclaren one last verification see you merged the deactivation of the ctest for now... move forward here and continue to debug `test_iodaconv_prepbufr_ncep_aircftprofiles2ioda`

are you able to duplicate the behavior on Orion ?

@climbfuji and @PatNichols did you see Ron's comment:


> @BenjaminRuston I think the std namespace is being polutteds with inconsistent versions of the std library...

**Comment by climbfuji** [comment]
> @rmclaren one last verification see you merged the deactivation of the ctest for now... move forward here and continue to debug `test_iodaconv_prepbufr_ncep_aircftprofiles2ioda`
> 
> are you able to duplicate the behavior on Orion ?
> 
> @climbfuji and @PatNichols did you see Ron's comment:
> 
> > @BenjaminRuston I think the std namespace is being polutteds with inconsistent versions of the std library...

On which platform? Which compiler?

**Comment by rmclaren** [comment]
Apparently my Orion account got deleted, as I've not used it enough... Feel free to merge this branch, I'll continue debugging on a different branch.

**Comment by rmclaren** [comment]
@BenjaminRuston Which porject are you building? I always compile ioda-bundle directly.

**Comment by BenjaminRuston** [comment]
> @BenjaminRuston Which project are you building? I always compile ioda-bundle directly.

yes @rmclaren I'm doing the same and just building the `ioda-bundle` to test the converters

**Comment by rmclaren** [comment]
@BenjaminRuston  Thanks.

**Pull request merged**
