### PR TITLE
update WMO satellite IDs

### LINKED ISSUE #1571: Check TROPICS WMO satellite ids
I'm looking at the NOAA TROPICS L1B to BUFR converter ([link](https://gitlab.ssec.wisc.edu/tropics_dpc/tropics_bufr_for_noaa/-/blob/master/resource_dir/scripts/run_bufr_encode_tropics.R?ref_type=heads#L457)), and realized that they have assigned different ids to the instruments than what are used in the JCSDA converter ([link](https://github.com/JCSDA-internal/ioda-converters/blob/2dcec8b78fd4b3f93ee688d830ce83a8da9347ea/src/hdf5/tropics_2ioda.py#L38-L44)). I checked the ECMWF catalog ([link](https://codes.ecmwf.int/odb/satelliteidentifier/)), and there is a discrepancy.

| Satellite | ioda-converter satellite id (SAID) | ECMWF satellite id |
| --- | --- | --- |
| TROPICS-01 | 933 | 709 |
| TROPICS-02 | 895 | None (failed to orbit) |
| TROPICS-03 | 896 | 228 |
| TROPICS-04 | 966 | None (failed to orbit) |
| TROPICS-05 | 967 | 263 |
| TROPICS-06 | 968 | 264 |
| TROPICS-07 | 969 | 284 |

@BenjaminRuston, you mentioned that you got these assignments from Jeff Ator. Who has an authoritative source?

### PR DESCRIPTION
**Pull request by BenjaminRuston**
## Description

Update the WMO satellite IDs using the ECMWF ODB table

## Issue(s) addressed

Resolves #1571 

## Impact

Use correct WMO IDs for TROPICS satellites

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by fcvdb — APPROVED** [review]
Thanks Ben!

**Comment by BenjaminRuston** [comment]
@ashley314 or @smaticka here it was noted the WMO instrument identifier was being put in place of the WMO satellite identifier, this was updated..  The tomorrow io number is still a placeholder an assignment will be final after NOAA NCEP starts producing their bufr files

**Review by smaticka — APPROVED** [review]
thanks for updating @BenjaminRuston !

02 and 04 are no longer used, correct?

**Comment by BenjaminRuston** [comment]
@smaticka correct TROPICS-02 and -04 we both lost at launch

**Pull request merged**
