### PR TITLE
Feature/gnssro fortran ncdiag2ioda2

### PR DESCRIPTION
**Pull request by hailingz**
## Description

This PR updates the gsincdiag2ioda file converter to IODA2.
Main update includes:
1) use epochtime: dateTime
2) use netcdf groups 

What problem does it fix? What new capability does it add?
This converter can converter the GSI diag files to IODA2 directly without the need of ioda-upgrade.x

### Issue(s) addressed
(https://github.com/JCSDA-internal/ufo/issues/1868)

## Acceptance Criteria (Definition of Done)
approval by reviewers @CoryMartin-NOAA 

## Dependencies
none

## Impact
none

### CODE REVIEW

**Review by CoryMartin-NOAA — APPROVED** [review]
assuming the output files are readable this looks good to me.

**Review by huishao-r — APPROVED** [review]
Thanks for getting this implemented!

**Review by fcvdb — APPROVED** [review]
Thanks Hailing.

**Review by srherbener — APPROVED** [review]
Looks good. Thanks for updating this!

**Pull request merged**
