### PR TITLE
Added GNAPS mnemonic to satwnds_new_subset_template.yaml

### PR DESCRIPTION
**Pull request by ilianagenkova**
Branch: [/feature/iodaconv_GNAPS](https://github.com/JCSDA-internal/ioda-converters/tree/feature/iodaconv_GNAPS)

Issue: #461 
https://github.com/JCSDA-internal/ioda-converters/issues/461

This PR means to add mnemonic GNAPS to satwnds_new_subset_template.yaml for improved ioda-converters robustness. 

This PR will close issue #461

### CODE REVIEW

**Review by aerorahul — COMMENTED** [review]
@ilianagenkova 
Can you also add a test where this is exercised?
If it is already covered in the tests, then you will need to update the output test file since it now contains a new variable `generating_application@MetaData`.

**Review by gthompsnJCSDA — COMMENTED** [review]
I am fine with this.  Is it generally true that ncols_conf will be a constant like 4 - since I thought there are typically 4 confidence settings.  And why would there be a second dimension of generating application for ncols_conf?  Are you sure that isn't just a single dimension variable [nloc]?

**Comment by ilianagenkova** [comment]
@gthompsnJCSDA  At the moment ncols_conf is generally 4, true, but that could change if the producers decide so. Therefore it's appropriate to have ncols_conf be a variable. And no, it isn't  a single dimension variable [nloc] . nloc is the number of obs/winds, and for each wind there are X repetitions of GNAPS-PCCF pairs. At the moment X=4. The 4 quality parameters are QI with FC, QI, w.out FC, Common QC w.out FC, Expected Error.

**Comment by rmclaren** [comment]
@aerorahul I added unit tests.

**Review by aerorahul — APPROVED** [review]
looks good.

**Comment by rmclaren** [comment]
Can anyone see why the build is failing?

**Review by rmclaren — APPROVED** [review]

**Comment by emilyhcliu** [comment]
@rmclaren The built is OK.  Two tests failed.

Screen Shot 2021-03-09 at 3 52 42 PM

**Review by emilyhcliu — CHANGES_REQUESTED** [review]
@ilianagenkova
Your changes look good.  But, need to fix the following two tests related to your changes:

47- test_iodaconv_bufr_satwnd_old_format (Failed)
48 - test_iodaconv_bufr_satwnd_new_format (Failed)

It is complaining that split_by_subset.x not found

**Comment by rmclaren** [comment]
@emilyhcliu That means that the NCEPLIB-bufr utility split_by_subset.x is not available in your shell. I guess this would need to be updated on the automated build machines as well.... 

@aerorahul How should we handle this?

**Comment by emilyhcliu** [comment]
@rmclaren 
The running log I showed in the previous comment is from AWS Build above.  I have access to AWS so I can see the build and run-time message there.

**Comment by aerorahul** [comment]
@rmclaren 
Perhaps adding a test that does not need the `split_by_subset` utility.  The files are already split.

**Comment by rmclaren** [comment]
@aerorahul I went ahead and added YAML files for the two different test cases and added those (in a sense, testing the same way we always do)

Unfortunately this is not a very good test, as it doesn't really exercise the code in question (run_satwnds.py). I was a bit hesitant to add these tests this way as they do not really test any different territory than the tests we already have. Generally you have "unit tests" that test individual code units (classes and functions), functional tests that test scenarios or use cases (basically make sure the software as a whole does what you intended it too), and regression tests that specifically test for bugs that you have fixed in the past in order to make sure they are not re-introduced. From the softwares perspective these YAML files do not meaningfully add to any of these categories... its a kind of beating a dead horse test. In the long run tests are resources that have to be maintained in their own right so I would avoid adding tests that add no new value to the ones that already exist.

**Review by rmclaren — APPROVED** [review]

**Review by srherbener — APPROVED** [review]
I see that the new tests are running and passing, and these changes look good. Thanks for contributing this!

**Pull request merged**
