### PR TITLE
For usage in surface data files in UFO, the height variable (metadata) is needed; so it was added

### PR DESCRIPTION
**Pull request by gthompsnJCSDA**
## Description

The height of observation is needed in UFO steps for surface data.  This is not ideal because within METARs, the convention is that height above surface elevation is 2 meters, but for winds it is 10 meters, so this addition is imperfect but good enough for now until a future version can take care of different variables can have a different height attribute.

### Issue(s) addressed

One was not created explicitly.  This is a pretty quick and simple addition.

## Acceptance Criteria (Definition of Done)

I ran the output ioda file from this converter into my UFO test and it was successful.

## Dependencies

None

## Impact

None

## Test Data

Since the converter now passes the new height@MetaData variable, I needed to create a new output netcdf file as the reference to compare against for ctest.  Therefore, please place this output file into the proper location in order for the automated testing to work properly.
[2020100106_metars_small.nc.gz](https://github.com/JCSDA-internal/ioda-converters/files/6461834/2020100106_metars_small.nc.gz)

### CODE REVIEW

**Comment by srherbener** [comment]
@gthompsnJCSDA I've installed the new METAR reference file which triggered the testing. I'll keep an eye on the tests.

**Comment by srherbener** [comment]
The METAR test passed, but the coding norms test failed:
```
test 6
--
969 | Start 6: iodaconv_metar_coding_norms
970 |  
971 | 6: Test command: /build_container/bin/iodaconv_lint.sh "/jcsda/ioda-bundle/iodaconv/src/conventional" "/jcsda/ioda-bundle/iodaconv"
972 | 6: Environment variables:
973 | 6:  OMP_NUM_THREADS=1
974 | 6: Test timeout computed to be: 10000000
975 | 6: + SRC_DIR=/jcsda/ioda-bundle/iodaconv/src/conventional
976 | 6: + PYCODESTYLE_CFG_PATH=/jcsda/ioda-bundle/iodaconv
977 | 6: + cd /jcsda/ioda-bundle/iodaconv/src/conventional
978 | 6: + pycodestyle -v --config=/jcsda/ioda-bundle/iodaconv/.pycodestyle --filename=*.py,*.py.in .
979 | 6: cli configuration: /jcsda/ioda-bundle/iodaconv/.pycodestyle
980 | 6: directory .
981 | 6: checking ./metar_csv2ioda.py
982 | 6: ./metar_csv2ioda.py:69:161: E501 line too long (200 > 160 characters)
983 | 6: 1       E501 line too long (200 > 160 characters)
984 | 1/1 Test #6: iodaconv_metar_coding_norms ......***Failed    0.07 sec
985 |  
986 | 0% tests passed, 1 tests failed out of 1
987 |  
988 | Label Time Summary:
989 | iodaconv    =   0.07 sec*proc (1 test)
990 | script      =   0.07 sec*proc (1 test)
991 |  
992 | Total Test time (real) =   0.07 sec
993 |  
994 | The following tests FAILED:
995 | 6 - iodaconv_metar_coding_norms (Failed)
996 | Errors while running CTest
```

**Review by srherbener — APPROVED** [review]
Looks good!

**Comment by gthompsnJCSDA** [comment]
> Looks good!


Steve, do I need to break that Header line that is more than 160 chars wide into 2 lines instead?  It is in a comment and clearly intentionally that long because the actual data files I am ingesting (CSV) have that list of variables.  But I could stick a forward slash roughly halfway through and put the remains on a second line below the first.

**Comment by srherbener** [comment]
> > Looks good!
> 
> Steve, do I need to break that Header line that is more than 160 chars wide into 2 lines instead? It is in a comment and clearly intentionally that long because the actual data files I am ingesting (CSV) have that list of variables. But I could stick a forward slash roughly halfway through and put the remains on a second line below the first.

Looks like that worked. Unfortunately, the coding style checker has its limitations. However following a coding style has some big benefits such as making the code more maintainable (consistent coding style).

**Comment by rhoneyager** [comment]
You can suppress the check for a single line with ```// NOLINT```. See https://en.wikipedia.org/wiki/Cpplint for details.

**Review by rhoneyager — APPROVED** [review]

**Pull request merged**
