### PR TITLE
Feature/common calling structure take 2

### PR DESCRIPTION
**Pull request by PatNichols**
Description
      This pull request allows all IODA converters written in python to be installable by pip and callable by module and package names. 

    Adds the required setup.py file with all known python dependencies.
    Adds the correct __init__.py files to the code.
    Adds the following code to src/lib_python/orddicts.py to manage the following deprecation so that python 3.10 can be used. See this [link](https://stackoverflow.com/questions/53978542/how-to-use-collections-abc-from-both-python-3-8-and-python-2-7).

try:
    from collections.abc import Callable
except ImportError:
    from collections import Callable

Removes the following code from all files and includes the correct module imports to replace it. These classes can now be called with lib_python import statements.
IODA_CONV_PATH = Path(__file__).parent/"@SCRIPT_LIB_PATH@"
if not IODA_CONV_PATH.is_dir():
    IODA_CONV_PATH = Path(__file__).parent/'..'/'lib-python'
sys.path.append(str(IODA_CONV_PATH.resolve()))

Removes all unused imports.

Moves the script generic_ob2ioda.py to the top level in source.
Changes any files or directories in src to use _ instead of - which is not allowed in python for modules or file names.
Important notes:

This passes all ctests in ioda-bundle except 581 - test_iodaconv_airnow. This is due to the converter's name being mismatched due to the change from _ to -. The test file test/testoutput/airnow_2020081306.nc needs to have the top level attribute for converter updated to airnow2ioda_nc.py from airnow2ioda-nc.py.

## Issues

see above

## Acceptance Criteria (Definition of Done)

      Needs to pass all ctests in ioda and ufo bundles.

## Dependencies

     None

## Impact
    
    Like most packages in the jedi suite, a bug can effect all other areas. Assuming there are no visible bugs there will be no impact.

### CODE REVIEW

**Comment by PatNichols** [comment]
@ericlingerfelt This has Dom's fix in it. That's about the only change....

**Comment by BenjaminRuston** [comment]
I'm getting 4 failures

The following tests FAILED:
	 60 - test_iodaconv_viirs_aod (Failed)
	 66 - test_iodaconv_modis_aod (Failed)
	 69 - test_iodaconv_airnow (Failed)
	105 - test_iodaconv_generic_gnssro_bufr (Failed)

**Comment by PatNichols** [comment]
Me roo

> I'm getting 4 failures
> 
> The following tests FAILED: 60 - test_iodaconv_viirs_aod (Failed) 66 - test_iodaconv_modis_aod (Failed) 69 - test_iodaconv_airnow (Failed) 105 - test_iodaconv_generic_gnssro_bufr (Failed)

There are way more than that in the ctests on github. >100

**Comment by PatNichols** [comment]
@ericlingerfelt do you know why there is a conflict. ?

**Comment by ericlingerfelt** [comment]
Hi All - Unfortunately, I do not currently have time to test this PR and determine the cause of the `ctest` issues that are taking place. I am currently involved with rolling out the new R2D2 system within strict deadlines. Thanks for working on this upgrade to the python ioda converters, @PatNichols and @BenjaminRuston!

**Comment by fcvdb** [comment]
What is the procedure to install the modules?
After building` ioda-bundle`, I tried
`cd <build>/iodaconv;  python3 -m pip install -e .;`
But in `<build>/iodaconv/test/CTestTestfile.cmake` the PYTHON path is hardcoded to:
`PYTHONPATH=<src>/ioda-bundle/iodaconv/test/../src:${PYTHONPATH}`
And I don't see the modules there.

**Comment by PatNichols** [comment]
@BenjaminRuston @fcvdb  I am getting the same number of error as Ben now. I think the CMake files need to be changed to get the paths right. We can do a pip install within the cmake I suppose. @ericlingerfelt is this what you intended?

**Comment by ericlingerfelt** [comment]
Hi @PatNichols, I think in the case of CMakeLists one should be able to link the python packages by amending PYTHONPATH. In the case of a user creating new python code that imports a converter, then one would use a `venv` and `pip install`. We can always ask @mer-a-o if she uses a `pip install` in the CI for the EWOK testing. I don't usually work on the CI / ctest end of things.

**Comment by BenjaminRuston** [comment]
down to a single failure:
` 59 - test_iodaconv_wrfdadiag_rad (Failed)`

this looks like deprecated code.  do we support `wrfdadiag` files?  Also none of the naming conventions have been updated in the file:  `wrfda_ncdiag.py`

@huishao-r should we just remove this test,, oh and I see @jjguerrette name all over this as well

are we still maintaining this?

**Comment by climbfuji** [comment]
@BenjaminRuston @huishao-r Ok to remove `src/wrfda_ncdiag` with everything underneath, as well as the test files?

**Comment by climbfuji** [comment]
@BenjaminRuston I got past your import error, now I have
```
File "/jcsda/ioda-bundle/ioda/src/engines/ioda/python/pyioda/ioda/__init__.py", line 8, in <module>
  from ._ioda_python import *
ModuleNotFoundError: No module named 'ioda._ioda_python'
```
I'll look into this later today or on Tuesday

**Comment by climbfuji** [comment]
I also would like to know what to do with the wrfda_ncdiag converter. Thanks!

**Comment by BenjaminRuston** [comment]
@climbfuji please comment the ctest for it out, will fix and reactivate or remove

**Comment by climbfuji** [comment]
@PatNichols @BenjaminRuston Almost there ... a few more iterations and I should have all three CI tests working again.

**Comment by climbfuji** [comment]
@BenjaminRuston I am puzzled. I got clang and intel to work, but GNU is still failing despite the `PYTHONPATH` being correct. My last resort before removing the (imo questionable) `nonroot` stuff from the GNU build is to launch the container manually and repeat all the steps that the CI test does.

**Comment by BenjaminRuston** [comment]
thanks @climbfuji, this small change just keeps on giving

**Comment by climbfuji** [comment]
@BenjaminRuston @PatNichols This is working now. I ended up adding the necessary `PYTHONPATH` entries manually to the CI buildspec scripts. Also, I got rid of the entire `nonroot` logic for GNU/OPENMPI. By simply setting two environment variables, one can run MPI as root, and by setting another variable, one can oversubscribe MPI tasks (@mer-a-o FYI). CI tests all passed for https://github.com/JCSDA-internal/ioda-converters/pull/1161/commits/99f84b136a8b9857bccf0f373f550135c6f59fec, the following commit just removed some commented-out code from the CI scripts (tests still running).

I am ok to approve this and merge it, knowing that we have to come back and clean the ioda-converters up up significantly. This should include installing ioda and pyioda python bindings in the proper Python directory tree (venv etc.), and consolidating the many converters into a common framework that gets reused by the different converters.

**Review by climbfuji — APPROVED** [review]

**Review by mer-a-o — APPROVED** [review]
Changes in CI directory look good.

**Comment by PatNichols** [comment]
@BenjaminRuston @climbfuji  This is still failing a great deal of ctests in the ioda_bundle on aws. There seems to be some problems with what github is doing for ctests and actually running it in the wild.The following tests FAILED:
	570 - test_iodaconv_nsidc_l4cdr_icec (Failed)
	571 - test_iodaconv_copernicus_l4icethk (Failed)
	572 - test_iodaconv_amsr2_l2icec (Failed)
	573 - test_iodaconv_gds2_sst_l2p (Failed)
	574 - test_iodaconv_gds2_sst_l3u (Failed)
	575 - test_iodaconv_smap_sss (Failed)
	576 - test_iodaconv_rads_adt (Failed)
	577 - test_iodaconv_godae_prof (Failed)
	578 - test_iodaconv_godae_ship (Failed)
	579 - test_iodaconv_godae_trak (Failed)
	580 - test_iodaconv_hgodas_adt (Failed)
	581 - test_iodaconv_hgodas_insitu (Failed)
	582 - test_iodaconv_hgodas_sst (Failed)
	583 - test_iodaconv_glider (Failed)
	584 - test_iodaconv_hfradar (Failed)
	585 - test_iodaconv_argoclim (Failed)
	586 - test_iodaconv_cryosat2 (Failed)
	587 - test_iodaconv_emc_ice (Failed)
	588 - test_iodaconv_smos_sss (Failed)
	589 - test_iodaconv_copernicus_l4adt (Failed)
	590 - test_iodaconv_copernicus_l3swh (Failed)
	591 - test_iodaconv_swot_l2adt (Failed)
	592 - test_iodaconv_sst_ostia (Failed)
	593 - test_iodaconv_avhrr_radiance (Failed)
	594 - test_iodaconv_pace_oc_l2 (Failed)
	595 - test_iodaconv_pace_radiance_L1B (Failed)
	596 - test_iodaconv_mls_o3_l2 (Failed)
	597 - test_iodaconv_omi_o3_l2 (Failed)
	598 - test_iodaconv_ompsnm_o3_l2 (Failed)
	599 - test_iodaconv_satwinds (Failed)
	600 - test_iodaconv_metar (Failed)
	601 - test_iodaconv_sondetac (Failed)
	602 - test_iodaconv_viirs_jpss1_oc_l2 (Failed)
	603 - test_iodaconv_modis_aqua_oc_l2 (Failed)
	604 - test_iodaconv_viirs_jpss1_oc_l3 (Failed)
	605 - test_iodaconv_godae_bgc_argo (Failed)
	610 - test_iodaconv_gsidiag_conv_uv (Failed)
	611 - test_iodaconv_gsidiag_conv (Failed)
	612 - test_iodaconv_gsidiag_rad (Failed)
	614 - test_iodaconv_viirs_aod (Failed)
	616 - test_iodaconv_tropomi_no2_total (Failed)
	617 - test_iodaconv_tropomi_no2_tropo (Failed)
	618 - test_iodaconv_mopitt_co (Failed)
	619 - test_iodaconv_tropess_cris_co (Failed)
	620 - test_iodaconv_modis_aod (Failed)
	621 - test_iodaconv_aeronet_aod (Failed)
	622 - test_iodaconv_aeronet_aaod (Failed)
	623 - test_iodaconv_airnow (Failed)
	624 - test_iodaconv_tropomi_co_total (Failed)
	659 - test_iodaconv_generic_gnssro_bufr (Failed)
	660 - test_iodaconv_atms_nc4 (Failed)
	670 - test_iodaconv_ghcn_snod (Failed)
	671 - test_iodaconv_smap_ssm (Failed)
	672 - test_iodaconv_smos_ssm (Failed)
	673 - test_iodaconv_ascat_ssm (Failed)
	674 - test_iodaconv_imsfv3_scf (Failed)
	675 - test_iodaconv_smap9km_ssm (Failed)
	676 - test_iodaconv_land_owp_snow_obs_dup_thin (Failed)

**Comment by PatNichols** [comment]
@BenjaminRuston @climbfuji  One frequent failure message is:"test_iodaconv_nsidc_l4cdr_icec" start time: Feb 22 17:02 UTC
Output:
----------------------------------------------------------
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4)
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/home/ubuntu/ioda_b_ccs/bld/bin/nsidc_l4cdr_ice2ioda.py", line 24, in <module>
    import ioda_conv_engines as iconv
  File "/home/ubuntu/ioda_b_ccs/bld/lib/pyiodaconv/ioda_conv_engines.py", line 3, in <module>
    import ioda_obs_space as ioda_os
ModuleNotFoundError: No module named 'ioda_obs_space'
<end of output>
Test time =   0.28 sec
-------------

**Comment by PatNichols** [comment]
Sorry about the big font. This was a cut and paste

**Comment by climbfuji** [comment]
You’ll need to fix the PYTHONPATH similar to what I’ve done, and either update the tests/CMakeLists.txt or provide instructions for how to do this manually.

**Comment by PatNichols** [comment]
Looks like a mangled python path.

**Comment by PatNichols** [comment]
updating manually would be an ugly kludge. I will look at the CMakeLists.txt to do see what can do done there.

**Comment by PatNichols** [comment]
Updating manually would be an ugly

**Comment by PatNichols** [comment]
Maybe the python path from ioda ctests is being reset from the iodaconv ctests.

**Comment by BenjaminRuston** [comment]
@travissluka this is close to going in, and it will impact the environment which calls a python converter.  You can either extend the PYTHONPATH to include the `iodaconv/src`, or do a `python3 -m pip install -e .`

would like to know of any impacts this would have on current SOCA workflow

**Comment by CoryMartin-NOAA** [comment]
How do we fix this pythonpath issue in a bundle? The ctests will fail unless the IODA python API is on `$PYTHONPATH` as described above. Simply setting that at runtime won't help, and it shouldn't be set at build time because it doesn't exist yet...

**Comment by BenjaminRuston** [comment]
we can add a pip install to the CMakeLists.txt at `src/CMakeLists.txt`

**Comment by CoryMartin-NOAA** [comment]
I'm hesitant about `pip install` being the correct solution here, because what if the user is installing a bundle but using a python env that they do not have permissions for? Then it would need to be a local pip install.

**Comment by climbfuji** [comment]
Yes that needs to be a venv. We do the same for solo, r2d2, ewok so those instructions should be used for ioda-converters as well. That said, the way the converters are built (and not really installed) is flawed.

**Comment by PatNichols** [comment]
@BenjaminRuston @climbfuji  Not all of the converters are on the new system of calling pyiodaconv/lib_python. Look at some of the marine ones.

**Comment by climbfuji** [comment]
I am looking into the PYTHONPATH issue, and it seems that `$<TARGET_FILE_DIR:_ioda_python>/../` gets set correctly in ioda, but not in iodaconv. Trying to figure this out ...

**Review by climbfuji — CHANGES_REQUESTED** [review]
Dismissing my approval until we got the issues around PYTHONPATH sorted out

**Comment by srherbener** [comment]
> I am looking into the PYTHONPATH issue, and it seems that `$<TARGET_FILE_DIR:_ioda_python>/../` gets set correctly in ioda, but not in iodaconv. Trying to figure this out ...

FYI: `_ioda_python` is a target that gets set in ioda and needs to be passed to iodaconv so that iodaconv knows where the ioda python API was loaded (the `ioda` and `ioda_obs_space` python modules). Unfortunately, the current CMake configuration doesn't build the proper export/import scripts to pass the `_ioda_python` target from ioda to iodaconv (or other repos).

See https://github.com/JCSDA-internal/ioda/issues/574 for details. This might be the proper approach to fix this, but it would be good for a CMake expert to review this and advise accordingly.

**Comment by climbfuji** [comment]
I may have a different fix for this today, stay tuned

**Comment by PatNichols** [comment]
@climbfuji @srherbener @BenjaminRuston Ben seems to fixed the issue. All ctests are apssing in the ioda bundle. We probably need some blessing from outside and to do a once over to see if we banished the IODA_CONV_PATH from all files but it looks good so far.

**Review by PatNichols — COMMENTED** [review]
This is the fix

**Comment by climbfuji** [comment]
I'll review again in a bit. You may want to experiment removing some of the manual PYTHONPATH additions in the buildspec/*CI* files, now that Ben fixed it.

**Review by climbfuji — APPROVED** [review]
All ctests pass on my mac for ioda-bundle except `test_util_signal_trap`, which is unrelated to this PR. Before merging this PR, please make sure to communicate with the relevant users and developers and update/provide documentation, so that they know what they have to do. Thanks!

**Comment by CoryMartin-NOAA** [comment]
@BenjaminRuston not yet, let me do that after my 3pm and get back to you by tomorrow AM. If I haven't complained by Tuesday AM, consider it mergeable.

**Review by CoryMartin-NOAA — APPROVED** [review]
*most* tests are passing on Hera in ioda-bundle with this converters branch. I won't hold this up for a handful of tests out of 272. Approved and thanks for finding a solution to this that works for everyone.


```
	530 - test_iodaconv_sondetac (Failed)
	535 - test_iodaconv_ncep_bufr (Failed)
	549 - test_iodaconv_modis_aod (Failed)
	588 - test_iodaconv_generic_gnssro_bufr (Failed)
```

**Comment by PatNichols** [comment]
@CoryMartin-NOAA Thank you for testing!

**Pull request merged**
