### PR TITLE
amv_ssec performance bug

### PR DESCRIPTION
**Pull request by PatNichols**
## Description

The python script src/convential/amv_ssec_ascii2ioda.py was incredibly slow when reading multiple files. This change improved performance a factor of 5 on our test by creating a local_data for each file then appending that to the global data variable rather than appending to global_data directly. Since np.append reallocates an array with each append this saves memory from thrashing. A read of six files went down from 6min to 65 seconds.
  Only the file in question was changed.

### Issue(s) addressed

The above issue was outlined in issue #932 

## Acceptance Criteria (Definition of Done)

The changes are done and ready to be merged after review. The time is nearly linear with # of files accounting for file sizes.

## Dependencies

None

## Impact

No impact on other projects or in other parts of ioda-coverters.

### CODE REVIEW

**Comment by PatNichols** [comment]
the only real change is in the file mentioned

**Comment by BenjaminRuston** [comment]
did you commit from your build directory?  

there are 668 files changed,, so think this did not go as intended?

**Comment by fabiolrdiniz** [comment]
Hi, @PatNichols. Thanks for adding me here. Nice that you worked on it. I believe that the `bld` folder has been added to your commit. Usually, people create a folder name as `build` inside the cloned copy of the repository, because the `.gitignore` file will ignore it. Please see this line: https://github.com/JCSDA-internal/ioda-converters/blob/a0bc40bdfbbbe897c2a68417c11abbff612adb71/.gitignore#L2

**Comment by PatNichols** [comment]
This branch is broken will create new pr.

**Pull request closed without merging**
