### PR TITLE
Bugfix for multiple input files in TROPOMI converter

### LINKED ISSUE #741: Tropomi converter doesn't work properly for 2+ files at once
## Current behavior (describe the bug)
```
  File "/scratch1/NCEPDEV/da/Cory.R.Martin/JEDI/stable/ioda-bundle/build_20220106/bin/tropomi_no2_nc2ioda.py", line 217, in <module>
    main()
  File "/scratch1/NCEPDEV/da/Cory.R.Martin/JEDI/stable/ioda-bundle/build_20220106/bin/tropomi_no2_nc2ioda.py", line 207, in main
    no2 = tropomi(args.input)
  File "/scratch1/NCEPDEV/da/Cory.R.Martin/JEDI/stable/ioda-bundle/build_20220106/bin/tropomi_no2_nc2ioda.py", line 58, in __init__
    self._read()
  File "/scratch1/NCEPDEV/da/Cory.R.Martin/JEDI/stable/ioda-bundle/build_20220106/bin/tropomi_no2_nc2ioda.py", line 151, in _read
    (self.loc_mdata[varname_ak], avg_kernel[..., k].ravel()))
AttributeError: 'tropomi' object has no attribute 'loc_mdata'
```

## To Reproduce

For example:
`tropomi_no2_nc2ioda.py -i S5P_OFFL_L2__NO2____20190801* -o test.nc`

## Expected behavior
Multiple files should concatenate together to one output file

## Additional information (optional)
Note if you specify only one input file, it works as intended.

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
## Description

Bug fix for replacing `loc_mdata` with `outdata` in case where there are multiple input files in the TROPOMI NO2 converter.

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #741

## Acceptance Criteria (Definition of Done)

Approved by @jeromebarre and @srherbener 

## Dependencies

None

## Impact

None

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
Not sure why automated CI fails, but tests pass for me on NOAA RDHPCS Hera.

**Review by jeromebarre — COMMENTED** [review]
This was an easy fix. :)
Thanks for doing this!

**Review by jeromebarre — APPROVED** [review]

**Comment by jeromebarre** [comment]
> Not sure why automated CI fails, but tests pass for me on NOAA RDHPCS Hera.

stating the obvious here: Are you UTD with develop?

**Review by srherbener — APPROVED** [review]
Changes look good! Thanks for fixing this.

**Pull request merged**
