### PR TITLE
Update and bug fix in converting GSI gps and humidity outputs to IODA.

### PR DESCRIPTION
**Pull request by gmao-jjin3**
Updated the Python program gsi_ncdiag.py to convert GSI ncdiag files into IODA files.
(1) Add more satellite IDs for commercial GNSSRO data.
(2) Bug-fix.  Remove the redundant writing out of "Model_Elevation".
(3) Bug-fix.  The GNSSRO "recorder_number" is saved as "recorder_number", not "Observation_Subtype" in GEOS NeCDF outputs.  Therefore, restore the original code to sort GNSSRO data by the variable "recorder_number".
(4) Save "saturated_specific_humidity_profile" and "saturated_specific_humidity" to produce GEOS specific humidity IODA files.

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
Definitely want to defer to @XuanliLi-NOAA and @emilyhcliu on this since some of these changes revert changes they made (through me) a month or 2 ago.

**Comment by gmao-yzhu** [comment]
The assignment of record_number is important, it will affect the results of sorting program. Jianjun's change on record_number works for the GEOS. If it is different from NCEP's, maybe an option parameter could be added.

**Comment by XuanliLi-NOAA** [comment]
I think the change with record_number is fine, we can update the variable name from Observation_Subtype to record_number in GSI. But in Line 78, the satellite id for GPS should also include these: 266, 267, 268 for commercial RO, 66 for Sentinel-6, and 803 and 804 for GRACE.

**Comment by danholdaway** [comment]
I pushed another small change we need to keep GMAO functionality alive.

**Comment by PatNichols** [comment]
@gmao-jjin3 ioda converters is broken. Expect ci tests to fail.

**Review by danholdaway — APPROVED** [review]

**Review by BenjaminRuston — APPROVED** [review]
this looks good

**Comment by BenjaminRuston** [comment]
coding norms to fix.... you can see this on the details from the CDASH lines (confusing becuase has a green checkmark)... click that `Details` button then bottom of the page `View Test Summary` and you get this:

```
+ SRC_DIR=/jcsda/ioda-bundle/iodaconv/src/gsi_ncdiag
+ PYCODESTYLE_CFG_PATH=/jcsda/ioda-bundle/iodaconv
+ cd /jcsda/ioda-bundle/iodaconv/src/gsi_ncdiag
+ pycodestyle -v --config=/jcsda/ioda-bundle/iodaconv/.pycodestyle --filename=*.py,*.py.in .
cli configuration: /jcsda/ioda-bundle/iodaconv/.pycodestyle
directory .
checking ./__init__.py
checking ./combine_files.py
checking ./combine_obsspace.py
checking ./gsi_ncdiag.py
./gsi_ncdiag.py:78:13: E201 whitespace after '['
./gsi_ncdiag.py:78:17: E241 multiple spaces after ','
./gsi_ncdiag.py:78:22: E241 multiple spaces after ','
./gsi_ncdiag.py:78:27: E241 multiple spaces after ','
./gsi_ncdiag.py:78:32: E241 multiple spaces after ','
./gsi_ncdiag.py:78:37: E241 multiple spaces after ','
./gsi_ncdiag.py:78:42: E241 multiple spaces after ','
./gsi_ncdiag.py:78:67: W291 trailing whitespace
./gsi_ncdiag.py:79:13: E128 continuation line under-indented for visual indent
./gsi_ncdiag.py:80:13: E128 continuation line under-indented for visual indent
checking ./proc_gsi_ncdiag.py
checking ./test_gsidiag.py
2       E128 continuation line under-indented for visual indent
1       E201 whitespace after '['
6       E241 multiple spaces after ','
1       W291 trailing whitespace
```

**Review by gmao-yzhu — APPROVED** [review]
looks fine to me.

**Pull request merged**
