### PR TITLE
Add total column values to TROPOMI

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
## Description

Adding in conversion of total column NO2 observations to compliment the tropospheric only values.

### CODE REVIEW

**Comment by mpagowski** [comment]
Apologies, away till Tuesday.

**Comment by YoulongXia-NOAA** [comment]
I look at the final output tropomi_no2.nc in test/testoutput, as I did for afwa snow depth before, there is no unit there. If you look at my python code in afwa snow feature branch, it is easy to add unit into output nc file. This will let the users know the products more clearly.  If possible, please add units in your code.

**Comment by YoulongXia-NOAA** [comment]
For If ... else sentence, now it is fine. To add more broad capacity for future use if you like to add more variable,  use if with defined name may be more helpful. This suggestion is totally up to your decision.

**Comment by CoryMartin-NOAA** [comment]
@YoulongXia-NOAA added units. As for the if statement (I assume you mean lines 132-137), this is because of the way the input file is structured, but I'm open to suggestions on a better way to do it.

**Comment by YoulongXia-NOAA** [comment]
> @YoulongXia-NOAA added units. As for the if statement (I assume you mean lines 132-137), this is because of the way the input file is structured, but I'm open to suggestions on a better way to do it.

Yes, in future I will meet the same issue. If you have a good way, please try it. If not, just keep it.

**Review by srherbener — APPROVED** [review]
Thanks for the update!

We may want to make a more sophisticated netcdf parser to go with the work Ron is doing, but that is for future development. I think the if-else (lines 132-137) is good for this PR.

**Comment by YoulongXia-NOAA** [comment]
As Steven thought that if else is fine right now for this PR. I did not have any concern now. So I approved this PR.

**Review by YoulongXia-NOAA — APPROVED** [review]
I approved this pull request.

**Pull request merged**
