### PR TITLE
converter for CALIPSO Level 2 Aerosol Profile V4.2 data

### PR DESCRIPTION
**Pull request by weiwilliam**
## Description
This PR introduces the converter (src/compo/calipso_hdf4_2ioda.py) for the CALIPSO level 2 extinction coefficient file.
CI test (iodaconv_validate_testoutput_calipso_l2.nc) has been added and tested.

### CODE REVIEW

**Comment by srherbener** [comment]
The ctests are reporting coding norms failures for the `calipso_hdf4_2ioda.py` script and we don't have the `pyhdf` package installed in the CI test containers yet. I believe that we do have `pyhdf` installed in the spack-stack based containers so we will have to wait until the containers get updated. Sorry about that. We are focused on the upcoming release (this week) and should be able to get to the test contains soon (hopefully, next week).

**Comment by srherbener** [comment]
Sorry I was not able to get to this review this week. Unfortunately, I'm going on leave for the next two weeks. I'm going to remove myself as a reviewer since I will be gone, and replace myself with another reviewer. Thank you for your understanding.

**Comment by jeromebarre** [comment]
Thanks for submitting this PR. As a general comment please clean tyour code before PR. Comments should be for commenting as much as possible. We can accept few exceptions where a line of two of code is passed in comment but this is too extensive. 

Also I would remove and create a new set of script, test input and output files for the backscatter product. Pleas do it in a separate PR for clarity.

Thanks

**Comment by weiwilliam** [comment]
Thank you, @srherbener and @jeromebarre
I'll clean up the comments in CALIPSO L2 data converter and issue another PR for L1 converter.

**Comment by weiwilliam** [comment]
I clean up the python script but leave some lines commented out for future use.
The name has been changed to calipso_l2_hdf4_2ioda.py for the distinction to L1 converter.

**Comment by jeromebarre** [comment]
Thanks for cleaning your code. It now looks good. As soon as `pyhdf` is added to the containers this will be merged.
@climbfuji @mer-a-o

**Comment by climbfuji** [comment]
> Thanks for cleaning your code. It now looks good. As soon as `pyhdf` is added to the containers this will be merged.
> @climbfuji @mer-a-o

Yep, working on it.

**Comment by weiwilliam** [comment]
Temporarily closed, I'll resubmit a pull request when the converted data provide needed information to UFO. Thanks.

**Pull request closed without merging**
