### PR TITLE
Update sfc_tv_obs_2018041500.nc4 to be consistent with #953

### PR DESCRIPTION
**Pull request by FanHan-NOAA**
## Description

Update sfc_tv_obs_2018041500.nc4 to be consistent with [#953](https://github.com/JCSDA-internal/ioda-converters/pull/953)

### CODE REVIEW

**Comment by srherbener** [comment]
@FanHan-NOAA thank you for this PR. The tests related to the `sfc_tv_obs_2018041500.nc4` file are failing, and I think the issue is that the develop version (with the old names) is being used in this PR instead of the version with the new names following the jedi conventions. I think if you run the test using the `feature/sprint-ioda-converters` branches and verify that you get the expected changes, then you can update with the output of that test. Thanks!

**Comment by FanHan-NOAA** [comment]
> @FanHan-NOAA thank you for this PR. The tests related to the `sfc_tv_obs_2018041500.nc4` file are failing, and I think the issue is that the develop version (with the old names) is being used in this PR instead of the version with the new names following the jedi conventions. I think if you run the test using the `feature/sprint-ioda-converters` branches and verify that you get the expected changes, then you can update with the output of that test. Thanks!

I've followed your instruction to upload the file again. Hope the tests pass this time.

**Comment by srherbener** [comment]
@FanHan-NOAA thank you for uploading the test reference file. I took a look at this and it is a bit more complicated than simply uploading a test reference file. I think I've got it all fixed now. I had to first resolve the conflict that the feature/sprint-ioda-converters branch had with develop. Then I merged feature/sprint-ioda-converters into this branch followed by updating the test reference file again (to get the proper height values).

It appears to be all in sync now, except that the testing is getting impacted by another defect (jcsda-internal/ioda/issues/703) of which I'm working on getting fixed. Since the defect is independent of the changes you made in #953 I'll go ahead and approve and merge this PR.

Once the defect is repaired, I'll go through again and update test reference files.

**Review by srherbener — APPROVED** [review]

**Comment by srherbener** [comment]
Sorry, need two reviewer approvals before merging so I will wait for @CoryMartin-NOAA's review. Thanks for your patience with this.

**Comment by FanHan-NOAA** [comment]
Thank you @srherbener for your help with this and for explaining what you did. Glad it all worked out!

**Pull request merged**
