### PR TITLE
New marine converter: godae BGC-Argo profiles

### LINKED ISSUE #726: ioda-converter (v2) for BGC-Argo profile observations
## Description

In support of ocean biogeochemical (BGC) data assimilation, a python converter is needed to read in historical or near real-time BGC-Argo profiles from us-godae ftp server and convert them to a unified format that supports IODA v2.

For further details see description [here](https://github.com/JCSDA-internal/soca-science/issues/383).

## Requirements
Same to other "marine" ioda-converters.

### PR DESCRIPTION
**Pull request by liuxiao37k**
## Description

This PR adds a python script to "marine" that reads in historical or near real-time biogeochemical (BGC) Argo profiles from godae ftp server and converts to a unified format that supports IODA v2.

A small example data file (a single pair of upward and downward profile) was fetched from https://biogeochemical-argo.org/data-access.php (godae ftp server). This portal provides historical and near real-time (w/ approximately 24 hours delay) Argo profiles in .nc format from participating Argo fleets.

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #726 
- fixes soca-science issue [#383](https://github.com/JCSDA-internal/soca-science/issues/383)

### CODE REVIEW

**Comment by liuxiao37k** [comment]
Hi @kbhargava - this new marine converter uses hgodas_insitu2ioda.py as a template. It supports IODA v2 format conversion. Can you please provide some initial comments before I request reviews from more folks? Thanks a lot!

**Review by kbhargava — COMMENTED** [review]
Test output
```
Traceback (most recent call last):
  File "/home/jedi/bin/godae_bgc_argo2ioda.py", line 126, in <module>
    main()
  File "/home/jedi/bin/godae_bgc_argo2ioda.py", line 111, in main
    ObsVars, nlocs = iconv.ExtractObsData(prof.data, locationKeyList)
  File "/home/jedi/lib/pyiodaconv/ioda_conv_engines.py", line 160, in ExtractObsData
    ObsVarExamples.append(LocKey[i])
IndexError: tuple index out of range
```

Test output
```
+ SRC_DIR=/jcsda/ioda-bundle/iodaconv/src/marine
+ PYCODESTYLE_CFG_PATH=/jcsda/ioda-bundle/iodaconv
+ cd /jcsda/ioda-bundle/iodaconv/src/marine
+ pycodestyle -v --config=/jcsda/ioda-bundle/iodaconv/.pycodestyle --filename=*.py,*.py.in .
cli configuration: /jcsda/ioda-bundle/iodaconv/.pycodestyle
directory .
checking ./argoClim2ioda.py
checking ./copernicus_l3swh2ioda.py
checking ./copernicus_l4adt2ioda.py
checking ./cryosat_ice2ioda.py
checking ./emc_ice2ioda.py
checking ./gds2_sst2ioda.py
checking ./glider2ioda.py
checking ./gmao_obs2ioda.py
checking ./godae_bgc_argo2ioda.py
./godae_bgc_argo2ioda.py:71:63: W291 trailing whitespace
./godae_bgc_argo2ioda.py:125:1: E305 expected 2 blank lines after class or function definition, found 1
```

**Comment by kbhargava** [comment]
> I have the ctest failing because of
> 
> ```
> ObsVarExamples.append(LocKey[i])
> IndexError: tuple index out of range
> ```

@liuxiao37k So ona closer look it looks  like line 71 and 72 aren't treated as a single statement. You might want to add "/" at the end of line 71 to indicate continuation.

**Comment by liuxiao37k** [comment]
@kbhargava thanks so much for catching the coding norm errors! I fixed them and seem to get past the auto ctest checks.

**Review by kbhargava — APPROVED** [review]
Looks good!

**Review by HamidehGMAO — APPROVED** [review]
Looks fine to me. Thanks

**Comment by liuxiao37k** [comment]
> Looks fine to me. Thanks

@HamidehGMAO @kbhargava Thanks for testing and providing reviews so quickly!

**Review by rhoneyager — APPROVED** [review]

**Pull request merged**
