### PR TITLE
add amsr2 ingest from JAXA remove from NASA script

### LINKED ISSUE #1491: add ingest script for AMSR2 from JAXA
## Description

AMSR/2 data files are publicly available via JAXA for registered users (also free)

## Requirements

wget

### PR DESCRIPTION
**Pull request by BenjaminRuston**
## Description

add a JAXA ingest script that can generically ingest AMSR/2 data

this does require a free registration to the JAXA G-portal but allows access to a large archive or the data

## Issue(s) addressed

Resolves #1491 

## Checklist

- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by ashley314 — APPROVED** [review]
Thanks! I'll be using part of these for onboarding AMSR/2 into the ingest suite :)

**Review by fabiolrdiniz — COMMENTED** [review]
Thanks, @BenjaminRuston!

**Review by fabiolrdiniz — APPROVED** [review]

**Comment by fabiolrdiniz** [comment]
@PatNichols @BenjaminRuston @fcvdb, this should be good to merge, no?

**Review by junmeiban — APPROVED** [review]
Thank you so much @BenjaminRuston for adding this.

**Pull request merged**
