### PR TITLE
changing file permissions

### LINKED ISSUE #1506: ensure decoders have execute permission
## Description
a few python decoders should have their permissions changes to include execute permission by default

## Acceptance Criteria (Definition of Done)
new checkouts of IODA converters have python scripts with execute permissions

### PR DESCRIPTION
**Pull request by BenjaminRuston**
## Description

A number of python scripts do not have execute permission, to be consistent they should be changed.

note the process followed to update permissions for a hypothetical `converter_file.py` below are:
```
chmod 755 converter_file.py
git update-index --chmod=+x  converter_file.py
git commit -m 'changing file permissions'
```

## Issue(s) addressed

Resolves #1506 

## Impact

Lateral move, for current implementations.

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by BenjaminRuston** [comment]
@jeromebarre I've noticed these converters in the `compo` directory that could also be changed.

This doesn't impact anything at present as generally everything is called by preceding the call with `python3` 

here are the files I could change, no changes are made to the contents just an update to the permissions:

```
aeronet_aod2ioda.py
omps_o3_nm_h52ioda.py
tempo_nc2ioda.py
tropess_co_nc2ioda.py
tropomi_no2_co_nc2ioda.py
viirs_aod2ioda.py
viirs_biaswriter.py
viirs_l1bnc2ioda.py
```

**Review by jeromebarre — APPROVED** [review]

**Comment by BenjaminRuston** [comment]
thanks @jeromebarre for the review, did you want me to change the permission on the `compo` ones as well?

**Comment by jeromebarre** [comment]
yes please

**Comment by BenjaminRuston** [comment]
@travissluka any input otherwise think this is now ready

**Review by travissluka — APPROVED** [review]

**Pull request merged**
