### PR TITLE
IODA converter example for adpsfc

### PR DESCRIPTION
**Pull request by nicholasesposito**
## Description

The purpose of the PR is to add an IODA converter example to IODA-Converters. This example will use the bufr2ioda executables to convert an adpsfc bufr file into an IODA-formatted netcdf file using a specified yaml file. This is an enhancement that adds test data.

The yaml and input bufr file have been placed in test/testinput
The output IODA-formatted netcdf file has been placed in test/testoutput
A test named "test_iodaconv_bufr_adpsfc2ioda" has been added to test/CMakeLists.txt

### Issue(s) addressed

The issue is an enhancement documented with issue #396 

## Dependencies

There are no other PRs that need to be merged before this one.

## Impact

Requires changes in the following repositories:
- [ ] ioda-converters

Requires updating test data for the following repositories:
- [ ] ioda-converters.

### CODE REVIEW

**Comment by CoryMartin-NOAA** [comment]
@nicholasesposito looks like you need to merge in 'develop', also for pull requests instead of 'assigning' people you make people 'reviewers'. I've taken the liberty of doing the latter already, but you'll need to merge in develop as this PR has too many changes associated with it right now.

**Comment by CoryMartin-NOAA** [comment]
git checkout develop
git pull
git pull # (for good measure again)
git checkout feature/converter_example
git merge develop

Note you may have to resolve conflicts, if so look for "HEAD and =======" in files.

**Comment by aerorahul** [comment]
Screen Shot 2021-01-22 at 3 10 07 PM
I was able to fix the conflicts, update the yaml file and run the converter.
Attached is a figure.

I found there are some missing values:

```
ncdump -v temperatureAir@ObsValue  test/testrun/gdas.t06z.adpsfc.tm00.nc
   1e+11, 1e+11, 1e+11, 276.55, 276.05, 275.45, 275.35, 274.95, 274.75,
    277.15, 277.15, 277.15, 277.15, 277.15, 277.15, 277.15, 277.15, 278.15,
```

How are `missing_values` handled here?  There should be a attribute for it so that netCDF understands that.  @rmclaren

**Comment by rmclaren** [comment]
@aerorahul The appropriate way to do this is to set the "range" attribute on the ioda variable (in the YAML). At least panoply will ignore values outside the valid range, not sure what ncdump will do.

**Comment by aerorahul** [comment]
netCDF can prescribe a variable attribute such as `_FillValue` or `missing_value`. See [here](https://www.unidata.ucar.edu/software/netcdf/docs/attribute_conventions.html)
We should be able to put that attribute into the netCDF file.


NCEPlibs-bufr assigns missing values as `1e11`.  This is defined in `bfrini.f`

`valid_range` is fine, but we should define a variable attribute `_FillValue` or `missing_value` using the value from bufr data.

**Comment by rmclaren** [comment]
Good point, I should add that.

**Pull request merged**
