### PR TITLE
Bugfix/mcmodel fix

### LINKED ISSUE #1366: New Memory Error
## Current behavior (describe the bug)

I suddenly get the folloing when tryning to compile the latest from the develop branch:

```
[ 58%] Linking Fortran executable ../../bin/bufr2nc_fortran.x
final section layout:
    __TEXT/__text addr=0x100006BB0, size=0x000E9B22, fileOffset=0x00006BB0, type=1
    __TEXT/__stubs addr=0x1000F06D2, size=0x00000282, fileOffset=0x000F06D2, type=29
    __TEXT/__const addr=0x1000F0960, size=0x0000D0D4, fileOffset=0x000F0960, type=0
    __TEXT/__cstring addr=0x1000FDA38, size=0x00023AFF, fileOffset=0x000FDA38, type=13
    __TEXT/__eh_frame addr=0x100121538, size=0x0000AAB0, fileOffset=0x00121538, type=19
    __DATA_CONST/__got addr=0x10012C000, size=0x00000AB0, fileOffset=0x0012C000, type=31
    __DATA_CONST/__const addr=0x10012CAC0, size=0x00000790, fileOffset=0x0012CAC0, type=0
    __DATA/__data addr=0x100130000, size=0x00002AD2, fileOffset=0x00130000, type=0
    __DATA/__common addr=0x100132AE0, size=0x0004F6D8, fileOffset=0x00000000, type=26
    __DATA/__bss addr=0x1001821C0, size=0x000D5C04, fileOffset=0x00000000, type=26
    __DATA/__huge addr=0x100257DE0, size=0xB45E5100, fileOffset=0x00000000, type=26
ld: 32-bit RIP relative reference out of range (2664205810 max is +/-2GB): from ___ahi_hsd_mod_MOD_read_hsd 
(0x10001848D) to ___ahi_hsd_mod_MOD_satzen (0x19ED06360) in '___ahi_hsd_mod_MOD_read_hsd' from 
CMakeFiles/bufr2nc_fortran.x.dir/hsd.f90.o for architecture x86_64
```

Looks like there is something trying to pre-allocate like 3 GB of memory... Might need to use dynamic allocation for this instead in order to reduce the "distance" between the segments of executable code....

Said another way: The memory footprint for the function read_hsd is too large. Its not possible to hold a value large enough in RIP (Relative Instruction Pointer a 32 bit value) to jump to the function satzen.

## Expected behavior

Should compile.

### PR DESCRIPTION
**Pull request by PatNichols**
## Description

This fixes a linking errror when someone uses the gcc c++ compiler on a mac.

## Issue(s) addressed

Resolves #1366 

## Dependencies

None

## Impact

None

## Checklist

- [x ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x ] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by PatNichols** [comment]
@rmclaren could you see if this works for you? Thanks!

**Comment by rmclaren** [comment]
@PatNichols OK that is working much better for me. I think its technically possibly for someone with a Mac to use the Intel compiler as well (though I don't run it this way)... I'm uncertain if we need to support this or not...

**Comment by srherbener** [comment]
Just want to point out that since Apple decided to move to the ARM based processors (M1 and M2), Intel has dropped support for their compiler on Mac M1 and M2 moving forward. Intel will still, for a while, support oneAPI on Intel based Macs but that will eventually get phased out.

It is correct that you can emulate Intel on Mac M1 and M2, using the Rosetta application. But Intel is not supporting this, and we have also decided for JEDI to not support Rosetta. I think it's safe to not worry about Intel on the Mac.

**Comment by rmclaren** [comment]
Sounds good.

**Review by srherbener — APPROVED** [review]
Looks good. Thanks for fixing this!

**Review by rmclaren — APPROVED** [review]

**Pull request merged**
