### PR TITLE
Adding try statement to tropomi converter

### PR DESCRIPTION
**Pull request by ashley314**
## Description

A bug was found when running the observation ingest suite, where the converter would error out if one file out of the group was unable to be opened. This PR adds a try statement to check each file during processing based on suggestions from Fabio. It will not use the file if it cannot open it, but the other files in the batch will be used to convert the observations to iodaformat. 

Previous error message and failing EWOK suite:
```
ncdump: obs.tropomi_s5p_no2.20241105T120000Z.3.nc: NetCDF: Unknown file format
```

New message and continuation of processing:
```
WARNING: This is not a NetCDF file: /Users/agriffin/JEDI_workflow/workdir/ce5b90/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.3.nc
```

## Issue(s) addressed

Resolves https://github.com/JCSDA-internal/ewok/issues/1076

## Dependencies

None

## Impact

Observation ingest CI

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] I have run the unit tests before creating the PR

### CODE REVIEW

**Review by fabiolrdiniz — COMMENTED** [review]
Thanks, @ashley314! My understanding is that CI is going to keep failing with this change (looping over the files). Perhaps some logic is needed to bypass those non-netcdf files.

**Comment by ashley314** [comment]
@fabiolrdiniz When I tested it out with the date that was failing, it still produced the ioda files for that period and continued running the suite. So hard to tell if it will actually fail or not. I can create a fake jedi-bundle PR to test CI with although we have not gotten this failure in a while.

```
-rw-r--r--  1 agriffin  1202617992  180943089 Dec  9 09:48 obs.tropomi_s5p_no2_tropo.20241105T120000Z.nc4
-rw-r--r--  1 agriffin  1202617992  253679202 Dec  9 09:48 obs.tropomi_s5p_no2_total.20241105T120000Z.nc4
```

**Review by fabiolrdiniz — APPROVED** [review]
Thanks, @ashley314! It will fail in the special case having the non-netcdf file as the first element of the list, otherwise it will re-use `ncd` from the previous iteration.

**Comment by ashley314** [comment]
That's a great point about it reusing the `ncd` from the previous iteration. Do you know if that would that duplicate data or just overwrite the info from the previous iteration?

**Comment by fabiolrdiniz** [comment]
I'd expect it to have duplicated values doing that.

**Comment by ashley314** [comment]
Thanks for pointing that out! I added a continue in there so it will skip over the bad file and not duplicate the last processed file. See the following output from testing. 
```
Processing variable: nitrogendioxide_total_column
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.0.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.1.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.10.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.11.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.12.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.13.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.14.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.15.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.16.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.17.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.18.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.19.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.2.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.20.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.21.nc
WARNING: This is not a NetCDF file: /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.3.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.4.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.5.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.6.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.7.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.8.nc
DEBUG: processing file /Users/agriffin/JEDI_workflow/workdir/f22433/20241105T120000Z/obs_tropomi_s5p_no2/obs.tropomi_s5p_no2.20241105T120000Z.9.nc
```

**Comment by fabiolrdiniz** [comment]
Nice! Thanks, @ashley314!

**Review by mer-a-o — APPROVED** [review]
Thanks @ashley314 . I didn't test the PR but the changes look good.

**Review by BenjaminRuston — APPROVED** [review]
huh,, would not have guess it would be an OSError

thanks @ashley314

**Pull request merged**
