### PR TITLE
Revert "Common Calling Structure"

### PR DESCRIPTION
**Pull request by PatNichols**
Reverts JCSDA-internal/ioda-converters#1087

### CODE REVIEW

**Comment by PatNichols** [comment]
@BenjaminRuston @fcvdb This should fix our problems for now.

**Review by BenjaminRuston — APPROVED** [review]
would have preferred to have moved forward but seems like we need to discuss library names first

**Review by srherbener — APPROVED** [review]

**Review by ericlingerfelt — COMMENTED** [review]
I do not believe that we should revert https://github.com/JCSDA-internal/ioda-converters/pull/1087. I think it would be best to create a new bug fix PR that responds to the issues that our users are experiencing.

**Comment by srherbener** [comment]
> I do not believe that we should revert #1087. I think it would be best to create a new bug fix PR that responds to the issues that our users are experiencing.

I think this is a very good point. However, the issue tied to this PR #1158 is suggesting that the develop branch is seriously broken and we need to restore develop to health quickly. But, restoring all of the work in the original feature branch might be difficult.

Would it work to merge this PR into develop now and then go back to the original PR and cherry pick the commits into a new PR. It would be painful if all of that work in the original PR would have to be redone, which is why I'm guessing @ericlingerfelt is suggesting to not merge this PR. 

@climbfuji can you help recommend how we should proceed? Thanks!

**Comment by srherbener** [comment]
Or can we simply merge this PR and then revert it which should re-create the state we are in now on a new feature branch. Then fix the packaging/PYTHONPATH issues on the new feature branch before issuing a PR.

**Comment by climbfuji** [comment]
I agree with @ericlingerfelt that reverting the PR is not a good idea. Decide on a name for the library quickly (i.e. use `lib_iodaconv` instead of `lib_python`), then fix the handful of files (probably less than five), update the documentation and share the information (that's what didn't happen apparently when the original PR was merged) with the developers and users.

**Review by climbfuji — DISMISSED** [review]
Recommend to fix in develop instead of reverting

**Comment by PatNichols** [comment]
@climbfuji @ericlingerfelt I might be in favor of a bugfix branch provided it can be applied quickly ( like in a hour or so). The ioda-develop is failing multiple ctests. This in turn means all the bundles are broken.

**Comment by PatNichols** [comment]
@climbfuji The number of files to fix depends on how you fix it. There are probably dozens if it's just a source code fix. A CMakefile fix might be quicker.

**Comment by PatNichols** [comment]
@climbfuji  Look up to see how many files are changed to get an idea of how many to fix in naive way.

**Comment by climbfuji** [comment]
But wouldn't the easiest way to "for now fix the ctests" be to simply change the ctest setup to append the missing directory to `PYTHONPATH`? This gives you time to think about a better name and update the documentation for users and developers. And it only touches a handful of files, not 100+.

**Comment by climbfuji** [comment]
@PatNichols This change in the iodaconv repository fixes the failing ctest for me (tried on my mac):
```
heinzell@JCSDA-L-18146:~/work/ioda-converters/ioda-bundle/iodaconv [brew-x86_64]> git diff
diff --git a/test/CMakeLists.txt b/test/CMakeLists.txt
index 860a21f8..c1faa990 100644
--- a/test/CMakeLists.txt
+++ b/test/CMakeLists.txt
@@ -407,7 +407,12 @@ set(IODA_CONV_COMP_TOL "0.5e-4")
 #        ENVIRONMENT "PYTHONPATH=$<TARGET_FILE_DIR:_ioda_python>/../"
 #        ...
 #        )
-set(IODACONV_PYTHONPATH "$<TARGET_FILE_DIR:_ioda_python>/../:$ENV{PYTHONPATH}")
+message (INFO "/Users/heinzell/work/ioda-converters/ioda-bundle/iodaconv/src")
+message (INFO "CMAKE_CURRENT_SOURCE_DIR is ${CMAKE_CURRENT_SOURCE_DIR}")
+message (INFO "<TARGET_FILE_DIR:_ioda_python>/../ is $<TARGET_FILE_DIR:_ioda_python>/../")
+set(IODACONV_PYTHONPATH "${CMAKE_CURRENT_SOURCE_DIR}/../src:$<TARGET_FILE_DIR:_ioda_python>/../:$ENV{PYTHONPATH}")
+#set(IODACONV_PYTHONPATH "$<TARGET_FILE_DIR:_ioda_python>/../:$ENV{PYTHONPATH}")
+#set(IODACONV_PYTHONPATH "${CMAKE_CURRENT_SOURCE_DIR}/../src:$ENV{PYTHONPATH}")

 #===============================================================================
 # Marine converters
heinzell@JCSDA-L-18146:~/work/ioda-converters/ioda-bundle/iodaconv [brew-x86_64]> git diff
diff --git a/test/CMakeLists.txt b/test/CMakeLists.txt
index 860a21f8..47452eaa 100644
--- a/test/CMakeLists.txt
+++ b/test/CMakeLists.txt
@@ -407,7 +407,10 @@ set(IODA_CONV_COMP_TOL "0.5e-4")
 #        ENVIRONMENT "PYTHONPATH=$<TARGET_FILE_DIR:_ioda_python>/../"
 #        ...
 #        )
-set(IODACONV_PYTHONPATH "$<TARGET_FILE_DIR:_ioda_python>/../:$ENV{PYTHONPATH}")
+#
+# DH 20230202 - need to add a bit more documentation here why to add ${CMAKE_CURRENT_SOURCE_DIR}/../src
+#
+set(IODACONV_PYTHONPATH "${CMAKE_CURRENT_SOURCE_DIR}/../src:$<TARGET_FILE_DIR:_ioda_python>/../:$ENV{PYTHONPATH}")

 #===============================================================================
 # Marine converters
```
Can you test this, and if it works issue a PR for ioda-converters? 

I'll unblock this PR but I think it's no longer needed

**Review by climbfuji — COMMENTED** [review]
Unblocking this PR

**Review by climbfuji — COMMENTED** [review]
Unblocking this PR, hope this works.

**Comment by PatNichols** [comment]
Now that I have time to breathe i will give it a shot. We still need to make the " no lib_python" folks happy bit ...

**Comment by climbfuji** [comment]
> Now that I have time to breathe i will give it a shot. We still need to make the " no lib_python" folks happy bit ...

Sure, that can be done in a second step. There are probably also documentation/documentation updates needed for users who point to the Python scripts in ioda-converters (but I haven't checked how much is there already and how it needs to change).

**Pull request merged**
