### PR TITLE
Feature/gds2 sst2ioda v2

### LINKED ISSUE #650: Upgrade Python converter for  gds2_sst2ioda to IODA-v2:
Update the converter identified in the title (gds2_sst2ioda.py) to use the IODA-v2 API.

- Update import statement
- Variable dimensions dictionary
- Dimensions dictionary
- Global attributes dictionary
- Remove record numbers
- Update keyDict
- Units, Fill values, other metadata
- Change order of when writer is called
- Remove ExtractoObsData if possible
- Update CMakeLists.txt with environment variable
- Run test to make sure it runs (but will fail because of unupdated test reference)
- Update test reference file
- run unit tests making use of the target converter and verify that they pass. Make sure you verify the results by examining the file using ```ncdump```, ```h5dump```, ```HDFview```, or a similar utility.

## ZenHub organization

Please make sure that you have properly set:
- Labels: OBS3
- Milestone: OBS - October 2021
- Estimate: An estimate of how long this issue will take to resolve. 1 = half a day. 2 = full day.
- Epics: Modify converters to IODAv2 format
- Assignees: Anyone **working** on this issue. Anyone who is not working directly on the issue, but
  who should receive notifications, should be listed below.
- Reviewers: 

## Notifications

Fill in a list of GitHub handles here. People here are not *assigned*, but instead receive notifications
about this issue's progress.

Notifications should always go to: @rhoneyager.

Other people:

### PR DESCRIPTION
**Pull request by HamidehGMAO**
## Description

Upgrade Python converter for gds2_sst2ioda to IODA-v2

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #650

### CODE REVIEW

**Review by guillaumevernieres — CHANGES_REQUESTED** [review]
@HamidehGMAO : The MetaData group is missing ...

**Comment by HamidehGMAO** [comment]
> @HamidehGMAO : The MetaData group is missing ...

Huh! I will take a look

**Comment by HamidehGMAO** [comment]
@srherbener the outputs looks fine now, except it seems the _FillValue part for the PreQC is not right. I don't understand what's wrong here, but QC is missing too. it's right in obs_data, but it's not right when it's written out. Any ideas?

**Comment by srherbener** [comment]
> @srherbener the outputs looks fine now, except it seems the _FillValue part for the PreQC is not right. I don't understand what's wrong here, but QC is missing too. it's right in obs_data, but it's not right when it's written out. Any ideas?

@HamidehGMAO, are you saying that the variables in the PreQC group are getting created but none of the intended values for these variables are showing up in the output file. Plus the _FillValues in the file are not set to the intended values as well.

If that's it, I'm not sure what would be going wrong. You could trace the progress of the PreQC variables from the call to BuildIoda to the place in BuildIoda that writes the data. If you don't have a python debugger, just pick a variable and print it out at various stages. If you catch it changing, then you can home in on the code that caused it to change. If it gets handed off to the ioda python module and is still intact, then perhaps @CoryMartin-NOAA or I could help track down what is going wrong.

**Comment by HamidehGMAO** [comment]
@srherbener right! I'm really confused. I print the qc data here

 https://github.com/JCSDA-internal/ioda-converters/blob/e078a9d8a929fb79403a1aebf0d0a892e2a934d6/src/lib-python/ioda_conv_engines.py#L106

14: VarKey ('sea_surface_temperature', 'PreQC') Vvals [2 2 0 0 0 0 1 2 2 1 2 0 0 0 0 0 0 0 1 2 2 2 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0
14:  0 2 2 2 1 1 0 0 0 2 2 1 0 0 0 0 0 0 0 0 0 2 0 0 0 2]

it seems fine, but then in the output file it's like this
"
group: PreQC {
  variables:
  	short sea_surface_skin_temperature(nlocs) ;
  		sea_surface_skin_temperature:_FillValue = -32767s ;
  	short sea_surface_temperature(nlocs) ;
  		sea_surface_temperature:_FillValue = -32767s ;
  		string sea_surface_temperature:units = "unitless" ;
  data:

   sea_surface_skin_temperature = _, _, _, _, _, _, _, _, _, _, _, _, _, _, 
      _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 
      _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ ;

   sea_surface_temperature = _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 
      _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, 
      _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _ ;
  } // group PreQC
}
"

**Comment by CoryMartin-NOAA** [comment]
@HamidehGMAO @srherbener 99% sure this is because the variable type is `short`. If you force the PreQC to `int32` it will likely work. The `ioda_obs_space` does not yet support `short`.

**Comment by HamidehGMAO** [comment]
Thanks @CoryMartin-NOAA , I will try that!

**Review by guillaumevernieres — APPROVED** [review]
I have not looked at the code but the output file was tested with soca 3dvar. So all good :+1:

**Review by srherbener — APPROVED** [review]

**Pull request merged**
