### PR TITLE
Add ozone QC flags from data provider (in bufr)

### PR DESCRIPTION
**Pull request by emilyhcliu**
Add two ozone data QC flags encoded in the BUFR file from the data provider.

### CODE REVIEW

**Review by fcvdb — APPROVED** [review]
The changes look good. Thanks Emily!

**Comment by CoryMartin-NOAA** [comment]
Why is the build failing in AWS?

**Comment by emilyhcliu** [comment]
@CoryMartin-NOAA I will check.  I did not run ctest before I submitted the PR.

**Comment by emilyhcliu** [comment]
@CoryMartin-NOAA It was the coding norm problem (missing white space).  It is fixed!

**Review by CoryMartin-NOAA — APPROVED** [review]

**Review by huishao-r — APPROVED** [review]

**Pull request merged**
