### PR TITLE
CMake config update for NCEPLIBS-bufr v12.0

### LINKED ISSUE #1292: [Bug] test_iodaconv_prepbufr_ncep_api_adpsfc2ioda is failing on S4 when using bufr@12.0.0
## Current behavior (describe the bug)

I tested bufr v12.0 on S4 using jedi-bundle, including ioda-converters, Intel/Impi and spack-stack-1.4.1. All of the jedi-bundle tests passed except for one ioda-conveters test: `test_iodaconv_prepbufr_ncep_api_adpsfc2ioda' which dumped out this error message:
```
Command: "/usr/bin/bash" "/data/users/sherbener/jedi/build-intel/bin/iodaconv_comp.sh" "netcdf" "/data/users/sherbener/jedi/venv/bin/python3.9 testinput/prepbufr_adpsfc_api.py" "prepbufr_adpsfc_api.nc" "0.0"
Directory: /data/users/sherbener/jedi/build-intel/iodaconv/test
"test_iodaconv_prepbufr_ncep_api_adpsfc2ioda" start time: Jul 12 20:41 UTC
Output:
----------------------------------------------------------
 
 ***********BUFR ARCHIVE LIBRARY ABORT**************
 BUFRLIB: NEMTBB - ITAB (      0) NOT FOUND IN TABLE B                                               
 ***********BUFR ARCHIVE LIBRARY ABORT**************

<end of output>
Test time =   0.68 sec
----------------------------------------------------------
Test Failed.
"test_iodaconv_prepbufr_ncep_api_adpsfc2ioda" end time: Jul 12 20:41 UTC
"test_iodaconv_prepbufr_ncep_api_adpsfc2ioda" time elapsed: 00:00:00
----------------------------------------------------------
```

Not sure if this is a fault in the bufr library or perhaps a usage issue. Here are release notes for bufr v12, and perhaps this error is related to the instructions for using the bufr_4 component. We are currently using the bufr_d component.

https://noaa-emc.github.io/NCEPLIBS-bufr/md__home_runner_work_NCEPLIBS_bufr_NCEPLIBS_bufr_bufr_docs_ReleaseNotes.html

Check out PR #1290 to see the exact CMake configuration changes I used to test bufr v12.0.

## To Reproduce

> What computer are you running on?

S4

> What compilers/modules are you using?

spack-stack-1.4.1
Intel/Impi

> Steps to reproduce the behavior

1. build jedi-bundle including ioda-converters
    a. ecbuild -DBUILD_IODA_CONVERTERS=ON <path-to-source>
2. ctest

## Expected behavior

All tests pass

### PR DESCRIPTION
**Pull request by srherbener**
## Description

This PR contains cmake configuration changes necessary when we update to using version 12.0 of the NCEPLIBS-bufr library (bufr v12.0). In version 12, the bufr::bufr_d component has been deprecated and can be replaced with the bufr::bufr_4 component.

I tested this on S4 using Intel/Impi using jedi-bundle (with BUILD_IODA_CONVERTERS=ON). All the ctests passed except for one ioda-converter test:
```
The following tests FAILED:
	1383 - test_iodaconv_prepbufr_ncep_api_adpsfc2ioda (Failed)
```

The test failure might be related to some update instructions outlined in the bufr v12.0 release notes: https://noaa-emc.github.io/NCEPLIBS-bufr/md__home_runner_work_NCEPLIBS_bufr_NCEPLIBS_bufr_bufr_docs_ReleaseNotes.html

Please do not merge until we are ready to switch to bufr v12.0. I'll leave this in draft form until then as a reminder.

## Issue(s) addressed

Partially addresses #1276
Fixes #1292

## Dependencies

Merging this PR needs to be coordinated with the spack-stack-1.5.0 release which includes the bufr v12.0 library

## Impact

Expected impact on downstream repositories: None

## Checklist

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (N/A)
- [x] I have run the unit tests before creating the PR
- [x] jedi-bundle tests, S4, Intel/Impi, bufr@11.7.1
- [x] jedi-bundle tests, S4, Intel/Impi, bufr@12.0.0

### CODE REVIEW

**Comment by PatNichols** [comment]
@srherbener Could you take a look at   https://github.com/JCSDA-internal/ioda-converters/pull/1221 There seems to be quite a bit of redundancy there. Perhaps merge your changes into his ? He has also updated his code to work with the new library version which isn't covered here.

**Comment by srherbener** [comment]
@rmclaren, @PatNichols, as @PatNichols pointed out I have the same changes here (moving bufr_d to bufr_4) as done in PR #1221. Since all the ctests are passing here, what about merging this PR in now (after removing draft status, and reviews and testing of course) so we are set to go when bufr v12.0 is released.

The plan now is to introduce bufr v12.0 in the spack-stack-1.5.0 release which is targeted for Fri, Sep 8th.

**Comment by rmclaren** [comment]
Should be fine.

**Comment by rmclaren** [comment]
Should we wait until the software stacks are updated? Otherwise people will have issues..

**Comment by srherbener** [comment]
I'm thinking that if it works out, we could switch over the the bufr_4 component now while still using bufr v11.7.1 and then we don't have to make this change later when bringing bufr v12.0 online.

**Review by PatNichols — APPROVED** [review]
Thanks Steve! Got it to work with ioda-bundle using spack stack version 14.1.

**Comment by climbfuji** [comment]
@srherbener Please resolve the conflicts, thanks.!

**Comment by srherbener** [comment]
> @srherbener Please resolve the conflicts, thanks.!

Done!

**Comment by srherbener** [comment]
I have verified that the change to the bufr::bufr_4 component works for bufr@11.7.1, but runs into an issue when using bufr@12.0.0. See https://github.com/JCSDA-internal/ioda-converters/issues/1292 for details.

In this light it seems safe to merge this PR in now (after approval of course) and not have to wait for bufr@12.0.0 to come online. We have to switch to the bufr::bufr_4 component at some point since bufr@12.0.0 only has that component. Might as well do that switch now so it's one less thing to worry about later on.

Does this sound like a reasonable approach? Thanks!

**Review by rmclaren — APPROVED** [review]

**Comment by rmclaren** [comment]
Should be good as long as we've updated the version of NCEPLIB0-bufr everywhere to version 12..

**Comment by srherbener** [comment]
Reading through the spack-stack documentation, https://spack-stack.readthedocs.io/en/1.4.1/PreConfiguredSites.html, it appears that bufr@12.0.0 is available on:
- Orion
- Hercules
- Discover
- Casper
- Cheyenne
- NOAA Parallel Works
- Acorn
- Gaea
- Hera
- Jet
- S4
- AWS Parallel Cluster (Ubuntu 20.04)

The idea is that you use spack-stack-1.4.0 for bufr@11.7.1 and use spack-stack-1.4.1 for bufr@12.0.0. 

Note that David Huber is currently working on installing bufr@11.7.1 into spack-stack-1.4.1 on: Hera, Orion, Hercules, Jet, Gaea, S4, Cheyenne, and the Parallel Works AWS, GCP, and Azure instances. Once this is completed, then you can use spack-stack-1.4.1 and can switch back and forth between bufr@11.7.1 and bufr@12.0.0 with module unload/load/swap commands. See https://github.com/JCSDA/spack-stack/issues/687 for details.

**Comment by srherbener** [comment]
All jedi-bundle tests including `test_iodaconv_prepbufr_ncep_api_adpsfc2ioda` are passing on S4 with @rmclaren's latest commits. Thanks!

**Pull request merged**
