### PR TITLE
Update the SatWinds AMV (from SSEC) ascii2ioda convert to follow JEDI Data Conventions

### LINKED ISSUE #902: Upgrade converter for SatWinds (amv_nesdis_ascii2ioda.py) to follow the JEDI Data Conventions
Update the SatWinds AMV converter ```amv_nesdis_ascii2ioda.py``` to follow the JEDI Data Conventions.  This is a converter started by Ben R and Lindsey H for atmospheric motion vectors (AMV) files on a FTP server at NESDIS.  The files are simple ascii with columns (space-separated) and can easily be read and converted to IODA.

### PR DESCRIPTION
**Pull request by gthompsnJCSDA**
## Description

This PR is intended to update the satwinds python converter ```src/conventional/amv_nesdis_ascii2ioda.py``` to follow the JEDI Data Conventions.  The code was initiated by Ben Ruston and Lindsey Hayden for files retrieved from SSEC FTP server.  They are simple ascii files with spaces between data values for variety of satellites, channels, and parts of the world.

### Issue(s) addressed

- closes #902 

## Acceptance Criteria (Definition of Done)

Successful reviews and ctests

## Dependencies

 - waiting for #901 

## Impact

No impacts expected if kept within ```feature/sprint-ioda-converters``` staging branch

### CODE REVIEW

**Comment by BenjaminRuston** [comment]
@gthompsnJCSDA note these files are not from NESDIS but from SSEC at Wisconsin, are available in near real time with about 1 hour delay from observation time

**Comment by gthompsnJCSDA** [comment]
> @gthompsnJCSDA note these files are not from NESDIS but from SSEC at Wisconsin, are available in near real time with about 1 hour delay from observation time

Gotcha - I just updated text in title and description to SSEC.

**Comment by gthompsnJCSDA** [comment]
Switched this PR to a "draft" because this needs to follow the code structure that gets finalized in #900 first.

**Review by BenjaminRuston — APPROVED** [review]

**Review by BenjaminRuston — CHANGES_REQUESTED** [review]
@gthompsnJCSDA looks like just the other changes of using dictionaries needs to be included...

**Review by srherbener — APPROVED** [review]
Changes look good and the relevant tests are passing.

**Review by BenjaminRuston — APPROVED** [review]

**Pull request merged**
