### PR TITLE
Feature/sprint modis aod converters hb

### LINKED ISSUE #845: Upgrade converter for chem/modis_aod to follow the JEDI Data Conventions
Update the converter identified in the title (hereafter referred to as the **target converter**) to follow the JEDI Data Conventions.

- Update variable names
- Ensure variable units match the units in the conventions table
- Update the global attributes dictionary as needed
- Run the converter test to make sure it runs (but will fail because of unupdated test reference)
- Run ```ioda-validate.x``` on your output file and verify that there are no errors or warnings
- Update test reference file
- Run unit tests making use of the target converter and verify that they pass
- Make sure you verify the results by examining the file using ```ncdump -t```, ```h5dump```, ```HDFview```, or a similar application.

## ZenHub organization

Please make sure that you have properly set:
- Labels: OBS3
- Estimate: An estimate of how long this issue will take to resolve. 1 = half a day. 2 = full day. 3 = two days, 5 = three days.
- Epics: [Sprint: Implement the JEDI Data Conventions in the Converters](https://github.com/JCSDA-internal/ioda-converters/issues/813)
- Assignees: Anyone **working** on this issue. Anyone who is not working directly on the issue, but
  who should receive notifications, should be listed below.
- Reviewers

## Notifications

Fill in a list of GitHub handles here. People here are not *assigned*, but instead receive notifications
about this issue's progress.

Notifications should always go to: @rhoneyager.

Other people:

### PR DESCRIPTION
**Pull request by bhuang95**
## Description

*Update chem/modis_aod converter to follow JEDI IODA convention*

Provide a detailed description of what this PR does.
The ioda-bundle/iodaconv/src/compo/modis_aod2ioda.py converter and the corresponding ctest output file ioda-converters/test/testoutput/modis_aod.nc have been updated to the latest [IODA conventions](https://docs.google.com/spreadsheets/d/1fHb2QIHOwgp4d6plyn9Dj9HZFZsDRxcPaUV6hdTb5BU/edit#gid=0) as of 2022/03/09.

I included "units" for preQC to avoid error after running ioda-validate.x. Instead, there was a warning as below
"Warning: Attribute 'units' is present but is not listed as a required or optional attribute in the spec."

[See the JEDI Documentation](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/pullrequest.html) for further information.

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #845

If this does not close an existing issue, then [be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## Acceptance Criteria (Definition of Done)

Pass ctests test_iodaconv_modis_aod

## Dependencies

If there are PRs that need to be merged before or along with this one, please add "waiting for another PR" label and list the dependencies in the other repositories (example below). Note that the branches in the other repositories should have matching names for the automated tests to pass.
Waiting on the following PRs:
- [ ]

### CODE REVIEW

**Review by gthompsnJCSDA — COMMENTED** [review]
Bo,  have a look at my changes.  They are pretty extensive.  Things worthy of reviewing:
1. how I deal with eliminate the boolean variable called ```First``` which is not needed. Where possible, try to avoid IF-blocks as they are slow in general.
2. As part of above, check the way I did ```np.append``` even though the lines are far longer than coding-norms of 100 chars.  I need to find a way to break these lines to match coding-norms.
3. I saw that you were attempting to make AOD a 2-dimensional array with location by channel, but there are no additional channels being placed into a 2nd dimension.  I would suggest we wait until that 2nd dimension is effectively used and do it then.
4. I realize the original code had a datetime conversion to string, but the original data are already exactly what ```dateTime``` needs with just a single reference line for the units of ```seconds since 1993-01-01T00:00:00Z```  Therefore, I took out string creation - another nice simplification.

**Comment by bhuang95** [comment]
@gthompsnJCSDA Thanks for editing this code. This MODIS AOD converter and another one for VIIRS AOD were managed by other folks before. I basically changed the name convention and modify its dimension from "Location" and ["Location", "Channel"]. I agree with your suggestion on dimension change. I see Ryan's PR #641 on multiple dimensions was approved. I will set it back "Location" dimension and Ryan's PR should let me pass the ioda-validator test. Because VIIRS AOD converters was written similarly as MODIS AOD. I will need to integrate your changes to VIIRS AOD converters. So please put its review on hold and I will keep you posted after it is done.

**Comment by gthompsnJCSDA** [comment]
> @gthompsnJCSDA Thanks for editing this code. This MODIS AOD converter and another one for VIIRS AOD were managed by other folks before. I basically changed the name convention and modify its dimension from "Location" and ["Location", "Channel"]. I agree with your suggestion on dimension change. I see Ryan's PR #641 on multiple dimensions was approved. I will set it back "Location" dimension and Ryan's PR should let me pass the ioda-validator test. Because VIIRS AOD converters was written similarly as MODIS AOD. I will need to integrate your changes to VIIRS AOD converters. So please put its review on hold and I will keep you posted after it is done.


Bo:  Just remember, there is no need to change the modis python script yourself.  Just do a ```git pull``` of your branch because I made direct changes into the branch.  That assumes you agree the changes are all good.  The final file passes ioda-validate.x just fine.  So this particular file could be considered **DONE** if you want.  Meanwhile, it would be very good to adopt my changes to the VIIRS equivalent script.

**Comment by bhuang95** [comment]
> > @gthompsnJCSDA Thanks for editing this code. This MODIS AOD converter and another one for VIIRS AOD were managed by other folks before. I basically changed the name convention and modify its dimension from "Location" and ["Location", "Channel"]. I agree with your suggestion on dimension change. I see Ryan's PR #641 on multiple dimensions was approved. I will set it back "Location" dimension and Ryan's PR should let me pass the ioda-validator test. Because VIIRS AOD converters was written similarly as MODIS AOD. I will need to integrate your changes to VIIRS AOD converters. So please put its review on hold and I will keep you posted after it is done.
> 
> Bo: Just remember, there is no need to change the modis python script yourself. Just do a `git pull` of your branch because I made direct changes into the branch. That assumes you agree the changes are all good. The final file passes ioda-validate.x just fine. So this particular file could be considered **DONE** if you want. Meanwhile, it would be very good to adopt my changes to the VIIRS equivalent script.

Greg, I see. Thanks. Your changes are great. I think it is ready to merger if there are no other comments from the reviewers.

**Comment by rhoneyager** [comment]
The validator passes, but the testoutput file does not match the test reference. https://cdash.jcsda.org/testDetails.php?test=5038942&build=67648

**Comment by bhuang95** [comment]
> The validator passes, but the testoutput file does not match the test reference. https://cdash.jcsda.org/testDetails.php?test=5038942&build=67648
> 
> EDIT: That's odd. Running locally has no issues at all.

@rhoneyager Sorry I must have missed copying to testoutput. It is updated now.

**Review by rhoneyager — APPROVED** [review]

**Pull request merged**
