### PR TITLE
adding conversion of satbias_pc files

### PR DESCRIPTION
**Pull request by shlyaeva**
## Description

Adds conversion of GSI text satbias_pc (preconditioning info for satellite variational bias correction) files into IODA files. 
Conversion is done in the same executable as satbias_in conversion.
This is required to generalize `ufo::ObsBiasCovariance` code which currently reads GSI text files and has hardcoded predictor names.

### Issue(s) addressed

Link the issues to be closed with this PR
- addresses partially https://github.com/JCSDA-internal/ufo/issues/923

### CODE REVIEW

**Review by aerorahul — APPROVED** [review]
code changes to read satbias_pc text file and write out the ioda netcdf looks good.

**Review by fabiolrdiniz — APPROVED** [review]
Thanks, @shlyaeva! Just a question, is there an idea for this key `input coeff file` to replace the `input file` on the ufo side too?

**Comment by shlyaeva** [comment]
@fabiolrdiniz 

> Thanks, @shlyaeva! Just a question, is there an idea for this key `input coeff file` to replace the `input file` on the ufo side too?

@fabiolrdiniz no, I don't plan to do that.

**Comment by weihanucar** [comment]
Looks good !

**Review by weihanucar — APPROVED** [review]

**Pull request merged**
