### PR TITLE
Fix new coding style errors revealed by upgrading pycodestyle from 2.8.0 to 2.11.0

### LINKED ISSUE #1433: Upgrade of pycodestyle from 2.8.0 to 2.11.0 reveals new coding style errors
## Description

During testing of the upcoming spack-stack-1.6.0 release, I found that pycodestyle was upgraded from  version 2.8.0 to 2.11.0 which resulted in flagging coding style errors in several python converters. That is, with pycodestyle@2.8.0 all converters pass but with pycodestyle@2.11.0 a handful of converters do not pass. Here's a list of the failing tests from the LastTestsFailed.log file:
```
 13 1836:iodaconv_compo_coding_norms
 14 1837:iodaconv_gsi_ncdiag_coding_norms
 15 1840:iodaconv_land_coding_norms
 16 1841:iodaconv_lib-python_coding_norms
 17 1842:iodaconv_marine_coding_norms
 18 1849:iodaconv_gnssro_coding_norms
```

With a very quick look, it appears that the new pycodestyle wants to have a space after keywords, whereas the old pycodestyle does not. Eg, `if(...):` is okay with 2.8.0 but is an error with 2.11.0.

## Requirements

All python scripts all pass pycodestyle@2.11.0 checks.

## Acceptance Criteria (Definition of Done)

All coding norms ctests pass.

## Dependencies
None

### PR DESCRIPTION
**Pull request by srherbener**
## Description

The upcoming spack-stack-1.6.0 release includes an upgrade for the pycodestyle package moving from the spack-stack-1.5.1 version, py-pycodestyle@2.8.0, to a newer version, py-pycodestyle@2.11.0. The pycodestyle 2.11.0 is flagging "no white space after keyword" errors (of which pycodestyle@2.8.0 did not). An example is "if(...):" where there is no space after "if". This passes in 2.8.0 and fails in 2.11.0.

This PR fixes all of these case and passes using pycodestyle 2.11.0.

## Issue(s) addressed

Resolves #1433

## Dependencies

List the other PRs that this PR is dependent on:
None

## Impact

Expected impact on downstream repositories:
None

## Checklist

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation (N/A)
- [x] I have run the unit tests before creating the PR
    - iodaconv ctests pass with both pycodestyle versions 2.8.0 and 2.11.0

### CODE REVIEW

**Review by PatNichols — APPROVED** [review]
thanks @srherbener for doing this. Looks good.

**Comment by PatNichols** [comment]
@BenjaminRuston Could you review this please? It's one of those quick reviews where no codde is actually changed just a new format to make coding norms.

**Review by BenjaminRuston — APPROVED** [review]
thanks @srherbener I run this manually often with the new stack assume still call it with just `pycodestyle` and not `py-pycodestyle` ?

**Comment by srherbener** [comment]
> thanks @srherbener I run this manually often with the new stack assume still call it with just `pycodestyle` and not `py-pycodestyle` ?

`py-<package_name>` is the way spack names its package that contain python packages. The actual python packages contained in the spack packages remain named as they were. So, `py-pycodestyle` is only the spack name, and when using in python (ie running manually) it is `pycodestyle`. Hope this helps clarify.

**Pull request merged**
