### PR TITLE
additional NASA mission ingest script

### LINKED ISSUE #1222: add ingest for more NASA missions
## Description
add more pulls from NASA gesdisc for additional missions, specifically GMI and AMSR2

## Requirements

ability to pull NASA mission data from public site

## Acceptance Criteria (Definition of Done)
simple pull works

### PR DESCRIPTION
**Pull request by BenjaminRuston**
## Description

add more NASA mission support

### Issue(s) addressed

- fixes #1222 

## Acceptance Criteria (Definition of Done)

people agree it is useful for a time before full ewok integration

### CODE REVIEW

**Comment by BenjaminRuston** [comment]
@ashley314 will work on converters for this data this provides an archival feed for these data sources not real time.  This is the same data stream from which NRL, NASA and Met Office begin their processing chain

**Review by fabiolrdiniz — APPROVED** [review]
Thanks, @BenjaminRuston. I was able to download these files:

```
-rw-r--r--    1 fabiodiniz  1202617992   2613 Apr 24 12:47 1C.GCOMW1.AMSR2.XCAL2016-V.20170915-S233914-E011806.028360.V07A.HDF5
-rw-r--r--    1 fabiodiniz  1202617992   2613 Apr 24 12:47 1C.GCOMW1.AMSR2.XCAL2016-V.20170915-S220021-E233913.028359.V07A.HDF5
-rw-r--r--    1 fabiodiniz  1202617992   2613 Apr 24 12:47 1C.GCOMW1.AMSR2.XCAL2016-V.20170915-S202128-E220020.028358.V07A.HDF5
-rw-r--r--    1 fabiodiniz  1202617992   2613 Apr 24 12:47 1C.GCOMW1.AMSR2.XCAL2016-V.20170915-S184235-E202127.028357.V07A.HDF5
-rw-r--r--    1 fabiodiniz  1202617992   2613 Apr 24 12:47 1C.GCOMW1.AMSR2.XCAL2016-V.20170915-S170342-E184234.028356.V07A.HDF5
-rw-r--r--    1 fabiodiniz  1202617992   2613 Apr 24 12:47 1C.GCOMW1.AMSR2.XCAL2016-V.20170915-S152449-E170341.028355.V07A.HDF5
-rw-r--r--    1 fabiodiniz  1202617992   2613 Apr 24 12:47 1C.GCOMW1.AMSR2.XCAL2016-V.20170915-S134556-E152448.028354.V07A.HDF5
-rw-r--r--    1 fabiodiniz  1202617992   2613 Apr 24 12:47 1C.GCOMW1.AMSR2.XCAL2016-V.20170915-S120703-E134555.028353.V07A.HDF5
-rw-r--r--    1 fabiodiniz  1202617992   2613 Apr 24 12:47 1C.GCOMW1.AMSR2.XCAL2016-V.20170915-S102810-E120702.028352.V07A.HDF5
-rw-r--r--    1 fabiodiniz  1202617992   2613 Apr 24 12:47 1C.GCOMW1.AMSR2.XCAL2016-V.20170915-S084917-E102809.028351.V07A.HDF5
-rw-r--r--    1 fabiodiniz  1202617992   2613 Apr 24 12:47 1C.GCOMW1.AMSR2.XCAL2016-V.20170915-S071024-E084916.028350.V07A.HDF5
-rw-r--r--    1 fabiodiniz  1202617992   2613 Apr 24 12:47 1C.GCOMW1.AMSR2.XCAL2016-V.20170915-S053131-E071023.028349.V07A.HDF5
-rw-r--r--    1 fabiodiniz  1202617992   2613 Apr 24 12:47 1C.GCOMW1.AMSR2.XCAL2016-V.20170915-S035238-E053130.028348.V07A.HDF5
-rw-r--r--    1 fabiodiniz  1202617992   2613 Apr 24 12:47 1C.GCOMW1.AMSR2.XCAL2016-V.20170915-S021345-E035237.028347.V07A.HDF5
-rw-r--r--    1 fabiodiniz  1202617992   2613 Apr 24 12:47 1C.GCOMW1.AMSR2.XCAL2016-V.20170915-S003452-E021344.028346.V07A.HDF5
```

using this command: `bash retrieve_from_nasa.sh 20170915`.

**Review by hailingz — APPROVED** [review]
I agree  "it is useful". Thank you!

**Comment by ashley314** [comment]
This is great. I'm trying to write the EWOK suite in a way to kick off all of these ingest scripts scattered across the bundle. I get "Username/Password Authentication Failed" when trying to run. Is there only certain people with access? I see the data online though.

**Comment by fabiolrdiniz** [comment]
@ashley314, yes, you need to have an account on https://disc.gsfc.nasa.gov/earthdata-login, and a `.netrc` fille with your credentials like:

```
machine urs.earthdata.nasa.gov login YOUR_USERNAME password YOUR_PASSWORD
```

**Comment by ashley314** [comment]
Thanks @fabiolrdiniz it is working now for me :)

**Review by ashley314 — APPROVED** [review]
Working for me thanks!

**Comment by gmao-jjin3** [comment]
@BenjaminRuston I have no objection to this PR and appreciate your efforts. We, at GMAO, don't download AMSR2 or GMI data from DSIC, however.  We get near-real-time AMSR2 and GMI HDF5 files directly from the NASA GPM team. In addition, we use Level 1B for AMSR2, and level 1C-R for GMI.

**Pull request merged**
