### PR TITLE
[draft] add script to ingest and convert AMV from SSEC

### LINKED ISSUE #1384: sample ingest and conversion script for geo AMV from SSEC
## Description
the SSEC at UW-Madison has a public facing archive of geostationary atmospheric motion vectors (AMVs) which are useful for a secondary feed of these data

### PR DESCRIPTION
**Pull request by BenjaminRuston**
## Description

sample script for ingest and conversion of AMV from SSEC

## Issue(s) addressed

Resolves #1384

### CODE REVIEW

**Comment by BenjaminRuston** [comment]
@ashley314 are you done with this,, assume yes?

**Comment by ashley314** [comment]
@BenjaminRuston I have not started AMV yet, hopefully next sprint. I can close this after that is done or copy the files now, either works for me. Thanks for checking!

**Comment by ashley314** [comment]
copied them for my notes, feel free to close

**Comment by BenjaminRuston** [comment]
this has been transferred to ingest scripts where it is more appropriate

**Pull request closed without merging**
