### PR TITLE
Feature/sprint ioda greg bufr2ioda3

### PR DESCRIPTION
**Pull request by gthompsnJCSDA**
## Description

This is a follow-up of #874 which was already merged.  Since I reduced the size of a testinput MHS satellite file, a few of the older ctests were failing.  So I reverted back to the develop branch of the input file and re-ran 4 tests that all used the same file and re-updated all the output files.

### Issue(s) addressed

See the PR mentioned above for which issue relates to this PR as well.

## Acceptance Criteria (Definition of Done)

Passing tests

## Dependencies

No direct dependencies except #874  was already merged into ```feature/sprint-ioda-converters```

## Impact

None (as long as it stays in the sprint feature branch)

### CODE REVIEW

**Comment by gthompsnJCSDA** [comment]
> @gthompsnJCSDA it looks like this PR is based on the wrong branch (develop). Should it be based on `feature/sprint-ioda-converters` instead? Thanks!


Yes, I messed that up, thanks.  HOWEVER, this is the sorta thing I was afraid of.  It now claims there are 38 different files.  Frustrating.  Confused.  There should be 4 files in the test/testoutput dir only that differ from what was previously merged. It appears I need to merge sprint-ioda-converters back in.  Stay tuned another minute or two.

**Comment by srherbener** [comment]
> > @gthompsnJCSDA it looks like this PR is based on the wrong branch (develop). Should it be based on `feature/sprint-ioda-converters` instead? Thanks!
> 
> Yes, I messed that up, thanks. HOWEVER, this is the sorta thing I was afraid of. It now claims there are 38 different files. Frustrating. Confused. There should be 4 files in the test/testoutput dir only that differ from what was previously merged. It appears I need to merge sprint-ioda-converters back in. Stay tuned another minute or two.

Just want to double check - you mentioned that this PR should be updating 4 files, but it's reporting only 3 files have changed. Is 3 the correct number? Thanks!

**Comment by gthompsnJCSDA** [comment]
@srherbener   Just to be really, really sure of it, I updated one more file to match so now there are 4 files.  Thanks for double-checking.  Hopefully these 4 ctests now pass.  For brevity, there will be 4 ctests for converting and 4 for ioda-validate:

- test_iodaconv_bufr_mhs2ioda
- test_iodaconv_bufr_filtering
- test_iodaconv_bufr_splitting
- test_iodaconv_bufr_filter_split

and

- iodaconv_validate_testoutput_gdas.t18z.1bmhs.tm00.nc
- iodaconv_validate_testoutput_gdas.t18z.1bmhs.tm00.filtering.nc
- iodaconv_validate_testoutput_gdas.t18z.1bmhs.tm00.15.seven.split.nc
- iodaconv_validate_testoutput_gdas.t18z.1bmhs.tm00.15.7.filter_split.nc

**Review by srherbener — APPROVED** [review]
Thanks for fixing these test files!

**Comment by gthompsnJCSDA** [comment]
@srherbener   I had too many feature branches that I was switching back and forth so I kept clobbering input and output files.  Now, I finally think I straightened everything out and ran all 8 ctests mentioned above and it all seems to be working finally.

**Comment by srherbener** [comment]
Thanks @gthompsnJCSDA for your diligence in getting this working. I'll go ahead and merge since it's just a test file only update to get more tests passing.

**Pull request merged**
