### PR TITLE
Feature/jbresch rsync

### PR DESCRIPTION
**Pull request by PatNichols**
Description

This PR will merge changes from the Jamie Bresch obs2ioda branch into ioda converters.

Issue(s) addressed

Resolves https://github.com/JCSDA-internal/ioda-converters/issues/1277

Impact

No expected impacts to jedi codes.

## Checklist

- [x ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ x] I have run the unit tests before creating the PR

### CODE REVIEW

**Comment by PatNichols** [comment]
this still needs an update to the test files for the ctest to pass but the mopitt_nc thing is gone.

**Comment by PatNichols** [comment]
@BenjaminRuston feel free to play with who reviews when the time comes.

**Comment by BenjaminRuston** [comment]
try upgrading the 3 files like this:

```
ioda-bundle/iodaconv/build/bin/ioda-upgrade-v1-to-v2.x amsua_metop-b_obs_2020110112.nc4 amsua_metop-b_obs_2020110112.upgraded.nc4

```

**Comment by BenjaminRuston** [comment]
the 3 files are:
```
/test/testoutput/amsua_metop-b_obs_2020110112.nc4
/test/testoutput/mhs_metop-b_obs_2020101215.nc4
/test/testoutput/sondes_obs_2020093018.nc4
```

**Comment by PatNichols** [comment]
The following tests FAILED:
	704 - test_iodaconv_prepbufr_conv (Failed)
	705 - test_iodaconv_mhs_conv (Failed)
	706 - test_iodaconv_amsua_conv (Failed)
The testoutput files to be updated

**Comment by PatNichols** [comment]
@BenjaminRuston  There are still some differences due to conventions and bad code. For examples dateTime expressed as a string vs. epoch. In some cases, it seems that the output files from this PR are more correct than the converted versions of develop. For example air_temperatures are realistic (~300K vs 2K).

**Comment by BenjaminRuston** [comment]
@PatNichols agree,  please revert the files back to original

@fcvdb will try to have a look at the new files and the reference ones

**Comment by PatNichols** [comment]
@BenjaminRuston it passed now :)

**Comment by PatNichols** [comment]
@hailingz @BenjaminRuston @ashley314 Could you check this? I believe it's ready to merge. Thank you!

**Comment by PatNichols** [comment]
@ashley314 Can you give this branch a try to see if it works for your needs? Thanks

**Comment by ashley314** [comment]
Yes! Sorry I missed this. I'll be able to test it out today/tomorrow. Thanks for putting it all together

**Comment by ashley314** [comment]
@PatNichols is there an equivalent to `obs2ioda-v2.x` in this branch? I'm looking for something similar to [NCAR's obs2ioda-v2](https://github.com/NCAR/obs2ioda/tree/main/obs2ioda-v2)

**Comment by PatNichols** [comment]
> @PatNichols is there an equivalent to `obs2ioda-v2.x` in this branch? I'm looking for something similar to [NCAR's obs2ioda-v2](https://github.com/NCAR/obs2ioda/tree/main/obs2ioda-v2)

@ashley314 Yes it should be nearly tthe same as  obs2ioda.x. We use the name bufr2nc_fortran.x since it's more descriptive of what this program does. Thanks.

**Comment by ashley314** [comment]
@PatNichols thanks, I was able to use `bufr2nc_fortran.x` to convert prepbufr data and AMSUA data! The file sizes are a little different when comparing the output with `obs2ioda-v2.x`. Another thing I noticed is that this PR does not set `min_datetime` and `max_datetime` when looking at the global attributes. I am not sure if that is useful or needed in the converted files. 

**This PR (bufr2nc_fortran):**
```
netcdf sondes_obs_2021010106 {
dimensions:
	nvars = 5 ;
	nlocs = 2159 ;
	nstring = 50 ;

// global attributes:
		:nvars = 5 ;
		:nlocs = 2159 ;
		:nstring = 50 ;
		:min_datetime = "" ;
		:max_datetime = "" ;
```

**NCAR converter (obs2ioda-v2):**
```
netcdf sondes_obs_2021010106 {
dimensions:
	nvars = 5 ;
	nlocs = 2159 ;
	nstring = 50 ;

// global attributes:
		:nvars = 5 ;
		:nlocs = 2159 ;
		:nstring = 50 ;
		:min_datetime = "2021-01-01T04:34:48Z" ;
		:max_datetime = "2021-01-01T07:20:28Z" ;
```

**Comment by BenjaminRuston** [comment]
compared output from NCAR repository and JCSDA for this converter one bit of metaData is different:

```
(venv) JCSDA-L-17733: /202202 >diff -dwib ncar_repo/amsua_metop-b_obs_2022021600.hdr.txt jcsda_repo/amsua_metop-b_obs_2022021600.hdr.txt
14,15c14,15
< 		:min_datetime = "2022-02-15T21:00:01Z" ;
< 		:max_datetime = "2022-02-16T02:59:59Z" ;
---
> 		:min_datetime = "" ;
> 		:max_datetime = "" ;
```

and one produces `.h5` while the other `.nc4` but looks like output is same otherwise

**Comment by gthompsnJCSDA** [comment]
@BenjaminRuston   And, by the way, since min and max datetime has zero implications and are deprecated, they can be totally ignored.

**Review by smaticka — APPROVED** [review]
Thanks @PatNichols !

The ioda-converter successfully compiled and worked on the `amsua` data I tested: `/ioda-bundle/iodaconv/test/testinput/gdas.t00z.1bamua.tm00.bufr_d`. I think it would help users if there were a README or some way to know the required syntax, as well as what instruments it should work on. The syntax that worked in the end was: 

`bufr2nc_fortran.x -i {inputfile_directory} -o {output_directory} {inputfile_name}`

**Review by BenjaminRuston — APPROVED** [review]
tested with gnu on Mac and spack-stack v1.4.0 looked at AMSU-A comparing NCAR version with JCSDA one in this PR, values match

**Comment by hailingz** [comment]
does this help? @smaticka 
https://github.com/JCSDA-internal/ioda-converters/blob/feature/jbresh_rsync/src/ncar-bufr2nc-fortran/README.md

**Comment by BenjaminRuston** [comment]
@ashley314 yes the `min_datetime` and `max_datetime` are not used and not part of the conventions

@ibanos90 would be super helpful if you could test, this should match for `amsua` and `mhs` will march through other datatype next.  would be happy to take suggestions if you would like to use this version

**Comment by smaticka** [comment]
> does this help? @smaticka https://github.com/JCSDA-internal/ioda-converters/blob/feature/jbresh_rsync/src/ncar-bufr2nc-fortran/README.md

Yes, thanks @hailingz ! I didn't know that was there. I'll look in `ioda-converters/src/` next time.

**Comment by ibanos90** [comment]
> @ashley314 yes the `min_datetime` and `max_datetime` are not used and not part of the conventions
> 
> @ibanos90 would be super helpful if you could test, this should match for `amsua` and `mhs` will march through other datatype next. would be happy to take suggestions if you would like to use this version

Hi @BenjaminRuston, I will test it and let you know. I am sorry for the late reply.

**Comment by hailingz** [comment]
which date are you testing with? I know Metop-a died in late 2021. not sure why n15 is missing. @smaticka

**Comment by ibanos90** [comment]
Hi @BenjaminRuston, I compiled the ioda-bundle and run the ctests. Two tests failed but do not seem to be related to this converter. In this sense, I looked for a specific ctest to test the `bufr2nc_fortran` converter but didn't find one. Did I miss it?
```
The following tests FAILED:
        631 - test_iodaconv_sondetac (Failed)
        712 - test_iodaconv_generic_bufr_raob (Failed)
```
I tested the converter using amsua and mhs for 2021012218 and it successfully created the ioda-v2 files matching the same number of observations and satellites as with obs2ioda. After converting to v3, the only difference I found is the empty `min_datetime` and `max_datetime`, similar to a previous comment here (which seems to be deprecated). 
I was wondering if there are any plans to make the changes inside the converter so it can upgrade directly to v3 instead of v2.

One thing I would like to mention for other data types is that the obs2ioda converter fails to correctly write out the station ID and variable names in some observation types, such as sondes and sfc, that have a “station_id” MetaData array. Same behavior is shown when using the NCAR-converter (not sure if you have noticed it). This is due to a caveat in the NetCDF-Fortran interface. To fix this, we use the ioda-upgrade-v1-to-v2.x for these specific observations types (after obs2ioda), then upgrade from v2 to v3. Otherwise it will fail to upgrade to v3.

At the moment, we may not use this converter since most of the tests we run are for a specific time period and we already have the observations converted (not running the real-time experiment at the moment). However, we may consider using it when moving to a different time period.

**Comment by ibanos90** [comment]
I forgot to mention that it would be nice if the `scan_position` output here could be changed to `integer` in order to account for the fix in https://github.com/JCSDA-internal/ufo-data/pull/352.

**Comment by gthompsnJCSDA** [comment]
> I forgot to mention that it would be nice if the `scan_position` output here could be changed to `integer` in order to account for the fix in [JCSDA-internal/ufo-data#352](https://github.com/JCSDA-internal/ufo-data/pull/352).

Thanks!  All of the items you listed are next on our TO-DO list since it will be good to get all types of data properly converted with as little extra steps as possible.

**Comment by ibanos90** [comment]
> > I forgot to mention that it would be nice if the `scan_position` output here could be changed to `integer` in order to account for the fix in [JCSDA-internal/ufo-data#352](https://github.com/JCSDA-internal/ufo-data/pull/352).
> 
> Thanks! All of the items you listed are next on our TO-DO list since it will be good to get all types of data properly converted with as little extra steps as possible.

Great, thanks!

**Comment by BenjaminRuston** [comment]
@ibanos90 thanks for the review, and yes we have some further clean-up to do.

We would like to keep this converter inline for a handful of datatypes,, primarily amsua, mhs, iasi, cris and the prepBUFR.  We are also establishing redundant capability with the EMC converter, amsua looks ready to go so can pass that along

**Comment by smaticka** [comment]
> which date are you testing with? I know Metop-a died in late 2021. not sure why n15 is missing. @smaticka

@hailingz I'm not sure what the date is. It is the `bufr` provided in the `testinput` dir:  `/ioda-bundle/iodaconv/test/testinput/gdas.t00z.1bamua.tm00.bufr_d`

I'm not sure how to inspect the `bufr_d` attributes/meta data/header info.

**Comment by ibanos90** [comment]
> @ibanos90 thanks for the review, and yes we have some further clean-up to do.
> 
> We would like to keep this converter inline for a handful of datatypes,, primarily amsua, mhs, iasi, cris and the prepBUFR. We are also establishing redundant capability with the EMC converter, amsua looks ready to go so can pass that along

Thanks @BenjaminRuston! Yes, amsua looks good.

**Pull request merged**
