### PR TITLE
Fix to read afwa snow depth lat/lon using pygrib when southern/northern hemisphere grib1 file is read  

### LINKED ISSUE #421: Fix wrong lat/lon for afwa snowDepth converter when stereographic projection is used
## Description

Need to modify the converter python codes using pyproj to calculate lat/lon when North/South polar stereographic projection parameters are used. For test cases with small region data,  this issue is not found. However, the users found this bug when the converters are used for northern/southern hemisphere AFWA grib1 data file and IMS grib2 data file to ask me to fix.

## Requirements

This bug will be fixed to output the correct latitudes and longitudes.

## Acceptance Criteria (Definition of Done)

The python codes will be modified to pass ctest, commit to a feature branch and finally the modified codes will be merged into development branch.

## Dependencies

No

### PR DESCRIPTION
**Pull request by YoulongXia-NOAA**
## Description

*(Instructions: replace text in this and all sections with your own text)*

When southern and northern AFWA snow depth grib1 files are read using pygrib, the latitudes and longitudes are not correct. We need to use  pyproj  and dx, dy to calculate latitude and longitude values. This issue may be associated with either AFWA grib1 file format or pygrib capability in handling grib1 format file. The actual reason remains unclear and need a further investigation. At least now current code works for AFWA snow depth grib1 file to obtain correct latitude and longitude values.  By the way, unit % for IMS snow is also added.

### Issue(s) addressed

Link the issues to be closed with this PR
- fixes #421 

If this does not close an existing issue, then [be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)

## Acceptance Criteria (Definition of Done)

The code is merged into the development branch.

## Dependencies

No dependency

## Impact

No impact 

## Test Data

Please list the test data (if any) that needs to be updated on AWS to the best of your knowledge (example below).

No

### CODE REVIEW

**Review by srherbener — APPROVED** [review]
I tested this on my iMac including the USE_PYGRIB=1 to enable this test. All the ioda converter tests pass. Thanks for fixing this.

The CI testing hasn't been upgraded yet to enable the pygrib related tests. This work is being tracked in ZenHub issue #371.

**Comment by srherbener** [comment]
Please review - this has been open for way too long.

**Review by gthompsnJCSDA — APPROVED** [review]
All sounds good to me.

**Comment by srherbener** [comment]
@gthompsnJCSDA thanks for the quick response!

**Comment by YoulongXia-NOAA** [comment]
Stephen and Greg, thank you for your time and effort to review this PR. Well done!

**Pull request merged**
